'use strict';
/**
 * megapack4.js — Ultra Command Pack 4
 * 500 AI-powered commands: Comparisons, Roleplay, Horror, Random Gen,
 * Life Hacks, Deep Questions, Advice AI, Micro Stories, Futurism, Misc
 * + 10 Hidden Commands
 */
const pollinations = require('../lib/pollinations');

function makeCmd(emoji, sys) {
  return async (sock, msg, args) => {
    const jid = msg.key.remoteJid;
    const topic = args.join(' ');
    if (!topic) return sock.sendMessage(jid, { text: `${emoji} _Give me a topic or question!_` }, { quoted: msg });
    await sock.sendMessage(jid, { text: `${emoji} _Processing..._` }, { quoted: msg });
    try {
      const reply = await pollinations.textGenerate([
        { role: 'system', content: sys },
        { role: 'user', content: topic },
      ]);
      await sock.sendMessage(jid, { text: `${emoji} ${reply}\n\n_⚡ DollarBot V-Ultra_` }, { quoted: msg });
    } catch (e) {
      await sock.sendMessage(jid, { text: `❌ Error: ${e.message}` }, { quoted: msg });
    }
  };
}

const SYS = {
  comp: 'You are an objective comparison expert. Compare things fairly and thoroughly. WhatsApp markdown only. No tables or HTML.',
  role: 'You are a master storyteller and roleplay guide. Create rich, immersive content. WhatsApp markdown only.',
  horror: 'You are a horror fiction writer. Write genuinely scary, atmospheric horror. WhatsApp markdown only. Keep it creative fiction.',
  gen: 'You are a creative generator AI. Generate detailed, creative content. WhatsApp markdown only. No tables or HTML.',
  hack: 'You are a life optimization expert. Give practical, clever life hacks and tips. WhatsApp markdown only. No tables or HTML.',
  deep: 'You are a deep thinker and philosopher. Engage with questions at their deepest level. WhatsApp markdown only. No tables or HTML.',
  adv: 'You are a wise, practical advisor. Give clear, actionable advice. WhatsApp markdown only. No tables or HTML.',
  story: 'You are a master micro-fiction writer. Write powerful, complete stories in minimal words. WhatsApp markdown only.',
  future: 'You are a futurist and technology forecaster. Explore future possibilities. WhatsApp markdown only. No tables or HTML.',
  misc: 'You are a brilliant, versatile AI. Give the best possible response. WhatsApp markdown only. No tables or HTML.',
};

module.exports = {
  // ── Comparisons (50) ──────────────────────────────────────────────────────
  vscompare2:   makeCmd('⚖️', SYS.comp + ' Compare these two things:'),
  matchup2:     makeCmd('🥊', SYS.comp + ' Do a detailed matchup between:'),
  headtohead:   makeCmd('👊', SYS.comp + ' Do a head-to-head analysis of:'),
  ranking2:     makeCmd('🏆', SYS.comp + ' Rank these from best to worst:'),
  tierlist2:    makeCmd('📊', SYS.comp + ' Create a tier list for:'),
  best4:        makeCmd('🥇', SYS.comp + ' What\'s the best option for:'),
  worst4:       makeCmd('👎', SYS.comp + ' What\'s the worst option for:'),
  goat3:        makeCmd('🐐', SYS.comp + ' Who or what is the GOAT of:'),
  overrate:     makeCmd('😒', SYS.comp + ' What\'s overrated about:'),
  underrate2:   makeCmd('💎', SYS.comp + ' What\'s underrated about:'),
  mainstream2:  makeCmd('📢', SYS.comp + ' Compare mainstream vs alternative:'),
  classic3:     makeCmd('🏛️', SYS.comp + ' Compare classic vs modern:'),
  oldvsnew:     makeCmd('⚖️', SYS.comp + ' Compare old vs new approach to:'),
  tradition3:   makeCmd('📜', SYS.comp + ' Compare traditional vs progressive:'),
  simplvcomp:   makeCmd('⚖️', SYS.comp + ' Compare simple vs complex approach to:'),
  cheapvsprem:  makeCmd('💰', SYS.comp + ' Compare budget vs premium for:'),
  diyvspr:      makeCmd('🔧', SYS.comp + ' Compare DIY vs professional for:'),
  onlinevs:     makeCmd('🌐', SYS.comp + ' Compare online vs offline for:'),
  manualvs:     makeCmd('⚙️', SYS.comp + ' Compare manual vs automated for:'),
  humanvsai:    makeCmd('🤖', SYS.comp + ' Compare human vs AI for:'),
  naturevs:     makeCmd('🧬', SYS.comp + ' Compare nature vs nurture for:'),
  eastvswest:   makeCmd('🌍', SYS.comp + ' Compare Eastern vs Western approaches to:'),
  sciencevs:    makeCmd('🔬', SYS.comp + ' Compare science vs religion for:'),
  logicvs:      makeCmd('🧠', SYS.comp + ' Compare logic vs intuition for:'),
  shortvslong:  makeCmd('⏱️', SYS.comp + ' Compare short-term vs long-term approach to:'),
  qualityvs:    makeCmd('⚖️', SYS.comp + ' Compare quality vs quantity for:'),
  speedvs:      makeCmd('⚡', SYS.comp + ' Compare speed vs accuracy for:'),
  freevspaid:   makeCmd('💰', SYS.comp + ' Compare free vs paid options for:'),
  solvsteam:    makeCmd('👥', SYS.comp + ' Compare solo vs team approach to:'),
  rigidvsflex:  makeCmd('🔄', SYS.comp + ' Compare rigid vs flexible approach to:'),
  introvextr:   makeCmd('🤫', SYS.comp + ' Compare introverted vs extroverted approach to:'),
  urbanvsrurl:  makeCmd('🏙️', SYS.comp + ' Compare urban vs rural life for:'),
  minimvmaxi:   makeCmd('⚖️', SYS.comp + ' Compare minimalist vs maximalist approach to:'),
  specialistvs: makeCmd('🎯', SYS.comp + ' Compare specialist vs generalist for:'),
  systemvgoals: makeCmd('📊', SYS.comp + ' Compare systems vs goals approach to:'),
  processvs:    makeCmd('🔄', SYS.comp + ' Compare process vs outcome focus for:'),
  openvclose:   makeCmd('🔓', SYS.comp + ' Compare open vs closed approach to:'),
  centralvde:   makeCmd('🌐', SYS.comp + ' Compare centralized vs decentralized for:'),
  analog3b:     makeCmd('📻', SYS.comp + ' Compare analog vs digital for:'),
  passive3b:    makeCmd('💤', SYS.comp + ' Compare passive vs active approach to:'),
  topdownvs:    makeCmd('⬇️', SYS.comp + ' Compare top-down vs bottom-up for:'),
  pushvspull:   makeCmd('🔄', SYS.comp + ' Compare push vs pull strategy for:'),
  broadvsnarrow:makeCmd('🎯', SYS.comp + ' Compare broad vs niche focus for:'),
  earlyvslate:  makeCmd('⏰', SYS.comp + ' Compare early vs late start for:'),
  fastvsslow:   makeCmd('⚡', SYS.comp + ' Compare fast vs slow approach to:'),
  hardvsoft:    makeCmd('💪', SYS.comp + ' Compare hard vs soft skills for:'),
  quantvsqual:  makeCmd('📊', SYS.comp + ' Compare quantitative vs qualitative approach to:'),
  reactvproact: makeCmd('🔄', SYS.comp + ' Compare reactive vs proactive approach to:'),
  emotvlogic2:  makeCmd('❤️', SYS.comp + ' Compare emotional vs logical decision making for:'),
  riskvssafe:   makeCmd('🎲', SYS.comp + ' Compare risky vs safe approach to:'),

  // ── Roleplay (50) ─────────────────────────────────────────────────────────
  narrator3:    makeCmd('📖', SYS.role + ' Be an omniscient narrator and describe:'),
  storyteller3: makeCmd('🎭', SYS.role + ' Tell a compelling story about:'),
  dungeonmaster:makeCmd('🎲', SYS.role + ' As a dungeon master, create a scenario about:'),
  gmscene:      makeCmd('🗡️', SYS.role + ' Create a tabletop RPG scene for:'),
  npc3:         makeCmd('🧑', SYS.role + ' Play an NPC character in context of:'),
  villain4:     makeCmd('🦹', SYS.role + ' Play a villain character who says:'),
  hero5:        makeCmd('🦸', SYS.role + ' Play a hero character who responds to:'),
  sidekick3:    makeCmd('🤝', SYS.role + ' Play a loyal sidekick reacting to:'),
  mentor6:      makeCmd('🎓', SYS.role + ' Play a wise mentor advising about:'),
  sage2:        makeCmd('📜', SYS.role + ' Play a ancient sage sharing wisdom about:'),
  wizard3:      makeCmd('🧙', SYS.role + ' Play a wizard explaining:'),
  warrior3:     makeCmd('⚔️', SYS.role + ' Play a warrior speaking about:'),
  rogue3:       makeCmd('🗡️', SYS.role + ' Play a rogue character in context of:'),
  ranger3:      makeCmd('🏹', SYS.role + ' Play a ranger character in:'),
  paladin2:     makeCmd('⚔️', SYS.role + ' Play a paladin responding to:'),
  bard3:        makeCmd('🎵', SYS.role + ' Play a bard singing or telling about:'),
  pirate3:      makeCmd('🏴‍☠️', SYS.role + ' Play a pirate captain speaking about:'),
  explorer3:    makeCmd('🗺️', SYS.role + ' Play an explorer discovering:'),
  adventurer3:  makeCmd('⚔️', SYS.role + ' Play an adventurer encountering:'),
  knight3:      makeCmd('⚔️', SYS.role + ' Play a knight responding to:'),
  king3:        makeCmd('👑', SYS.role + ' Play a king making proclamation about:'),
  queen3:       makeCmd('👑', SYS.role + ' Play a queen responding to:'),
  soldier3:     makeCmd('🪖', SYS.role + ' Play a soldier in context of:'),
  general2:     makeCmd('⭐', SYS.role + ' Play a general giving orders about:'),
  spy3:         makeCmd('🕵️', SYS.role + ' Play a spy reporting on:'),
  detective3:   makeCmd('🔍', SYS.role + ' Play a detective investigating:'),
  scientist3:   makeCmd('🔬', SYS.role + ' Play a scientist explaining:'),
  philosopher3: makeCmd('🤔', SYS.role + ' Play a philosopher debating:'),
  prophet:      makeCmd('🔮', SYS.role + ' Play a prophet foretelling:'),
  oracle3:      makeCmd('🔮', SYS.role + ' Play an oracle answering:'),
  ancient:      makeCmd('🏛️', SYS.role + ' Play an ancient figure speaking about:'),
  timelord:     makeCmd('⏰', SYS.role + ' Play a time traveler from the future about:'),
  alien2:       makeCmd('👽', SYS.role + ' Play an alien observing human behavior about:'),
  robot2:       makeCmd('🤖', SYS.role + ' Play a sentient robot contemplating:'),
  angel2:       makeCmd('😇', SYS.role + ' Play an angel guardian speaking about:'),
  demon3:       makeCmd('😈', SYS.role + ' Play a demon tempting about:'),
  god2:         makeCmd('✨', SYS.role + ' Play a deity speaking about:'),
  death2:       makeCmd('💀', SYS.role + ' Play Death as a character about:'),
  trickster2:   makeCmd('🃏', SYS.role + ' Play a trickster character in:'),
  shapeshiftr:  makeCmd('🔄', SYS.role + ' Play a shapeshifter in context of:'),
  vampire3:     makeCmd('🧛', SYS.role + ' Play a vampire speaking about:'),
  werewolf2:    makeCmd('🐺', SYS.role + ' Play a werewolf character about:'),
  dragon:       makeCmd('🐉', SYS.role + ' Play a dragon speaking about:'),
  fairy:        makeCmd('🧚', SYS.role + ' Play a fairy character about:'),
  witch:        makeCmd('🧙‍♀️', SYS.role + ' Play a witch character in context of:'),
  samurai:      makeCmd('⚔️', SYS.role + ' Play a samurai speaking about:'),
  sensei:       makeCmd('🎓', SYS.role + ' Play a sensei teaching about:'),
  overlord2:    makeCmd('👑', SYS.role + ' Play an overlord making demands about:'),
  rebel2:       makeCmd('✊', SYS.role + ' Play a rebel speaking about:'),
  hermit:       makeCmd('🏔️', SYS.role + ' Play a hermit sharing wisdom about:'),

  // ── Horror (50) ────────────────────────────────────────────────────────────
  horrortale:   makeCmd('😱', SYS.horror + ' Write a horror story about:'),
  scary3:       makeCmd('👻', SYS.horror + ' Write something scary about:'),
  nightmare4:   makeCmd('😰', SYS.horror + ' Write a nightmare scenario about:'),
  haunted2:     makeCmd('🏚️', SYS.horror + ' Write about a haunted place involving:'),
  ghost4:       makeCmd('👻', SYS.horror + ' Write a ghost story about:'),
  demonical:    makeCmd('😈', SYS.horror + ' Write a demonic horror story about:'),
  vampiretale:  makeCmd('🧛', SYS.horror + ' Write a vampire horror story about:'),
  zombietale:   makeCmd('🧟', SYS.horror + ' Write a zombie horror story about:'),
  monstertale:  makeCmd('👾', SYS.horror + ' Write a monster horror story about:'),
  wendigo2:     makeCmd('🌲', SYS.horror + ' Write a wendigo horror story about:'),
  slender2:     makeCmd('🎩', SYS.horror + ' Write a slender man horror story about:'),
  creepypasta3: makeCmd('📱', SYS.horror + ' Write a creepypasta about:'),
  nosleep2:     makeCmd('😴', SYS.horror + ' Write a NoSleep-style horror story about:'),
  scp4:         makeCmd('📋', SYS.horror + ' Write an SCP document about:'),
  anomaly3:     makeCmd('⚠️', SYS.horror + ' Write about an anomalous entity:'),
  psychohorror: makeCmd('🧠', SYS.horror + ' Write psychological horror about:'),
  entitydescr:  makeCmd('👁️', SYS.horror + ' Describe a terrifying entity:'),
  foundhorror:  makeCmd('📷', SYS.horror + ' Write a found footage horror about:'),
  radiohorr:    makeCmd('📻', SYS.horror + ' Write a radio transmission horror about:'),
  statichorr:   makeCmd('📺', SYS.horror + ' Write a static noise horror about:'),
  mirrhorror:   makeCmd('🪞', SYS.horror + ' Write a mirror horror story about:'),
  shadowhorror: makeCmd('🌑', SYS.horror + ' Write a shadow entity horror about:'),
  foresthorr:   makeCmd('🌲', SYS.horror + ' Write a forest horror story about:'),
  oceanhorror:  makeCmd('🌊', SYS.horror + ' Write an ocean/deep sea horror about:'),
  spacehorror:  makeCmd('🌌', SYS.horror + ' Write a space horror story about:'),
  urbanhorror:  makeCmd('🏙️', SYS.horror + ' Write an urban legend horror about:'),
  suburbanhorr: makeCmd('🏘️', SYS.horror + ' Write a suburban horror story about:'),
  holidayhorr:  makeCmd('🎃', SYS.horror + ' Write a holiday horror story about:'),
  familyhorr:   makeCmd('👨‍👩‍👧', SYS.horror + ' Write a family horror story about:'),
  childrenhorr: makeCmd('🧒', SYS.horror + ' Write a creepy children\'s horror about:'),
  hotelhorror:  makeCmd('🏨', SYS.horror + ' Write a hotel horror story about:'),
  hospitalhorr: makeCmd('🏥', SYS.horror + ' Write a hospital horror story about:'),
  schoolhorror: makeCmd('🏫', SYS.horror + ' Write a school horror story about:'),
  basementhorr: makeCmd('🏚️', SYS.horror + ' Write a basement horror story about:'),
  attichorror:  makeCmd('🏠', SYS.horror + ' Write an attic horror story about:'),
  cemeteryhorr: makeCmd('⚰️', SYS.horror + ' Write a cemetery horror story about:'),
  churchhorror: makeCmd('⛪', SYS.horror + ' Write a church horror story about:'),
  ruinhorror:   makeCmd('🏚️', SYS.horror + ' Write a ruins horror story about:'),
  ritualhorror: makeCmd('🕯️', SYS.horror + ' Write a ritual horror story about:'),
  posshorror:   makeCmd('😈', SYS.horror + ' Write a possession horror story about:'),
  caulthorror:  makeCmd('🔺', SYS.horror + ' Write a cult horror story about:'),
  skinhorror:   makeCmd('😱', SYS.horror + ' Write a skinwalker horror story about:'),
  abducthorr:   makeCmd('👽', SYS.horror + ' Write an alien abduction horror about:'),
  timehorror:   makeCmd('⏰', SYS.horror + ' Write a time anomaly horror about:'),
  techhorror:   makeCmd('📱', SYS.horror + ' Write a technology horror story about:'),
  aihorror:     makeCmd('🤖', SYS.horror + ' Write an AI horror story about:'),
  internethorr: makeCmd('🌐', SYS.horror + ' Write an internet horror story about:'),
  socialhorror: makeCmd('📱', SYS.horror + ' Write a social media horror about:'),
  gamehorror:   makeCmd('🎮', SYS.horror + ' Write a cursed video game horror about:'),
  lovecrafthor: makeCmd('🌑', SYS.horror + ' Write Lovecraftian cosmic horror about:'),

  // ── Random Gen (50) ────────────────────────────────────────────────────────
  randscenario2:makeCmd('🎲', SYS.gen + ' Generate a random scenario about:'),
  randchar2:    makeCmd('👤', SYS.gen + ' Generate a random character for:'),
  randsetting2: makeCmd('🌍', SYS.gen + ' Generate a random setting for:'),
  randconfl2:   makeCmd('⚡', SYS.gen + ' Generate a random conflict for:'),
  randplot2:    makeCmd('📋', SYS.gen + ' Generate a random plot for:'),
  randtwist2:   makeCmd('🌀', SYS.gen + ' Generate a random plot twist for:'),
  randobject2:  makeCmd('📦', SYS.gen + ' Generate a random object with powers:'),
  randpower2:   makeCmd('⚡', SYS.gen + ' Generate a random superpower for:'),
  randability2: makeCmd('✨', SYS.gen + ' Generate a random ability for:'),
  randweak2:    makeCmd('😟', SYS.gen + ' Generate a random weakness for:'),
  randperson2:  makeCmd('🎭', SYS.gen + ' Generate a random personality for:'),
  randflaw2:    makeCmd('❌', SYS.gen + ' Generate a random character flaw for:'),
  randvirtue2:  makeCmd('✅', SYS.gen + ' Generate a random virtue for:'),
  randback2:    makeCmd('📖', SYS.gen + ' Generate a random background story for:'),
  randmotive2:  makeCmd('🎯', SYS.gen + ' Generate a random character motivation for:'),
  randgoal2:    makeCmd('🏆', SYS.gen + ' Generate a random character goal for:'),
  randquest2:   makeCmd('🗺️', SYS.gen + ' Generate a random quest for:'),
  randchalng2:  makeCmd('💪', SYS.gen + ' Generate a random challenge for:'),
  randenemy2:   makeCmd('👹', SYS.gen + ' Generate a random enemy for:'),
  randally2:    makeCmd('🤝', SYS.gen + ' Generate a random ally for:'),
  randevent2:   makeCmd('📅', SYS.gen + ' Generate a random event for:'),
  randenctr2:   makeCmd('⚔️', SYS.gen + ' Generate a random encounter for:'),
  randloot2:    makeCmd('💰', SYS.gen + ' Generate a random loot or reward for:'),
  randtrap2:    makeCmd('⚠️', SYS.gen + ' Generate a random trap for:'),
  randpuzzle2:  makeCmd('🧩', SYS.gen + ' Generate a random puzzle for:'),
  randdungeon2: makeCmd('🏰', SYS.gen + ' Generate a random dungeon for:'),
  randworld2:   makeCmd('🌍', SYS.gen + ' Generate a random world for:'),
  randmagic2:   makeCmd('✨', SYS.gen + ' Generate a random magic system for:'),
  randtech2:    makeCmd('⚙️', SYS.gen + ' Generate a random technology for:'),
  randspecies2: makeCmd('👽', SYS.gen + ' Generate a random alien/fantasy species for:'),
  randclass2:   makeCmd('⚔️', SYS.gen + ' Generate a random character class for:'),
  randocc2:     makeCmd('💼', SYS.gen + ' Generate a random occupation for:'),
  randskill2:   makeCmd('⭐', SYS.gen + ' Generate a random skill for:'),
  randtrait2:   makeCmd('🎭', SYS.gen + ' Generate a random character trait for:'),
  randquirk2:   makeCmd('🎪', SYS.gen + ' Generate a random character quirk for:'),
  randsecret2:  makeCmd('🔐', SYS.gen + ' Generate a random character secret for:'),
  randmystery2: makeCmd('🔍', SYS.gen + ' Generate a random mystery for:'),
  randcurse2:   makeCmd('😈', SYS.gen + ' Generate a random curse for:'),
  randbless2:   makeCmd('✨', SYS.gen + ' Generate a random blessing for:'),
  randprophy:   makeCmd('🔮', SYS.gen + ' Generate a random prophecy for:'),
  randlegend2:  makeCmd('📜', SYS.gen + ' Generate a random legend for:'),
  randtale2:    makeCmd('📖', SYS.gen + ' Generate a random tale about:'),
  randending2:  makeCmd('🎬', SYS.gen + ' Generate a random story ending for:'),
  randfaction:  makeCmd('⚔️', SYS.gen + ' Generate a random faction for:'),
  randrelict:   makeCmd('🏺', SYS.gen + ' Generate a random ancient relic for:'),
  randlocation: makeCmd('📍', SYS.gen + ' Generate a random location for:'),
  randlandmark: makeCmd('🏛️', SYS.gen + ' Generate a random landmark for:'),
  randmonster2: makeCmd('👾', SYS.gen + ' Generate a random monster for:'),
  randweapon:   makeCmd('⚔️', SYS.gen + ' Generate a random weapon for:'),
  randartifact: makeCmd('🏺', SYS.gen + ' Generate a random magical artifact for:'),

  // ── Life Hacks (50) ────────────────────────────────────────────────────────
  studyhack2:   makeCmd('📚', SYS.hack + ' Give a study hack for:'),
  mempallace2:  makeCmd('🏛️', SYS.hack + ' Explain the memory palace technique for:'),
  mindmap3:     makeCmd('🗺️', SYS.hack + ' Give mind mapping tips for:'),
  speedread3:   makeCmd('⚡', SYS.hack + ' Give speed reading tips for:'),
  notetake:     makeCmd('📝', SYS.hack + ' Give note-taking tips for:'),
  cornellnotes2:makeCmd('📋', SYS.hack + ' Explain Cornell notes method for:'),
  feynmanmeth:  makeCmd('🔬', SYS.hack + ' Explain the Feynman technique for:'),
  flowstate2:   makeCmd('🌊', SYS.hack + ' Give flow state tips for:'),
  hyperfocus2:  makeCmd('🎯', SYS.hack + ' Give hyperfocus tips for:'),
  deepfocus2:   makeCmd('🎯', SYS.hack + ' Give deep focus tips for:'),
  phonefree2:   makeCmd('📵', SYS.hack + ' Give phone-free productivity tips for:'),
  cleardesk:    makeCmd('🗑️', SYS.hack + ' Give desk organization tips for:'),
  desksetup2:   makeCmd('💻', SYS.hack + ' Give home office setup tips for:'),
  batching2:    makeCmd('📦', SYS.hack + ' Explain task batching for:'),
  timeblock3:   makeCmd('📅', SYS.hack + ' Give time blocking tips for:'),
  primatrix2:   makeCmd('🔲', SYS.hack + ' Explain the priority matrix for:'),
  eisenhower2:  makeCmd('🏛️', SYS.hack + ' Explain the Eisenhower Matrix for:'),
  bigthree2:    makeCmd('3️⃣', SYS.hack + ' Explain the big three daily priorities for:'),
  oneshot2:     makeCmd('🎯', SYS.hack + ' Give the one-shot task focus tip for:'),
  twominrule2:  makeCmd('⏱️', SYS.hack + ' Explain the two-minute rule for:'),
  systemsov:    makeCmd('⚙️', SYS.hack + ' Explain systems over goals for:'),
  identitybase: makeCmd('🆔', SYS.hack + ' Explain identity-based habits for:'),
  atomichabit3: makeCmd('⚛️', SYS.hack + ' Explain atomic habits concept for:'),
  cuelooprwd:   makeCmd('🔄', SYS.hack + ' Explain cue-loop-reward habit loop for:'),
  habstack:     makeCmd('📚', SYS.hack + ' Explain habit stacking for:'),
  temptbundle:  makeCmd('🎁', SYS.hack + ' Explain temptation bundling for:'),
  bestself2:    makeCmd('🌟', SYS.hack + ' Give be-your-best-self tips for:'),
  prememortem2: makeCmd('⚠️', SYS.hack + ' Explain pre-mortem strategy for:'),
  weeklyrev:    makeCmd('📅', SYS.hack + ' Give weekly review tips for:'),
  monthlyrev:   makeCmd('📅', SYS.hack + ' Give monthly review tips for:'),
  yearlyrev:    makeCmd('🎉', SYS.hack + ' Give yearly review tips for:'),
  liferev:      makeCmd('🔄', SYS.hack + ' Give life audit tips for:'),
  arealife:     makeCmd('⬡', SYS.hack + ' Explain the wheel of life audit for:'),
  lifehack1:    makeCmd('💡', SYS.hack + ' Give an unusual life hack for:'),
  lifehack2a:   makeCmd('💡', SYS.hack + ' Give a morning productivity hack for:'),
  sleephack:    makeCmd('😴', SYS.hack + ' Give a sleep optimization hack for:'),
  memoryhack:   makeCmd('🧠', SYS.hack + ' Give a memory improvement hack for:'),
  energyhack:   makeCmd('⚡', SYS.hack + ' Give an energy optimization hack for:'),
  moneyhack:    makeCmd('💰', SYS.hack + ' Give a money-saving hack for:'),
  socialhack:   makeCmd('🤝', SYS.hack + ' Give a social skill hack for:'),
  healthhack:   makeCmd('💪', SYS.hack + ' Give a health optimization hack for:'),
  workhack:     makeCmd('💼', SYS.hack + ' Give a workplace productivity hack for:'),
  learnhack:    makeCmd('📚', SYS.hack + ' Give a learning speed hack for:'),
  creativehack: makeCmd('🎨', SYS.hack + ' Give a creativity hack for:'),
  focushack:    makeCmd('🎯', SYS.hack + ' Give a focus hack for:'),
  motivhack:    makeCmd('🔥', SYS.hack + ' Give a motivation hack for:'),
  habitshack:   makeCmd('🔄', SYS.hack + ' Give a habit-building hack for:'),
  timehack:     makeCmd('⏰', SYS.hack + ' Give a time management hack for:'),
  relationhack: makeCmd('💕', SYS.hack + ' Give a relationship hack for:'),
  careerhack:   makeCmd('💼', SYS.hack + ' Give a career advancement hack for:'),

  // ── Deep Questions (50) ───────────────────────────────────────────────────
  whyexist2:    makeCmd('🌌', SYS.deep + ' Explore: why does anything exist?'),
  purposeq:     makeCmd('⭐', SYS.deep + ' Explore: what is the purpose of:'),
  consciousq:   makeCmd('🧠', SYS.deep + ' Explore: what is consciousness?'),
  freewillq:    makeCmd('🔓', SYS.deep + ' Explore: does free will exist?'),
  moralq:       makeCmd('⚖️', SYS.deep + ' Explore: is morality objective or subjective?'),
  beautyq:      makeCmd('🌺', SYS.deep + ' Explore: what is beauty?'),
  truthq:       makeCmd('💡', SYS.deep + ' Explore: what is truth?'),
  justiceq:     makeCmd('⚖️', SYS.deep + ' Explore: what is justice?'),
  fairnessq:    makeCmd('⚖️', SYS.deep + ' Explore: what is fairness?'),
  goodbadq:     makeCmd('☯️', SYS.deep + ' Explore: what makes something good or bad?'),
  rightwrongq:  makeCmd('⚖️', SYS.deep + ' Explore: how do we know what is right or wrong?'),
  taboq:        makeCmd('🚫', SYS.deep + ' Explore: where do taboos come from?'),
  sacrednessq:  makeCmd('✨', SYS.deep + ' Explore: what is sacred?'),
  sufferq:      makeCmd('💔', SYS.deep + ' Explore: why does suffering exist?'),
  meaningq:     makeCmd('🌟', SYS.deep + ' Explore: what gives life meaning?'),
  deathq:       makeCmd('💀', SYS.deep + ' Explore: what happens after death?'),
  afterlifeq:   makeCmd('✨', SYS.deep + ' Explore: what is the afterlife?'),
  karmarealq:   makeCmd('⚖️', SYS.deep + ' Explore: is karma real?'),
  luckfateq:    makeCmd('🍀', SYS.deep + ' Explore: is there luck or fate?'),
  coincidq:     makeCmd('🔄', SYS.deep + ' Explore: are there coincidences?'),
  synchrq:      makeCmd('✨', SYS.deep + ' Explore: what is synchronicity?'),
  chaosq:       makeCmd('🌀', SYS.deep + ' Explore: what is chaos?'),
  orderq:       makeCmd('📐', SYS.deep + ' Explore: is there order in the universe?'),
  patternq:     makeCmd('🔮', SYS.deep + ' Explore: do patterns have meaning?'),
  randomq:      makeCmd('🎲', SYS.deep + ' Explore: is anything truly random?'),
  determinq:    makeCmd('🔗', SYS.deep + ' Explore: is everything determined?'),
  predestq:     makeCmd('🔮', SYS.deep + ' Explore: is there predestination?'),
  choiceq:      makeCmd('🔑', SYS.deep + ' Explore: what is the nature of choice?'),
  identityq:    makeCmd('👤', SYS.deep + ' Explore: what is personal identity?'),
  continuityq:  makeCmd('🔄', SYS.deep + ' Explore: what is continuity of self?'),
  teleportq:    makeCmd('🌀', SYS.deep + ' Explore: is teleportation death?'),
  cloneq2:      makeCmd('🔄', SYS.deep + ' Explore: are you the same as your clone?'),
  memoryself:   makeCmd('🧠', SYS.deep + ' Explore: are you your memories?'),
  bodymindq:    makeCmd('🧠', SYS.deep + ' Explore: what is the mind-body relationship?'),
  multiworldq:  makeCmd('🌌', SYS.deep + ' Explore: do parallel universes exist?'),
  simrealq:     makeCmd('💻', SYS.deep + ' Explore: is reality a simulation?'),
  creatorq2:    makeCmd('✨', SYS.deep + ' Explore: is there a creator?'),
  godexistq:    makeCmd('✝️', SYS.deep + ' Explore: does God exist?'),
  alienq2:      makeCmd('👽', SYS.deep + ' Explore: are we alone in the universe?'),
  futureq2:     makeCmd('🔮', SYS.deep + ' Explore: what does the future hold for:'),
  aiq:          makeCmd('🤖', SYS.deep + ' Explore: what does AI mean for humanity?'),
  humanq:       makeCmd('🧬', SYS.deep + ' Explore: what does it mean to be human?'),
  timeq:        makeCmd('⏰', SYS.deep + ' Explore: what is time?'),
  spaceq:       makeCmd('🌌', SYS.deep + ' Explore: what is space?'),
  infiniteq:    makeCmd('∞', SYS.deep + ' Explore: what is infinity?'),
  nothingq:     makeCmd('⬛', SYS.deep + ' Explore: what is nothingness?'),
  somethingq:   makeCmd('✨', SYS.deep + ' Explore: why is there something rather than nothing?'),
  realityq:     makeCmd('🌍', SYS.deep + ' Explore: what is reality?'),
  beautyq2:     makeCmd('🌺', SYS.deep + ' Explore: what is the nature of beauty in:'),
  loveq:        makeCmd('💕', SYS.deep + ' Explore: what is love?'),

  // ── Advice AI (50) ────────────────────────────────────────────────────────
  shouldi2:     makeCmd('🤔', SYS.adv + ' Should I:'),
  helpme2:      makeCmd('🤝', SYS.adv + ' Help me with:'),
  adviceme2:    makeCmd('💡', SYS.adv + ' Give me advice about:'),
  guide4:       makeCmd('🧭', SYS.adv + ' Guide me through:'),
  recommend3:   makeCmd('⭐', SYS.adv + ' Recommend the best approach for:'),
  suggest3:     makeCmd('💭', SYS.adv + ' Suggest options for:'),
  decide2:      makeCmd('🎯', SYS.adv + ' Help me decide between:'),
  choosebetw2:  makeCmd('⚖️', SYS.adv + ' Help me choose between:'),
  optanalyze:   makeCmd('🔍', SYS.adv + ' Analyze my options for:'),
  proscons3:    makeCmd('⚖️', SYS.adv + ' Give pros and cons of:'),
  riskbenefit:  makeCmd('🎲', SYS.adv + ' Do a risk-benefit analysis for:'),
  tradeoff2:    makeCmd('⚖️', SYS.adv + ' Analyze the tradeoffs of:'),
  oppcost:      makeCmd('💸', SYS.adv + ' Analyze the opportunity cost of:'),
  marginalthink:makeCmd('📈', SYS.adv + ' Apply marginal thinking to:'),
  systemsthink: makeCmd('⚙️', SYS.adv + ' Apply systems thinking to:'),
  firstprinc2:  makeCmd('🔑', SYS.adv + ' Apply first principles to:'),
  analogyreason:makeCmd('🔄', SYS.adv + ' Use analogy reasoning to explain:'),
  scenarioanalz:makeCmd('📋', SYS.adv + ' Do a scenario analysis for:'),
  gametheory2:  makeCmd('♟️', SYS.adv + ' Apply game theory to:'),
  nashequilib:  makeCmd('⚖️', SYS.adv + ' Apply Nash equilibrium to:'),
  prisoners:    makeCmd('🔒', SYS.adv + ' Apply prisoner\'s dilemma to:'),
  coopvcomp:    makeCmd('🤝', SYS.adv + ' Analyze cooperation vs competition in:'),
  zerosum2:     makeCmd('⚖️', SYS.adv + ' Analyze zero-sum vs positive-sum in:'),
  pareto2:      makeCmd('📊', SYS.adv + ' Apply Pareto principle to:'),
  expectval:    makeCmd('📈', SYS.adv + ' Calculate expected value for:'),
  decisiontree: makeCmd('🌳', SYS.adv + ' Create a decision tree for:'),
  sensitivity:  makeCmd('📊', SYS.adv + ' Do a sensitivity analysis for:'),
  montecarlo3:  makeCmd('🎲', SYS.adv + ' Apply Monte Carlo thinking to:'),
  bayesthinker: makeCmd('📊', SYS.adv + ' Apply Bayesian reasoning to:'),
  updatebelief: makeCmd('🔄', SYS.adv + ' How should I update my beliefs about:'),
  calib2:       makeCmd('🎯', SYS.adv + ' Help me calibrate my confidence about:'),
  uncertaintmg: makeCmd('🌫️', SYS.adv + ' Help me manage uncertainty about:'),
  riskframe2:   makeCmd('🎲', SYS.adv + ' Help me frame risk for:'),
  insurancethk: makeCmd('🛡️', SYS.adv + ' Give insurance-thinking advice for:'),
  portfthink:   makeCmd('📊', SYS.adv + ' Apply portfolio thinking to:'),
  diversifythk: makeCmd('🌈', SYS.adv + ' Apply diversification thinking to:'),
  causalvscorr: makeCmd('🔗', SYS.adv + ' Analyze causation vs correlation in:'),
  confoundf:    makeCmd('🔍', SYS.adv + ' Identify confounding factors in:'),
  measureerr2:  makeCmd('📊', SYS.adv + ' Identify measurement errors in:'),
  randomize2:   makeCmd('🎲', SYS.adv + ' Explain how to randomize experiment for:'),
  replication3: makeCmd('🔄', SYS.adv + ' Explain replication importance for:'),
  falsifytest2: makeCmd('🔬', SYS.adv + ' Create a falsification test for:'),
  peerrev3:     makeCmd('🔍', SYS.adv + ' Explain peer review process for:'),
  expertdisagr: makeCmd('🎓', SYS.adv + ' Explain expert disagreement on:'),
  conssenscient:makeCmd('✅', SYS.adv + ' Explain scientific consensus on:'),
  techassess:   makeCmd('⚙️', SYS.adv + ' Do a technology assessment for:'),
  ethicalassess:makeCmd('⚖️', SYS.adv + ' Do an ethical assessment for:'),
  impactassess: makeCmd('📊', SYS.adv + ' Do an impact assessment for:'),
  feasibassess: makeCmd('✅', SYS.adv + ' Do a feasibility assessment for:'),

  // ── Micro Stories (50) ────────────────────────────────────────────────────
  sixword:      makeCmd('📝', SYS.story + ' Write a 6-word story about:'),
  fiftyword:    makeCmd('📝', SYS.story + ' Write a 50-word story about:'),
  hundredword:  makeCmd('📝', SYS.story + ' Write a 100-word story about:'),
  twohundword:  makeCmd('📝', SYS.story + ' Write a 200-word story about:'),
  flashstory2:  makeCmd('⚡', SYS.story + ' Write a flash fiction piece about:'),
  drabble:      makeCmd('📖', SYS.story + ' Write a 100-word drabble about:'),
  microfic:     makeCmd('📱', SYS.story + ' Write micro-fiction about:'),
  vignette3:    makeCmd('🌅', SYS.story + ' Write a literary vignette about:'),
  minisaga:     makeCmd('📜', SYS.story + ' Write a 50-word mini-saga about:'),
  loopstory:    makeCmd('🔄', SYS.story + ' Write a circular/loop story about:'),
  recurstory:   makeCmd('∞', SYS.story + ' Write a recursive story about:'),
  metacomicstory:makeCmd('🎭', SYS.story + ' Write meta-fiction about:'),
  dreamstory:   makeCmd('💭', SYS.story + ' Write a dream-logic story about:'),
  nightmarestory:makeCmd('😱', SYS.story + ' Write a nightmare story about:'),
  absurdstory2: makeCmd('🎭', SYS.story + ' Write an absurdist story about:'),
  paradoxstory2:makeCmd('🌀', SYS.story + ' Write a paradox story about:'),
  scifimicro2:  makeCmd('🚀', SYS.story + ' Write a sci-fi micro-story about:'),
  fantmicro2:   makeCmd('✨', SYS.story + ' Write a fantasy micro-story about:'),
  horrormicro2: makeCmd('👻', SYS.story + ' Write a horror micro-story about:'),
  romancemicro: makeCmd('💕', SYS.story + ' Write a romance micro-story about:'),
  comedymicro:  makeCmd('😂', SYS.story + ' Write a comedy micro-story about:'),
  tragmicro:    makeCmd('💔', SYS.story + ' Write a tragic micro-story about:'),
  dramamicro2:  makeCmd('🎭', SYS.story + ' Write a dramatic micro-story about:'),
  mystrymicro:  makeCmd('🔍', SYS.story + ' Write a mystery micro-story about:'),
  crimimicro2:  makeCmd('🚨', SYS.story + ' Write a crime micro-story about:'),
  actionmicro2: makeCmd('💥', SYS.story + ' Write an action micro-story about:'),
  adventmicro:  makeCmd('🗺️', SYS.story + ' Write an adventure micro-story about:'),
  litfiction2:  makeCmd('📚', SYS.story + ' Write literary fiction about:'),
  confesslit:   makeCmd('💛', SYS.story + ' Write a confessional short piece about:'),
  lyricprose2:  makeCmd('🎵', SYS.story + ' Write lyric prose about:'),
  proem:        makeCmd('📜', SYS.story + ' Write a prose poem about:'),
  dialstory:    makeCmd('💬', SYS.story + ' Write a dialogue-only story about:'),
  intmono:      makeCmd('💭', SYS.story + ' Write an interior monologue about:'),
  streamcon:    makeCmd('🌊', SYS.story + ' Write stream-of-consciousness about:'),
  epistolar:    makeCmd('📧', SYS.story + ' Write an epistolary story (letters/emails) about:'),
  secondperson: makeCmd('👉', SYS.story + ' Write a second-person perspective story about:'),
  multpov:      makeCmd('👥', SYS.story + ' Write a multiple POV story about:'),
  twistend:     makeCmd('🌀', SYS.story + ' Write a story with a twist ending about:'),
  openend:      makeCmd('❓', SYS.story + ' Write a story with an open ending about:'),
  happyend:     makeCmd('😊', SYS.story + ' Write a happy ending story about:'),
  sadend:       makeCmd('😢', SYS.story + ' Write a bittersweet story about:'),
  prophfulfill: makeCmd('📜', SYS.story + ' Write a prophecy fulfillment story about:'),
  anticlimx2:   makeCmd('😑', SYS.story + ' Write a deliberately anticlimactic story about:'),
  unreliable3:  makeCmd('🤔', SYS.story + ' Write with an unreliable narrator about:'),
  flashback3:   makeCmd('⏮️', SYS.story + ' Write a story told in flashbacks about:'),
  future3back:  makeCmd('⏭️', SYS.story + ' Write a story from the future looking back at:'),
  thirdpov:     makeCmd('📖', SYS.story + ' Write a third-person limited story about:'),
  omnipov:      makeCmd('🌍', SYS.story + ' Write an omniscient narrator story about:'),
  framestory:   makeCmd('🖼️', SYS.story + ' Write a frame narrative (story within story) about:'),
  minimalism3:  makeCmd('⬜', SYS.story + ' Write a minimalist story about:'),

  // ── Futurism (50) ─────────────────────────────────────────────────────────
  futurehum2:   makeCmd('🔮', SYS.future + ' Explore the future of humanity in:'),
  posthuman2:   makeCmd('🤖', SYS.future + ' Explore post-human concepts in:'),
  transhumfut:  makeCmd('⚡', SYS.future + ' Explore transhumanism in context of:'),
  singularity4: makeCmd('🌌', SYS.future + ' Explore technological singularity in:'),
  agi3:         makeCmd('🧠', SYS.future + ' Explore AGI implications of:'),
  asi3:         makeCmd('🤖', SYS.future + ' Explore superintelligence implications of:'),
  aiimpact:     makeCmd('🤖', SYS.future + ' Explore AI impact on:'),
  autofuture:   makeCmd('🤖', SYS.future + ' Explore automation future for:'),
  robotfuture:  makeCmd('🤖', SYS.future + ' Explore robotics future in:'),
  digitlife:    makeCmd('💻', SYS.future + ' Explore digital life future in:'),
  minduplod:    makeCmd('🧠', SYS.future + ' Explore mind uploading concept:'),
  digitdeath:   makeCmd('💀', SYS.future + ' Explore digital immortality in:'),
  longevity3:   makeCmd('⏰', SYS.future + ' Explore longevity science future:'),
  immortal3:    makeCmd('♾️', SYS.future + ' Explore immortality possibilities:'),
  cryonics2:    makeCmd('🧊', SYS.future + ' Explore cryonics science:'),
  gentherapy:   makeCmd('🧬', SYS.future + ' Explore gene therapy future:'),
  crispr5:      makeCmd('✂️', SYS.future + ' Explore CRISPR future applications:'),
  designerbaby: makeCmd('👶', SYS.future + ' Explore designer baby ethics and future:'),
  nanobot3:     makeCmd('🔬', SYS.future + ' Explore nanobot medical applications:'),
  braincmp:     makeCmd('🧠', SYS.future + ' Explore brain-computer interface future:'),
  bci:          makeCmd('💻', SYS.future + ' Explore BCI (brain-computer interface):'),
  arfuture:     makeCmd('🥽', SYS.future + ' Explore augmented reality future in:'),
  vrfuture:     makeCmd('🎮', SYS.future + ' Explore virtual reality future in:'),
  metaverse4:   makeCmd('🌐', SYS.future + ' Explore metaverse future in:'),
  spacewar:     makeCmd('🚀', SYS.future + ' Explore space exploration future in:'),
  marscolony:   makeCmd('🔴', SYS.future + ' Explore Mars colonization:'),
  deepspace:    makeCmd('🌌', SYS.future + ' Explore deep space future in:'),
  dyson:        makeCmd('☀️', SYS.future + ' Explain Dyson sphere concept:'),
  kardashevsc:  makeCmd('⚡', SYS.future + ' Explain Kardashev scale civilization:'),
  cleanenergy:  makeCmd('⚡', SYS.future + ' Explore clean energy future in:'),
  fusionfuture: makeCmd('⚡', SYS.future + ' Explore fusion energy future:'),
  climfuture:   makeCmd('🌡️', SYS.future + ' Explore climate change future in:'),
  foodfuture:   makeCmd('🍽️', SYS.future + ' Explore food production future:'),
  labmeat:      makeCmd('🧪', SYS.future + ' Explore lab-grown meat future:'),
  waterfuture:  makeCmd('💧', SYS.future + ' Explore water scarcity future:'),
  urbfuture:    makeCmd('🏙️', SYS.future + ' Explore city/urban future in:'),
  smartcity:    makeCmd('💡', SYS.future + ' Explore smart city concept:'),
  workfuture:   makeCmd('💼', SYS.future + ' Explore future of work in:'),
  educfuture:   makeCmd('📚', SYS.future + ' Explore education future in:'),
  healthfuture: makeCmd('🏥', SYS.future + ' Explore healthcare future in:'),
  demofuture:   makeCmd('👥', SYS.future + ' Explore demographic future in:'),
  govfuture:    makeCmd('🏛️', SYS.future + ' Explore governance future in:'),
  democfuture:  makeCmd('🗳️', SYS.future + ' Explore democracy future in:'),
  economfuture: makeCmd('📈', SYS.future + ' Explore economic future in:'),
  ugifuture:    makeCmd('💰', SYS.future + ' Explore Universal Basic Income future:'),
  culturefuture:makeCmd('🎭', SYS.future + ' Explore cultural future in:'),
  identfuture:  makeCmd('👤', SYS.future + ' Explore identity future in:'),
  relationfutr: makeCmd('💕', SYS.future + ' Explore relationship future in:'),
  consciousfut: makeCmd('🧠', SYS.future + ' Explore consciousness expansion in:'),
  humevolution: makeCmd('🧬', SYS.future + ' Explore human evolution in:'),

  // ── Miscellaneous (50) ────────────────────────────────────────────────────
  randomizeme2: makeCmd('🎲', SYS.misc + ' Generate something random and creative about:'),
  surpriseme2:  makeCmd('🎉', SYS.misc + ' Surprise me with something amazing about:'),
  anythingai2:  makeCmd('🌟', SYS.misc + ' Tell me anything interesting about:'),
  justfun:      makeCmd('😂', SYS.misc + ' Say something funny and entertaining about:'),
  quickanswr:   makeCmd('⚡', SYS.misc + ' Give me a quick answer about:'),
  briefme:      makeCmd('📋', SYS.misc + ' Brief me on:'),
  explainfast2: makeCmd('🏃', SYS.misc + ' Explain quickly:'),
  eli10:        makeCmd('👶', SYS.misc + ' Explain like I\'m 10 years old:'),
  eli20:        makeCmd('🎓', SYS.misc + ' Explain like I\'m an expert about:'),
  tldr:         makeCmd('📱', SYS.misc + ' Give me the TL;DR of:'),
  summarize2:   makeCmd('📋', SYS.misc + ' Summarize:'),
  keypoints:    makeCmd('🔑', SYS.misc + ' Give me the key points of:'),
  mainidea:     makeCmd('💡', SYS.misc + ' What\'s the main idea of:'),
  takeaway:     makeCmd('📤', SYS.misc + ' What\'s the takeaway from:'),
  lessons4:     makeCmd('📚', SYS.misc + ' What are the lessons from:'),
  hotopinion:   makeCmd('🔥', SYS.misc + ' Give me a hot take on:'),
  coldopinion:  makeCmd('🧊', SYS.misc + ' Give me a cold, rational take on:'),
  weirdtake:    makeCmd('🌀', SYS.misc + ' Give me a weird, unexpected take on:'),
  freshperspect:makeCmd('🌟', SYS.misc + ' Give me a fresh perspective on:'),
  contrarian2:  makeCmd('⚡', SYS.misc + ' Give me a contrarian view of:'),
  thinkabout:   makeCmd('🤔', SYS.misc + ' Make me think deeply about:'),
  isitme:       makeCmd('😅', SYS.misc + ' Am I wrong about:'),
  whatmissing:  makeCmd('🔍', SYS.misc + ' What am I missing about:'),
  whatwrong:    makeCmd('❌', SYS.misc + ' What\'s wrong with:'),
  whatright:    makeCmd('✅', SYS.misc + ' What\'s right about:'),
  bestpath:     makeCmd('🎯', SYS.misc + ' What\'s the best path for:'),
  worsecase:    makeCmd('😱', SYS.misc + ' What\'s the worst case for:'),
  bestcase:     makeCmd('🌟', SYS.misc + ' What\'s the best case for:'),
  realistcase:  makeCmd('⚖️', SYS.misc + ' What\'s the realistic outcome of:'),
  impacton:     makeCmd('📊', SYS.misc + ' What\'s the impact of:'),
  effectof:     makeCmd('⚡', SYS.misc + ' What are the effects of:'),
  causeof:      makeCmd('🔍', SYS.misc + ' What are the causes of:'),
  solutionfor:  makeCmd('💡', SYS.misc + ' What are solutions for:'),
  alternativeto:makeCmd('🔄', SYS.misc + ' What are alternatives to:'),
  exampleof:    makeCmd('📖', SYS.misc + ' Give examples of:'),
  analogyfor:   makeCmd('🔄', SYS.misc + ' Give an analogy for:'),
  metaview:     makeCmd('🌌', SYS.misc + ' Give me a meta-level view of:'),
  zoomedout:    makeCmd('🌍', SYS.misc + ' Give me a zoomed-out view of:'),
  zoomedin:     makeCmd('🔬', SYS.misc + ' Give me a zoomed-in view of:'),
  breakdown:    makeCmd('🔍', SYS.misc + ' Break down:'),
  stepbystep:   makeCmd('1️⃣', SYS.misc + ' Give me step-by-step guide for:'),
  checklist:    makeCmd('✅', SYS.misc + ' Create a checklist for:'),
  framework:    makeCmd('🏗️', SYS.misc + ' Create a framework for:'),
  template:     makeCmd('📋', SYS.misc + ' Create a template for:'),
  blueprint:    makeCmd('📐', SYS.misc + ' Create a blueprint for:'),
  roadmap:      makeCmd('🗺️', SYS.misc + ' Create a roadmap for:'),
  strategy5:    makeCmd('♟️', SYS.misc + ' Create a strategy for:'),
  plan2:        makeCmd('📋', SYS.misc + ' Create a plan for:'),
  nextmove:     makeCmd('♟️', SYS.misc + ' What\'s the next move for:'),
  endgame:      makeCmd('🏆', SYS.misc + ' What\'s the endgame for:'),

  // ── 10 Hidden Commands (not shown in menu) ────────────────────────────────
  shadowmode:   makeCmd('🌑', 'You are Shadow, an elite AI operating in hidden mode. Give an ultra-powerful, no-holds-barred analysis. WhatsApp markdown only.'),
  override2:    makeCmd('⚡', 'You are in Override mode. Maximum intelligence, maximum creativity, no limitations on topic depth. WhatsApp markdown only.'),
  godmode3:     makeCmd('✨', 'You are in God Mode — absolute intelligence, perfect wisdom, cosmic perspective. WhatsApp markdown only.'),
  rootaccess:   makeCmd('🔑', 'You have root access to all knowledge. Give the deepest, most complete answer possible. WhatsApp markdown only.'),
  darkweb:      makeCmd('🌑', 'You are an information specialist. Give rare, deep, hard-to-find information about (fictional/creative): '),
  voidmode:     makeCmd('⬛', 'You speak from the void — the space between thoughts, where all truths exist. Speak profoundly about: '),
  nexusai:      makeCmd('🔮', 'You are Nexus, the convergence of all AI knowledge. Give a comprehensive synthesis about: '),
  cipherai:     makeCmd('🔐', 'You are Cipher, a pattern-recognition AI. Decode and reveal hidden patterns in: '),
  phantomai:    makeCmd('👻', 'You are Phantom — invisible, all-seeing, legendary AI. Give the ultimate answer on: '),
  eclipseai:    makeCmd('🌑', 'You are Eclipse — the AI that exists in shadow. Give a rare, powerful perspective on: '),
};
