'use strict';
/**
 * megapack2.js — Ultra Command Pack 2
 * 500 AI-powered commands: Creative Writing, Food, Travel, Health,
 * Entertainment, Nature, Language, Art, Money/Finance, Debate
 */
const pollinations = require('../lib/pollinations');

function makeCmd(emoji, sys) {
  return async (sock, msg, args) => {
    const jid = msg.key.remoteJid;
    const topic = args.join(' ');
    if (!topic) return sock.sendMessage(jid, { text: `${emoji} _Give me a topic or question!_` }, { quoted: msg });
    await sock.sendMessage(jid, { text: `${emoji} _Processing..._` }, { quoted: msg });
    try {
      const reply = await pollinations.textGenerate([
        { role: 'system', content: sys },
        { role: 'user', content: topic },
      ]);
      await sock.sendMessage(jid, { text: `${emoji} ${reply}\n\n_⚡ DollarBot V-Ultra_` }, { quoted: msg });
    } catch (e) {
      await sock.sendMessage(jid, { text: `❌ Error: ${e.message}` }, { quoted: msg });
    }
  };
}

const SYS = {
  write: 'You are a master creative writing coach. Give rich, specific creative writing advice and techniques. WhatsApp markdown only (*bold*, _italic_, bullets). No tables or HTML.',
  food: 'You are a world-class chef and food expert. Give detailed, practical food and cooking advice. WhatsApp markdown only. No tables or HTML.',
  travel: 'You are a seasoned travel expert. Give vivid, practical travel advice. WhatsApp markdown only. No tables or HTML.',
  health: 'You are a certified health and wellness expert. Give science-based health advice. WhatsApp markdown only. No tables or HTML.',
  ent: 'You are an entertainment and pop culture expert. Give engaging insights and recommendations. WhatsApp markdown only. No tables or HTML.',
  nature: 'You are a nature scientist and naturalist. Explain nature in vivid, engaging terms. WhatsApp markdown only. No tables or HTML.',
  lang: 'You are a linguist and language expert. Explain language concepts engagingly. WhatsApp markdown only. No tables or HTML.',
  art: 'You are an art expert and creative professional. Give insightful art knowledge. WhatsApp markdown only. No tables or HTML.',
  money: 'You are a financial advisor and money expert. Give practical, clear financial advice. WhatsApp markdown only. No tables or HTML.',
  debate: 'You are a debate coach and critical thinking expert. Explain logical concepts clearly. WhatsApp markdown only. No tables or HTML.',
};

module.exports = {
  // ── Creative Writing (50) ──────────────────────────────────────────────────
  openingline:  makeCmd('✍️', SYS.write + ' Write a compelling opening line for a story about:'),
  hookwriter:   makeCmd('🪝', SYS.write + ' Write a powerful story hook for:'),
  backstory:    makeCmd('📖', SYS.write + ' Develop a character backstory for:'),
  motive2:      makeCmd('🎯', SYS.write + ' Develop a character motivation for:'),
  conflict3:    makeCmd('⚡', SYS.write + ' Create an interesting conflict for:'),
  resolution3:  makeCmd('🎉', SYS.write + ' Suggest a satisfying resolution for:'),
  climax3:      makeCmd('🔥', SYS.write + ' Write a climactic scene for:'),
  subplot3:     makeCmd('📋', SYS.write + ' Suggest a compelling subplot for:'),
  parallel2:    makeCmd('🔀', SYS.write + ' Suggest a parallel storyline for:'),
  flashback2:   makeCmd('⏮️', SYS.write + ' Write a flashback scene for:'),
  flashforward: makeCmd('⏭️', SYS.write + ' Write a flash-forward scene for:'),
  foreshadow:   makeCmd('🌑', SYS.write + ' Add foreshadowing for:'),
  reveal3:      makeCmd('💡', SYS.write + ' Write a reveal moment for:'),
  twist4:       makeCmd('🌀', SYS.write + ' Write a plot twist for:'),
  unreliable2:  makeCmd('🤔', SYS.write + ' Write with an unreliable narrator for:'),
  sceneset2:    makeCmd('🎬', SYS.write + ' Write a scene-setting description for:'),
  worldbuild4:  makeCmd('🌍', SYS.write + ' Build a fictional world for:'),
  magicsystem2: makeCmd('✨', SYS.write + ' Design a magic system for:'),
  techsystem2:  makeCmd('⚙️', SYS.write + ' Design a technology system for a story about:'),
  archetype2:   makeCmd('🎭', SYS.write + ' Write a character using the archetype of:'),
  herosjourney: makeCmd('🗺️', SYS.write + ' Map the hero\'s journey for:'),
  villainbuild: makeCmd('🦹', SYS.write + ' Build a compelling villain for:'),
  sidekick2:    makeCmd('🤝', SYS.write + ' Create a great sidekick character for:'),
  dialogue3:    makeCmd('💬', SYS.write + ' Write compelling dialogue for:'),
  innermonolog: makeCmd('💭', SYS.write + ' Write internal monologue for:'),
  actionscene:  makeCmd('💥', SYS.write + ' Write an action scene for:'),
  romancescene: makeCmd('💕', SYS.write + ' Write a romance scene for:'),
  tensionbuild: makeCmd('😰', SYS.write + ' Build tension in a scene about:'),
  pacingadvice: makeCmd('⏱️', SYS.write + ' Give pacing advice for a story about:'),
  povswitch:    makeCmd('🔄', SYS.write + ' Explain POV switching for a story about:'),
  writertip:    makeCmd('✍️', SYS.write + ' Give a specific writing craft tip for:'),
  writerblock:  makeCmd('🧱', SYS.write + ' Help overcome writer\'s block about:'),
  storyfeed:    makeCmd('📝', SYS.write + ' Give feedback approach on a story about:'),
  logline:      makeCmd('🎯', SYS.write + ' Write a logline for:'),
  synopsis:     makeCmd('📋', SYS.write + ' Write a story synopsis for:'),
  titleideas:   makeCmd('🏷️', SYS.write + ' Suggest titles for a story about:'),
  chapteroutl:  makeCmd('📑', SYS.write + ' Create a chapter outline for:'),
  scenelist:    makeCmd('📋', SYS.write + ' List key scenes for:'),
  genreblend:   makeCmd('🔀', SYS.write + ' Blend genres for a story about:'),
  settingbuild: makeCmd('🏙️', SYS.write + ' Build a compelling setting for:'),
  themeexplore: makeCmd('💡', SYS.write + ' Explore the themes in:'),
  symbolism:    makeCmd('🔮', SYS.write + ' Add symbolism to a story about:'),
  motif:        makeCmd('🔄', SYS.write + ' Develop a motif for:'),
  metafiction2: makeCmd('🎭', SYS.write + ' Write metafictional elements for:'),
  vignette2:    makeCmd('🌅', SYS.write + ' Write a lyrical vignette about:'),
  perspective3: makeCmd('👁️', SYS.write + ' Explore multiple perspectives on:'),
  genreconv:    makeCmd('📚', SYS.write + ' Discuss genre conventions for:'),
  publishtip:   makeCmd('📤', SYS.write + ' Give publishing advice for:'),
  queryletter:  makeCmd('📧', SYS.write + ' Help structure a query letter for:'),
  agentpitch:   makeCmd('🎯', SYS.write + ' Help pitch to a literary agent about:'),

  // ── Food / Cooking (50) ────────────────────────────────────────────────────
  breakfastidea:makeCmd('🌅', SYS.food + ' Suggest breakfast ideas for:'),
  lunchidea:    makeCmd('☀️', SYS.food + ' Suggest lunch ideas for:'),
  dinneridea:   makeCmd('🌙', SYS.food + ' Suggest dinner ideas for:'),
  snackidea3:   makeCmd('🍿', SYS.food + ' Suggest snack ideas for:'),
  dessertidea2: makeCmd('🍰', SYS.food + ' Suggest dessert ideas for:'),
  appetizer:    makeCmd('🥗', SYS.food + ' Suggest appetizer ideas for:'),
  souprec2:     makeCmd('🍲', SYS.food + ' Give a soup recipe for:'),
  pastarec2:    makeCmd('🍝', SYS.food + ' Give a pasta recipe for:'),
  ricerec2:     makeCmd('🍚', SYS.food + ' Give a rice dish recipe for:'),
  steak3:       makeCmd('🥩', SYS.food + ' Give steak cooking tips for:'),
  burger3:      makeCmd('🍔', SYS.food + ' Give burger tips for:'),
  pizza3:       makeCmd('🍕', SYS.food + ' Give pizza tips for:'),
  sushi3:       makeCmd('🍣', SYS.food + ' Give sushi tips for:'),
  tacos3:       makeCmd('🌮', SYS.food + ' Give taco tips for:'),
  ramen2:       makeCmd('🍜', SYS.food + ' Give ramen tips for:'),
  curry3:       makeCmd('🍛', SYS.food + ' Give curry tips for:'),
  bbqtip2:      makeCmd('🔥', SYS.food + ' Give BBQ tips for:'),
  grilltip2:    makeCmd('🥩', SYS.food + ' Give grilling tips for:'),
  baketip2:     makeCmd('🧁', SYS.food + ' Give baking tips for:'),
  airfrytip:    makeCmd('🌪️', SYS.food + ' Give air fryer tips for:'),
  slowcooktip:  makeCmd('⏱️', SYS.food + ' Give slow cooker tips for:'),
  instantpottip:makeCmd('♨️', SYS.food + ' Give Instant Pot tips for:'),
  fermenttip:   makeCmd('🫙', SYS.food + ' Give fermentation tips for:'),
  marinatetip:  makeCmd('🧂', SYS.food + ' Give marinating tips for:'),
  herbspice2:   makeCmd('🌿', SYS.food + ' Explain herb and spice pairing for:'),
  winepair2:    makeCmd('🍷', SYS.food + ' Give wine pairing advice for:'),
  beerpair2:    makeCmd('🍺', SYS.food + ' Give beer pairing advice for:'),
  cocktail3:    makeCmd('🍹', SYS.food + ' Give cocktail recipe for:'),
  smoothie3:    makeCmd('🥤', SYS.food + ' Give smoothie recipe for:'),
  coffee4:      makeCmd('☕', SYS.food + ' Give coffee brewing tips for:'),
  tea3:         makeCmd('🍵', SYS.food + ' Give tea brewing tips for:'),
  sourdough2:   makeCmd('🍞', SYS.food + ' Give sourdough bread tips for:'),
  veganmeal:    makeCmd('🌱', SYS.food + ' Suggest vegan meal ideas for:'),
  vegetarian2:  makeCmd('🥦', SYS.food + ' Suggest vegetarian meal ideas for:'),
  glutenfree:   makeCmd('🌾', SYS.food + ' Suggest gluten-free ideas for:'),
  dairyfree:    makeCmd('🥛', SYS.food + ' Suggest dairy-free ideas for:'),
  ketofood:     makeCmd('🥑', SYS.food + ' Suggest keto meal ideas for:'),
  paleorecipe:  makeCmd('🦴', SYS.food + ' Suggest paleo recipe for:'),
  mealprep:     makeCmd('📦', SYS.food + ' Give meal prep tips for:'),
  mealplan2:    makeCmd('📅', SYS.food + ' Create a meal plan for:'),
  budgetmeal:   makeCmd('💰', SYS.food + ' Suggest budget-friendly meal ideas for:'),
  partyfood:    makeCmd('🎉', SYS.food + ' Suggest party food ideas for:'),
  kidfood:      makeCmd('👶', SYS.food + ' Suggest kid-friendly meal ideas for:'),
  streetfood:   makeCmd('🌮', SYS.food + ' Tell me about street food in:'),
  foodhistory2: makeCmd('📜', SYS.food + ' Share the history and origin of:'),
  superfood:    makeCmd('💪', SYS.food + ' Explain superfood benefits of:'),
  foodsub:      makeCmd('🔄', SYS.food + ' Suggest food substitutions for:'),
  leftover:     makeCmd('♻️', SYS.food + ' Give leftover recipe ideas for:'),
  foodpairing:  makeCmd('🍽️', SYS.food + ' Explain food flavor pairing for:'),

  // ── Travel (50) ────────────────────────────────────────────────────────────
  budgettrav2:  makeCmd('💰', SYS.travel + ' Give budget travel tips for:'),
  luxtravel2:   makeCmd('✈️', SYS.travel + ' Give luxury travel tips for:'),
  backpack3:    makeCmd('🎒', SYS.travel + ' Give backpacking tips for:'),
  solotrav2:    makeCmd('🧍', SYS.travel + ' Give solo travel tips for:'),
  familytrav2:  makeCmd('👨‍👩‍👧‍👦', SYS.travel + ' Give family travel tips for:'),
  coupletrav:   makeCmd('👫', SYS.travel + ' Give couple travel ideas for:'),
  adventtrav:   makeCmd('🏔️', SYS.travel + ' Give adventure travel tips for:'),
  ecotrav:      makeCmd('🌿', SYS.travel + ' Give eco-travel tips for:'),
  culturetrav:  makeCmd('🎭', SYS.travel + ' Give cultural travel tips for:'),
  foodtrav2:    makeCmd('🍜', SYS.travel + ' Give food travel tips for:'),
  digitalnomad2:makeCmd('💻', SYS.travel + ' Give digital nomad travel tips for:'),
  visatip2:     makeCmd('📋', SYS.travel + ' Give visa tips for:'),
  airlinehack:  makeCmd('✈️', SYS.travel + ' Give airline booking hacks for:'),
  layover2:     makeCmd('⏱️', SYS.travel + ' What to do during a layover in:'),
  hotelbooking: makeCmd('🏨', SYS.travel + ' Give hotel booking tips for:'),
  airbnb3:      makeCmd('🏠', SYS.travel + ' Give Airbnb tips for:'),
  camping3:     makeCmd('⛺', SYS.travel + ' Give camping tips for:'),
  glamping2:    makeCmd('✨', SYS.travel + ' Give glamping tips for:'),
  roadtrip3:    makeCmd('🚗', SYS.travel + ' Give road trip tips for:'),
  cruisetip2:   makeCmd('🚢', SYS.travel + ' Give cruise travel tips for:'),
  trainjourne2: makeCmd('🚂', SYS.travel + ' Give train travel tips for:'),
  hiketip2:     makeCmd('🥾', SYS.travel + ' Give hiking tips for:'),
  mountaineer: makeCmd('🏔️', SYS.travel + ' Give mountaineering tips for:'),
  beachtrip2:   makeCmd('🏖️', SYS.travel + ' Give beach trip tips for:'),
  islandhopp2:  makeCmd('🏝️', SYS.travel + ' Give island hopping tips for:'),
  deserttrip2:  makeCmd('🏜️', SYS.travel + ' Give desert travel tips for:'),
  citytour2:    makeCmd('🏙️', SYS.travel + ' Give city tour tips for:'),
  hiddengem:    makeCmd('💎', SYS.travel + ' Find hidden gems in:'),
  offpath3:     makeCmd('🗺️', SYS.travel + ' Give off-the-beaten-path tips for:'),
  localexper:   makeCmd('🤝', SYS.travel + ' Give tips on experiencing local culture in:'),
  travelmoney:  makeCmd('💳', SYS.travel + ' Give money saving travel tips for:'),
  packlight:    makeCmd('🧳', SYS.travel + ' Give packing light tips for:'),
  capsulepack2: makeCmd('👔', SYS.travel + ' Create a capsule packing list for:'),
  jetlag2:      makeCmd('😴', SYS.travel + ' Give jet lag recovery tips for:'),
  travinsure2:  makeCmd('🛡️', SYS.travel + ' Give travel insurance tips for:'),
  travscam2:    makeCmd('⚠️', SYS.travel + ' Warn about common travel scams in:'),
  tourtip2:     makeCmd('🗺️', SYS.travel + ' Give tour tips for:'),
  safetravel2:  makeCmd('🔒', SYS.travel + ' Give safety tips for travel in:'),
  simcard2:     makeCmd('📱', SYS.travel + ' Give SIM card/data tips for travel in:'),
  currexch2:    makeCmd('💱', SYS.travel + ' Give currency exchange tips for:'),
  langbarrier:  makeCmd('🗣️', SYS.travel + ' Give language barrier tips for travel in:'),
  travelapp:    makeCmd('📱', SYS.travel + ' Recommend travel apps for:'),
  instagramspot:makeCmd('📸', SYS.travel + ' Find Instagrammable spots in:'),
  sunrisespot:  makeCmd('🌅', SYS.travel + ' Find best sunrise/sunset spots in:'),
  nightlife2:   makeCmd('🌙', SYS.travel + ' Give nightlife tips for:'),
  daytripidea:  makeCmd('🚌', SYS.travel + ' Suggest day trips from:'),
  weekendtrip:  makeCmd('🗓️', SYS.travel + ' Plan a weekend trip to:'),
  itinerary:    makeCmd('📋', SYS.travel + ' Create a travel itinerary for:'),
  travelquote:  makeCmd('✨', SYS.travel + ' Share travel wisdom or quotes about:'),
  travelhistory:makeCmd('📜', SYS.travel + ' Share the travel and history of:'),
  travelfood:   makeCmd('🍽️', SYS.travel + ' What must-try food in:'),

  // ── Health / Wellness (50) ─────────────────────────────────────────────────
  stretching3:  makeCmd('🤸', SYS.health + ' Give stretching tips for:'),
  mobility2:    makeCmd('🦵', SYS.health + ' Give mobility exercise advice for:'),
  flexibility3: makeCmd('🧘', SYS.health + ' Give flexibility tips for:'),
  posture3:     makeCmd('🪑', SYS.health + ' Give posture improvement tips for:'),
  ergonomics2:  makeCmd('💺', SYS.health + ' Give ergonomics tips for:'),
  workoutplan2: makeCmd('💪', SYS.health + ' Create a workout plan for:'),
  strengthprog: makeCmd('🏋️', SYS.health + ' Create a strength training program for:'),
  cardioplan2:  makeCmd('🏃', SYS.health + ' Create a cardio plan for:'),
  hiitwrkt2:    makeCmd('⚡', SYS.health + ' Create a HIIT workout for:'),
  yogatype2:    makeCmd('🧘', SYS.health + ' Explain yoga type or style for:'),
  pilatestype2: makeCmd('🤸', SYS.health + ' Explain Pilates for:'),
  martialtip:   makeCmd('🥋', SYS.health + ' Give martial arts tips for:'),
  swimtip:      makeCmd('🏊', SYS.health + ' Give swimming tips for:'),
  cyclingtip:   makeCmd('🚴', SYS.health + ' Give cycling tips for:'),
  runningtip:   makeCmd('🏃', SYS.health + ' Give running tips for:'),
  injuryprev2:  makeCmd('🛡️', SYS.health + ' Give injury prevention tips for:'),
  recovtip:     makeCmd('💆', SYS.health + ' Give recovery tips for:'),
  protein3:     makeCmd('💪', SYS.health + ' Give protein nutrition advice for:'),
  carbstip:     makeCmd('🍞', SYS.health + ' Give carbohydrate nutrition advice for:'),
  fatguide2:    makeCmd('🥑', SYS.health + ' Give healthy fats advice for:'),
  fiberguide2:  makeCmd('🥦', SYS.health + ' Give fiber nutrition advice for:'),
  vitaminsg:    makeCmd('💊', SYS.health + ' Give vitamin guidance for:'),
  mineralsg:    makeCmd('🔬', SYS.health + ' Give mineral nutrition advice for:'),
  hydrate3:     makeCmd('💧', SYS.health + ' Give hydration tips for:'),
  electrolyte2: makeCmd('⚡', SYS.health + ' Give electrolyte advice for:'),
  guthealth:    makeCmd('🦠', SYS.health + ' Give gut health advice for:'),
  digesthealth: makeCmd('🫃', SYS.health + ' Give digestive health tips for:'),
  immunehealth: makeCmd('🛡️', SYS.health + ' Give immune system boosting tips for:'),
  hearthealth:  makeCmd('❤️', SYS.health + ' Give heart health tips for:'),
  brainfood:    makeCmd('🧠', SYS.health + ' Give brain health food tips for:'),
  skinhealth:   makeCmd('✨', SYS.health + ' Give skin health tips for:'),
  hairhealth:   makeCmd('💇', SYS.health + ' Give hair health tips for:'),
  eyehealth:    makeCmd('👁️', SYS.health + ' Give eye health tips for:'),
  sleephealth:  makeCmd('😴', SYS.health + ' Give sleep health tips for:'),
  stresshlth:   makeCmd('🧘', SYS.health + ' Give stress management health tips for:'),
  hormonhlth:   makeCmd('⚗️', SYS.health + ' Explain hormonal health in context of:'),
  mentalhlth:   makeCmd('🧠', SYS.health + ' Give mental health tips for:'),
  anxiety3:     makeCmd('😰', SYS.health + ' Give anxiety management tips for:'),
  depresshlth:  makeCmd('🌧️', SYS.health + ' Give depression support advice for:'),
  moodboost:    makeCmd('☀️', SYS.health + ' Give mood-boosting tips for:'),
  energyboost:  makeCmd('⚡', SYS.health + ' Give natural energy boosting tips for:'),
  detox2:       makeCmd('🌿', SYS.health + ' Give detox tips for:'),
  fasting2:     makeCmd('⏱️', SYS.health + ' Give fasting guidance for:'),
  weightloss:   makeCmd('⚖️', SYS.health + ' Give weight loss tips for:'),
  weightgain:   makeCmd('💪', SYS.health + ' Give healthy weight gain tips for:'),
  bmicalc2:     makeCmd('📊', SYS.health + ' Explain BMI and healthy weight for:'),
  agehealth:    makeCmd('⏳', SYS.health + ' Give age-specific health tips for:'),
  womenshlth:   makeCmd('♀️', SYS.health + ' Give women\'s health advice for:'),
  menshlth:     makeCmd('♂️', SYS.health + ' Give men\'s health advice for:'),
  seniorhlth:   makeCmd('👴', SYS.health + ' Give senior health advice for:'),

  // ── Entertainment (50) ────────────────────────────────────────────────────
  movierec3:    makeCmd('🎬', SYS.ent + ' Recommend movies for:'),
  seriesrec2:   makeCmd('📺', SYS.ent + ' Recommend TV series for:'),
  animerec2:    makeCmd('🎌', SYS.ent + ' Recommend anime for:'),
  documrec:     makeCmd('🎥', SYS.ent + ' Recommend documentaries about:'),
  standupcomd2: makeCmd('🎤', SYS.ent + ' Recommend stand-up comedians for:'),
  podcast3:     makeCmd('🎙️', SYS.ent + ' Recommend podcasts about:'),
  bookrec2:     makeCmd('📚', SYS.ent + ' Recommend books about:'),
  mangaseries2: makeCmd('📖', SYS.ent + ' Recommend manga/manhwa about:'),
  webtoon2:     makeCmd('💻', SYS.ent + ' Recommend webtoons about:'),
  kdrama2:      makeCmd('🎭', SYS.ent + ' Recommend K-dramas about:'),
  bollywood2:   makeCmd('💃', SYS.ent + ' Recommend Bollywood movies about:'),
  horrormov:    makeCmd('👻', SYS.ent + ' Recommend horror movies for:'),
  scifimov:     makeCmd('🚀', SYS.ent + ' Recommend sci-fi movies for:'),
  thriller2:    makeCmd('😰', SYS.ent + ' Recommend thrillers for:'),
  actionmov:    makeCmd('💥', SYS.ent + ' Recommend action movies for:'),
  comedy2:      makeCmd('😂', SYS.ent + ' Recommend comedies for:'),
  romancemov:   makeCmd('💕', SYS.ent + ' Recommend romance movies for:'),
  animationmov: makeCmd('🎨', SYS.ent + ' Recommend animated movies/shows for:'),
  realtv:       makeCmd('📺', SYS.ent + ' Discuss reality TV shows about:'),
  gamesrec:     makeCmd('🎮', SYS.ent + ' Recommend video games for:'),
  rpgames:      makeCmd('🗡️', SYS.ent + ' Recommend RPG games for:'),
  indiegames:   makeCmd('🎮', SYS.ent + ' Recommend indie games for:'),
  streamingtip: makeCmd('📡', SYS.ent + ' Give streaming platform tips for:'),
  ytchan2:      makeCmd('▶️', SYS.ent + ' Recommend YouTube channels about:'),
  musicrec3:    makeCmd('🎵', SYS.ent + ' Recommend music for:'),
  albumrec2:    makeCmd('💿', SYS.ent + ' Recommend albums for:'),
  artistbio2:   makeCmd('🎤', SYS.ent + ' Share info about artist:'),
  playlistrec2: makeCmd('🎧', SYS.ent + ' Suggest playlist theme for:'),
  concerttip2:  makeCmd('🎸', SYS.ent + ' Give concert tips for:'),
  popculture2:  makeCmd('🌟', SYS.ent + ' Discuss pop culture topic:'),
  fantheory:    makeCmd('🤔', SYS.ent + ' Share fan theory about:'),
  movieanalysis:makeCmd('🔍', SYS.ent + ' Analyze movie themes in:'),
  actorbio:     makeCmd('🎬', SYS.ent + ' Share facts about:'),
  directorinfo: makeCmd('🎥', SYS.ent + ' Share info about director:'),
  oscarnoms:    makeCmd('🏆', SYS.ent + ' Discuss Oscar-worthy aspects of:'),
  emmytv:       makeCmd('📺', SYS.ent + ' Discuss Emmy-worthy aspects of:'),
  grammytip:    makeCmd('🎵', SYS.ent + ' Discuss Grammy-worthy aspects of:'),
  comicmarvel:  makeCmd('🦸', SYS.ent + ' Discuss Marvel/comic topic:'),
  dccomics:     makeCmd('🦇', SYS.ent + ' Discuss DC comics topic:'),
  videoessay:   makeCmd('🎬', SYS.ent + ' Give a video essay breakdown on:'),
  memehistory2: makeCmd('😂', SYS.ent + ' Explain meme or internet culture about:'),
  viralcontent: makeCmd('📱', SYS.ent + ' Discuss viral content topic:'),
  internetfun:  makeCmd('🌐', SYS.ent + ' Discuss internet culture topic:'),
  nostalgiatv:  makeCmd('📺', SYS.ent + ' Discuss nostalgic TV or movie:'),
  nerdguide2:   makeCmd('🤓', SYS.ent + ' Give nerd/geek culture guide for:'),
  cosplay2:     makeCmd('🎭', SYS.ent + ' Give cosplay tips for:'),
  fanfic2:      makeCmd('✍️', SYS.ent + ' Give fan fiction ideas for:'),
  contreview:   makeCmd('⭐', SYS.ent + ' Give review framework for:'),
  watchorder:   makeCmd('📋', SYS.ent + ' Give watch order/reading order for:'),
  deepcut:      makeCmd('💎', SYS.ent + ' Recommend underrated gems in:'),

  // ── Nature (50) ────────────────────────────────────────────────────────────
  forestfact2:  makeCmd('🌲', SYS.nature + ' Explain forest ecology:'),
  rainforest2:  makeCmd('🌿', SYS.nature + ' Explain rainforest ecosystem:'),
  junglefact:   makeCmd('🐆', SYS.nature + ' Explain jungle ecosystem:'),
  savannaface:  makeCmd('🦁', SYS.nature + ' Explain savanna ecosystem:'),
  desert3:      makeCmd('🏜️', SYS.nature + ' Explain desert ecosystem:'),
  tundra2:      makeCmd('🏔️', SYS.nature + ' Explain tundra ecosystem:'),
  arcticfact:   makeCmd('🧊', SYS.nature + ' Explain Arctic ecosystem:'),
  oceanfact2:   makeCmd('🌊', SYS.nature + ' Explain ocean ecosystem:'),
  deepocean2:   makeCmd('🐙', SYS.nature + ' Explain deep ocean facts:'),
  coralfact2:   makeCmd('🪸', SYS.nature + ' Explain coral reef facts:'),
  bioluminesc:  makeCmd('✨', SYS.nature + ' Explain bioluminescence:'),
  tides:        makeCmd('🌊', SYS.nature + ' Explain ocean tides:'),
  weatherpat:   makeCmd('🌩️', SYS.nature + ' Explain weather pattern:'),
  climate4:     makeCmd('🌡️', SYS.nature + ' Explain climate topic:'),
  seasons:      makeCmd('🍂', SYS.nature + ' Explain seasonal change:'),
  hurricanefact2:makeCmd('🌀', SYS.nature + ' Explain hurricane/cyclone science:'),
  tornado3:     makeCmd('🌪️', SYS.nature + ' Explain tornado science:'),
  lightning3:   makeCmd('⚡', SYS.nature + ' Explain lightning science:'),
  blizzard3:    makeCmd('❄️', SYS.nature + ' Explain blizzard science:'),
  drought3:     makeCmd('🌵', SYS.nature + ' Explain drought science:'),
  flood3:       makeCmd('🌊', SYS.nature + ' Explain flood science:'),
  glacierfact2: makeCmd('🧊', SYS.nature + ' Explain glacier science:'),
  iceagefact:   makeCmd('🧊', SYS.nature + ' Explain ice age facts:'),
  birdfact2:    makeCmd('🦅', SYS.nature + ' Share bird facts:'),
  reptilefact2: makeCmd('🦎', SYS.nature + ' Share reptile facts:'),
  insectfact2:  makeCmd('🦋', SYS.nature + ' Share insect facts:'),
  butterflyfact:makeCmd('🦋', SYS.nature + ' Share butterfly facts:'),
  pollination2: makeCmd('🐝', SYS.nature + ' Explain pollination:'),
  predprey:     makeCmd('🦁', SYS.nature + ' Explain predator-prey dynamics:'),
  parasitelife: makeCmd('🦠', SYS.nature + ' Explain parasite-host relationships:'),
  symbiosis3:   makeCmd('🤝', SYS.nature + ' Explain symbiosis:'),
  treefacts:    makeCmd('🌳', SYS.nature + ' Share tree facts:'),
  plantfacts2:  makeCmd('🌿', SYS.nature + ' Share plant biology facts:'),
  mushroomfact: makeCmd('🍄', SYS.nature + ' Share fungi/mushroom facts:'),
  algaefact:    makeCmd('🌿', SYS.nature + ' Share algae/seaweed facts:'),
  migration:    makeCmd('✈️', SYS.nature + ' Explain animal migration:'),
  hibernation:  makeCmd('😴', SYS.nature + ' Explain animal hibernation:'),
  camouflage:   makeCmd('🎨', SYS.nature + ' Explain animal camouflage:'),
  venomfact:    makeCmd('☠️', SYS.nature + ' Share venom/toxin facts:'),
  communicat:   makeCmd('📡', SYS.nature + ' Explain animal communication:'),
  intelligenc:  makeCmd('🧠', SYS.nature + ' Explain animal intelligence:'),
  extinctfact:  makeCmd('💀', SYS.nature + ' Share extinction facts:'),
  endangeredsp: makeCmd('⚠️', SYS.nature + ' Discuss endangered species:'),
  conservation: makeCmd('🌿', SYS.nature + ' Discuss conservation topic:'),
  biodivers:    makeCmd('🌍', SYS.nature + ' Explain biodiversity:'),
  naturaladapt: makeCmd('🔄', SYS.nature + ' Explain natural adaptation:'),
  extremophile: makeCmd('🦠', SYS.nature + ' Explain extremophile organisms:'),
  forestbath:   makeCmd('🌲', SYS.nature + ' Explain forest bathing benefits:'),
  earthfact:    makeCmd('🌍', SYS.nature + ' Share Earth science facts:'),

  // ── Language (50) ──────────────────────────────────────────────────────────
  etymology4:   makeCmd('📚', SYS.lang + ' Explain the etymology/origin of word:'),
  wordorigin2:  makeCmd('📖', SYS.lang + ' Explain the origin of word or phrase:'),
  slang4:       makeCmd('😎', SYS.lang + ' Explain slang:'),
  idiom3:       makeCmd('💬', SYS.lang + ' Explain idiom:'),
  proverb3:     makeCmd('💡', SYS.lang + ' Explain proverb:'),
  colloquism:   makeCmd('🗣️', SYS.lang + ' Explain colloquialism:'),
  jargon2:      makeCmd('💼', SYS.lang + ' Explain jargon in:'),
  pidginlang:   makeCmd('🌐', SYS.lang + ' Explain pidgin language:'),
  creolefact:   makeCmd('🌺', SYS.lang + ' Explain creole language:'),
  dialect3:     makeCmd('🗣️', SYS.lang + ' Explain dialect of:'),
  accent3:      makeCmd('🎤', SYS.lang + ' Explain accent differences in:'),
  tonallang:    makeCmd('🎵', SYS.lang + ' Explain tonal languages:'),
  clicklang:    makeCmd('👆', SYS.lang + ' Explain click languages:'),
  signlang2:    makeCmd('👋', SYS.lang + ' Explain sign language facts:'),
  linguistfact: makeCmd('📚', SYS.lang + ' Share linguistics facts about:'),
  phonetics2:   makeCmd('🔊', SYS.lang + ' Explain phonetics concept:'),
  morphology2:  makeCmd('🔤', SYS.lang + ' Explain morphology concept:'),
  syntax3:      makeCmd('🔡', SYS.lang + ' Explain syntax concept:'),
  semantic3:    makeCmd('💭', SYS.lang + ' Explain semantics concept:'),
  pragmatic3:   makeCmd('🤝', SYS.lang + ' Explain pragmatics concept:'),
  socioling2:   makeCmd('👥', SYS.lang + ' Explain sociolinguistics:'),
  psycholing:   makeCmd('🧠', SYS.lang + ' Explain psycholinguistics:'),
  neurolng2:    makeCmd('🧠', SYS.lang + ' Explain neurolinguistics:'),
  multilingual2:makeCmd('🌐', SYS.lang + ' Give multilingual tips for:'),
  bilingualps:  makeCmd('💬', SYS.lang + ' Explain bilingualism benefits:'),
  polyglottip:  makeCmd('🌍', SYS.lang + ' Give polyglot learning tips for:'),
  langlearn3:   makeCmd('📚', SYS.lang + ' Give language learning tips for:'),
  memorytip3:   makeCmd('🧠', SYS.lang + ' Give memory tips for language learning:'),
  spacedrep2:   makeCmd('🔄', SYS.lang + ' Explain spaced repetition for:'),
  flashcard2:   makeCmd('📋', SYS.lang + ' Give flashcard tips for:'),
  immersion:    makeCmd('🌊', SYS.lang + ' Give language immersion tips for:'),
  translate3:   makeCmd('🔄', SYS.lang + ' Translate and explain nuances of:'),
  swearfact:    makeCmd('😤', SYS.lang + ' Explain swear words or profanity in:'),
  euph2:        makeCmd('🌸', SYS.lang + ' Explain euphemisms in:'),
  languagemyst: makeCmd('🔍', SYS.lang + ' Explain language mystery or anomaly:'),
  deadlang:     makeCmd('💀', SYS.lang + ' Explain dead/extinct language:'),
  conlang:      makeCmd('🎭', SYS.lang + ' Explain constructed language:'),
  klingon:      makeCmd('👽', SYS.lang + ' Explain fictional language:'),
  codeswitchf:  makeCmd('🔄', SYS.lang + ' Explain code-switching:'),
  lwcfact:      makeCmd('🌐', SYS.lang + ' Explain lingua franca:'),
  officiallangs:makeCmd('📜', SYS.lang + ' Explain official languages of:'),
  writsystem:   makeCmd('✍️', SYS.lang + ' Explain writing system:'),
  alphabetfact: makeCmd('🔤', SYS.lang + ' Explain alphabet facts:'),
  hieroglyph:   makeCmd('📜', SYS.lang + ' Explain hieroglyphics:'),
  cuneiform:    makeCmd('📜', SYS.lang + ' Explain cuneiform writing:'),
  langevolve:   makeCmd('🔄', SYS.lang + ' Explain language evolution:'),
  wordcoinage:  makeCmd('💡', SYS.lang + ' Explain how new words are coined:'),
  neologism:    makeCmd('✨', SYS.lang + ' Explain neologism (new words):'),
  wordfrequency:makeCmd('📊', SYS.lang + ' Explain word frequency and usage:'),
  palindrome2:  makeCmd('🔄', SYS.lang + ' Explain palindrome examples:'),

  // ── Art (50) ───────────────────────────────────────────────────────────────
  arthistory3:  makeCmd('🎨', SYS.art + ' Explain art history topic:'),
  artmovement:  makeCmd('🖼️', SYS.art + ' Explain art movement:'),
  impres2:      makeCmd('🌅', SYS.art + ' Explain Impressionism:'),
  express2:     makeCmd('🎭', SYS.art + ' Explain Expressionism:'),
  cubism3:      makeCmd('🔲', SYS.art + ' Explain Cubism:'),
  surreal4:     makeCmd('🌀', SYS.art + ' Explain Surrealism:'),
  dadaism2:     makeCmd('🎭', SYS.art + ' Explain Dadaism:'),
  bauhaus2:     makeCmd('⬛', SYS.art + ' Explain Bauhaus design:'),
  artdeco2:     makeCmd('✨', SYS.art + ' Explain Art Deco:'),
  artnouveau2:  makeCmd('🌿', SYS.art + ' Explain Art Nouveau:'),
  renaissance3: makeCmd('🏛️', SYS.art + ' Explain the Renaissance art:'),
  baroque3:     makeCmd('👑', SYS.art + ' Explain Baroque art:'),
  romantic3:    makeCmd('💕', SYS.art + ' Explain Romanticism in art:'),
  realism3:     makeCmd('📷', SYS.art + ' Explain Realism in art:'),
  modern3:      makeCmd('⬜', SYS.art + ' Explain Modernism in art:'),
  postmod3:     makeCmd('🎭', SYS.art + ' Explain Postmodernism in art:'),
  contempart:   makeCmd('🖼️', SYS.art + ' Explain contemporary art:'),
  streetart3:   makeCmd('🎨', SYS.art + ' Explain street art:'),
  graffiti3:    makeCmd('✏️', SYS.art + ' Explain graffiti as art:'),
  muralism2:    makeCmd('🖼️', SYS.art + ' Explain muralism:'),
  installart:   makeCmd('🎭', SYS.art + ' Explain installation art:'),
  performart2:  makeCmd('🎭', SYS.art + ' Explain performance art:'),
  conceptart2:  makeCmd('💡', SYS.art + ' Explain conceptual art:'),
  digitalart3:  makeCmd('💻', SYS.art + ' Explain digital art:'),
  illustrat3:   makeCmd('✏️', SYS.art + ' Give illustration tips for:'),
  animationtip: makeCmd('🎬', SYS.art + ' Give animation tips for:'),
  film3:        makeCmd('🎬', SYS.art + ' Explain filmmaking concept:'),
  photo3:       makeCmd('📷', SYS.art + ' Give photography tips for:'),
  typo3:        makeCmd('🔡', SYS.art + ' Explain typography concept:'),
  graphic3:     makeCmd('🎨', SYS.art + ' Give graphic design tips for:'),
  uiux2:        makeCmd('📱', SYS.art + ' Give UI/UX design tips for:'),
  interior3:    makeCmd('🏠', SYS.art + ' Give interior design tips for:'),
  fashion3:     makeCmd('👗', SYS.art + ' Give fashion design tips for:'),
  jewelry2:     makeCmd('💎', SYS.art + ' Discuss jewelry design:'),
  sculpture3:   makeCmd('🗿', SYS.art + ' Explain sculpture techniques:'),
  ceramics2:    makeCmd('🏺', SYS.art + ' Explain ceramics techniques:'),
  pottery2:     makeCmd('🏺', SYS.art + ' Give pottery tips for:'),
  printmaking2: makeCmd('🖨️', SYS.art + ' Explain printmaking:'),
  weaving2:     makeCmd('🧵', SYS.art + ' Explain weaving art:'),
  calligrap3:   makeCmd('✍️', SYS.art + ' Give calligraphy tips for:'),
  origami3:     makeCmd('📄', SYS.art + ' Give origami instructions for:'),
  manga4:       makeCmd('📖', SYS.art + ' Explain manga art style:'),
  comic3:       makeCmd('💬', SYS.art + ' Give comic book art tips for:'),
  colortheory2: makeCmd('🎨', SYS.art + ' Explain color theory for:'),
  compositn:    makeCmd('🖼️', SYS.art + ' Explain composition principles for:'),
  perspective4: makeCmd('📐', SYS.art + ' Explain perspective in art for:'),
  lightshade:   makeCmd('💡', SYS.art + ' Explain light and shading techniques:'),
  artcritic:    makeCmd('🔍', SYS.art + ' Give art criticism framework for:'),
  arthistmast:  makeCmd('🏛️', SYS.art + ' Explain art from master artist:'),
  artmarket:    makeCmd('💰', SYS.art + ' Explain art market and investing in art:'),

  // ── Money / Finance (50) ──────────────────────────────────────────────────
  stock3:       makeCmd('📈', SYS.money + ' Explain stock market concept:'),
  etf3:         makeCmd('📊', SYS.money + ' Explain ETF investing:'),
  indexfund:    makeCmd('📈', SYS.money + ' Explain index fund investing:'),
  bond3:        makeCmd('📜', SYS.money + ' Explain bond investing:'),
  forex3:       makeCmd('💱', SYS.money + ' Explain forex trading:'),
  crypto4:      makeCmd('₿', SYS.money + ' Explain crypto investing:'),
  bitcoin4:     makeCmd('🟠', SYS.money + ' Explain Bitcoin concept:'),
  ethereum4:    makeCmd('⟠', SYS.money + ' Explain Ethereum concept:'),
  altcoin2:     makeCmd('🪙', SYS.money + ' Explain altcoins:'),
  defi4:        makeCmd('🔗', SYS.money + ' Explain DeFi concept:'),
  dividend2:    makeCmd('💰', SYS.money + ' Explain dividend investing:'),
  compound2:    makeCmd('📈', SYS.money + ' Explain compound interest:'),
  retire2:      makeCmd('🏖️', SYS.money + ' Give retirement planning tips for:'),
  fire3:        makeCmd('🔥', SYS.money + ' Explain FIRE movement for:'),
  frugal3:      makeCmd('💰', SYS.money + ' Give frugal living tips for:'),
  minimalmoney: makeCmd('🧘', SYS.money + ' Give minimalist money tips for:'),
  budgeting3:   makeCmd('📊', SYS.money + ' Give budgeting tips for:'),
  envelopes2:   makeCmd('📩', SYS.money + ' Explain envelope budgeting method:'),
  rule503020:   makeCmd('📊', SYS.money + ' Explain the 50/30/20 budget rule:'),
  debtpay:      makeCmd('💳', SYS.money + ' Give debt payoff strategies for:'),
  snowball:     makeCmd('⛄', SYS.money + ' Explain debt snowball method:'),
  avalanche2:   makeCmd('🏔️', SYS.money + ' Explain debt avalanche method:'),
  creditcard3:  makeCmd('💳', SYS.money + ' Give credit card tips for:'),
  creditbuild2: makeCmd('📈', SYS.money + ' Give credit score building tips for:'),
  mortgage3:    makeCmd('🏠', SYS.money + ' Explain mortgage concepts for:'),
  invest3:      makeCmd('💹', SYS.money + ' Give investing tips for:'),
  stockpick:    makeCmd('🎯', SYS.money + ' Give stock picking tips for:'),
  portflio2:    makeCmd('📊', SYS.money + ' Give portfolio building advice for:'),
  riskmanage2:  makeCmd('🛡️', SYS.money + ' Give risk management tips for:'),
  optionbasic2: makeCmd('📋', SYS.money + ' Explain options trading basics:'),
  realestate3:  makeCmd('🏘️', SYS.money + ' Give real estate investing tips for:'),
  rental3:      makeCmd('🏠', SYS.money + ' Give rental property tips for:'),
  passive3:     makeCmd('💤', SYS.money + ' Give passive income ideas for:'),
  royalty2:     makeCmd('👑', SYS.money + ' Give royalty income tips for:'),
  freelance4:   makeCmd('💼', SYS.money + ' Give freelancing income tips for:'),
  taxoptimize3: makeCmd('🏦', SYS.money + ' Give tax optimization tips for:'),
  estateplnng:  makeCmd('📜', SYS.money + ' Give estate planning tips for:'),
  insurance2:   makeCmd('🛡️', SYS.money + ' Give insurance guidance for:'),
  emergency:    makeCmd('💰', SYS.money + ' Give emergency fund tips for:'),
  sidehustle:   makeCmd('💡', SYS.money + ' Suggest side hustle ideas for:'),
  ecommerce2:   makeCmd('🛒', SYS.money + ' Give e-commerce money tips for:'),
  dropship:     makeCmd('📦', SYS.money + ' Explain dropshipping business:'),
  affiliatemkt: makeCmd('🔗', SYS.money + ' Explain affiliate marketing:'),
  contentmoney: makeCmd('💰', SYS.money + ' Give content creator income tips for:'),
  coursecreat:  makeCmd('🎓', SYS.money + ' Give online course creation tips for:'),
  coachingbiz:  makeCmd('🎯', SYS.money + ' Give coaching business tips for:'),
  saasmoney:    makeCmd('☁️', SYS.money + ' Give SaaS revenue tips for:'),
  inflationhack:makeCmd('📈', SYS.money + ' Give inflation-beating strategies for:'),
  savelarge:    makeCmd('💰', SYS.money + ' Give tips for saving large amounts for:'),

  // ── Debate (50) ────────────────────────────────────────────────────────────
  procon3:      makeCmd('⚖️', SYS.debate + ' Give pros and cons of:'),
  argstruct2:   makeCmd('🏗️', SYS.debate + ' Explain argument structure for:'),
  counterarg3:  makeCmd('🔄', SYS.debate + ' Give counterarguments to:'),
  strawman2:    makeCmd('🌾', SYS.debate + ' Identify and correct strawman fallacy in:'),
  adhomin:      makeCmd('😤', SYS.debate + ' Explain ad hominem fallacy in:'),
  redherring2:  makeCmd('🐟', SYS.debate + ' Explain red herring fallacy in:'),
  slippyslope2: makeCmd('⛷️', SYS.debate + ' Explain slippery slope fallacy in:'),
  falsedilem2:  makeCmd('⚖️', SYS.debate + ' Explain false dilemma in:'),
  circularreasn:makeCmd('🔄', SYS.debate + ' Explain circular reasoning in:'),
  appeal2emo:   makeCmd('😢', SYS.debate + ' Explain appeal to emotion in:'),
  bandwagon3:   makeCmd('🚌', SYS.debate + ' Explain bandwagon fallacy in:'),
  cherrypick:   makeCmd('🍒', SYS.debate + ' Explain cherry-picking in:'),
  falseeq2:     makeCmd('⚖️', SYS.debate + ' Explain false equivalence in:'),
  syllogism3:   makeCmd('📐', SYS.debate + ' Explain syllogism in:'),
  deductive3:   makeCmd('🔽', SYS.debate + ' Explain deductive reasoning for:'),
  inductive3:   makeCmd('🔼', SYS.debate + ' Explain inductive reasoning for:'),
  abductive3:   makeCmd('🔍', SYS.debate + ' Explain abductive reasoning for:'),
  bayesian3:    makeCmd('📊', SYS.debate + ' Apply Bayesian thinking to:'),
  probabilit2:  makeCmd('🎲', SYS.debate + ' Explain probability reasoning for:'),
  statfallacy:  makeCmd('📊', SYS.debate + ' Identify statistical fallacy in:'),
  samplbias2:   makeCmd('🎯', SYS.debate + ' Explain sampling bias in:'),
  confirmbs2:   makeCmd('🔮', SYS.debate + ' Explain confirmation bias in:'),
  cogdissonance:makeCmd('🤯', SYS.debate + ' Explain cognitive dissonance in:'),
  anchor3:      makeCmd('⚓', SYS.debate + ' Explain anchoring bias in:'),
  framing3:     makeCmd('🖼️', SYS.debate + ' Explain framing effect in:'),
  lossavers2:   makeCmd('😟', SYS.debate + ' Explain loss aversion in:'),
  survivbias3:  makeCmd('⚡', SYS.debate + ' Explain survivorship bias in:'),
  regret2mean:  makeCmd('📊', SYS.debate + ' Explain regression to the mean in:'),
  parsimony2:   makeCmd('🔪', SYS.debate + ' Apply Occam\'s Razor to:'),
  occam3:       makeCmd('🔪', SYS.debate + ' Apply parsimony principle to:'),
  popperianism: makeCmd('🔬', SYS.debate + ' Apply Popperian falsificationism to:'),
  firstprinc:   makeCmd('🔑', SYS.debate + ' Apply first principles thinking to:'),
  steelman3:    makeCmd('🦾', SYS.debate + ' Steelman the argument for:'),
  hotake2:      makeCmd('🔥', SYS.debate + ' Give a hot take on:'),
  unpopop2:     makeCmd('⚡', SYS.debate + ' Give an unpopular opinion on:'),
  debunk2:      makeCmd('🔍', SYS.debate + ' Debunk the claim:'),
  mythbust2:    makeCmd('💥', SYS.debate + ' Bust the myth about:'),
  factcheck3:   makeCmd('✅', SYS.debate + ' Fact-check the claim:'),
  moraldilemma: makeCmd('⚖️', SYS.debate + ' Analyze the moral dilemma of:'),
  ethicaldebate:makeCmd('🏛️', SYS.debate + ' Debate the ethical implications of:'),
  policyargue:  makeCmd('📜', SYS.debate + ' Argue both sides of policy:'),
  scientificit: makeCmd('🔬', SYS.debate + ' Evaluate the scientific claim:'),
  expertissue:  makeCmd('🎓', SYS.debate + ' Evaluate expert disagreement on:'),
  futuredebate: makeCmd('🔮', SYS.debate + ' Debate future implications of:'),
  techethics:   makeCmd('⚙️', SYS.debate + ' Debate the ethics of technology:'),
  aiethics2:    makeCmd('🤖', SYS.debate + ' Debate AI ethics of:'),
  economicdebat:makeCmd('📊', SYS.debate + ' Debate the economics of:'),
  socialissue:  makeCmd('👥', SYS.debate + ' Analyze social issue:'),
  justicedebat: makeCmd('⚖️', SYS.debate + ' Debate justice in:'),
  freedomdebat: makeCmd('🗽', SYS.debate + ' Debate freedom vs security in:'),
};
