'use strict';
/**
 * megapack1.js — Ultra Command Pack 1
 * 500 AI-powered commands: Tech/Dev, Business, Psychology, Relationship,
 * Dark Humor, Philosophy, Conspiracy, Self-help, Trivia, Science
 */
const pollinations = require('../lib/pollinations');

function makeCmd(emoji, sys) {
  return async (sock, msg, args) => {
    const jid = msg.key.remoteJid;
    const topic = args.join(' ');
    if (!topic) return sock.sendMessage(jid, { text: `${emoji} _Give me a topic or question!_` }, { quoted: msg });
    await sock.sendMessage(jid, { text: `${emoji} _Processing..._` }, { quoted: msg });
    try {
      const reply = await pollinations.textGenerate([
        { role: 'system', content: sys },
        { role: 'user', content: topic },
      ]);
      await sock.sendMessage(jid, { text: `${emoji} *${reply}*\n\n_⚡ DollarBot V-Ultra_` }, { quoted: msg });
    } catch (e) {
      await sock.sendMessage(jid, { text: `❌ Error: ${e.message}` }, { quoted: msg });
    }
  };
}

const SYS = {
  dev: 'You are an expert software engineer. Give practical, precise dev advice using WhatsApp markdown (*bold*, _italic_, bullet points). No tables or HTML.',
  biz: 'You are a top-tier business strategist. Give sharp, actionable business advice in WhatsApp markdown. No tables or HTML.',
  psych: 'You are a behavioral psychologist. Explain psychology concepts clearly in WhatsApp markdown. Be insightful and grounded. No tables or HTML.',
  relate: 'You are a relationship expert. Give honest, warm, practical relationship advice in WhatsApp markdown. No tables or HTML.',
  dark: 'You are a dark humor comedian. Give a witty, darkly funny response about the topic. WhatsApp markdown only. Keep it tasteful but edgy.',
  phil: 'You are a philosopher. Explore the philosophical dimensions of this topic thoughtfully in WhatsApp markdown. No tables or HTML.',
  conspi: 'You are a conspiracy theorist character. Give a creative, wild conspiracy angle on this topic. WhatsApp markdown only. Clearly fictional/satirical.',
  self: 'You are a self-improvement coach. Give clear, motivating self-help advice in WhatsApp markdown. No tables or HTML.',
  trivia: 'You are a trivia expert. Share fascinating, accurate facts and trivia about this topic. WhatsApp markdown only. No tables or HTML.',
  sci: 'You are a science communicator. Explain the science clearly and engagingly in WhatsApp markdown. No tables or HTML.',
};

module.exports = {
  // ── Tech / Dev (50) ────────────────────────────────────────────────────────
  devadvice:    makeCmd('💻', SYS.dev + ' Topic: general dev advice about'),
  codereview:   makeCmd('🔍', SYS.dev + ' Do a mini code review / feedback on this code or concept:'),
  bugfix:       makeCmd('🐛', SYS.dev + ' Help debug this issue:'),
  refactor:     makeCmd('🔧', SYS.dev + ' Suggest how to refactor or improve this code/concept:'),
  optimize:     makeCmd('⚡', SYS.dev + ' Suggest optimization strategies for:'),
  securecode:   makeCmd('🔐', SYS.dev + ' Explain security best practices for:'),
  apidoc:       makeCmd('📄', SYS.dev + ' Explain how to document or use this API/feature:'),
  dbquery:      makeCmd('🗄️', SYS.dev + ' Help with this database or query question:'),
  algorithmtip: makeCmd('🧮', SYS.dev + ' Explain this algorithm or data structure:'),
  regexhelp:    makeCmd('🔣', SYS.dev + ' Help create or explain a regex pattern for:'),
  gitcmds:      makeCmd('🌿', SYS.dev + ' Explain or help with this git scenario:'),
  dockerhelp:   makeCmd('🐳', SYS.dev + ' Give Docker guidance for:'),
  cloudtips:    makeCmd('☁️', SYS.dev + ' Give cloud architecture advice for:'),
  microservice: makeCmd('⚙️', SYS.dev + ' Explain microservices concepts for:'),
  devopstip:    makeCmd('🔄', SYS.dev + ' Give DevOps/CI-CD advice for:'),
  testcase:     makeCmd('✅', SYS.dev + ' Help write test cases or explain testing strategy for:'),
  mockdata:     makeCmd('📊', SYS.dev + ' Explain or generate mock data structure for:'),
  apidesign:    makeCmd('🏗️', SYS.dev + ' Give REST API design advice for:'),
  gqlhelp:      makeCmd('⬡', SYS.dev + ' Help with GraphQL design or query for:'),
  bashscript:   makeCmd('💲', SYS.dev + ' Help write or explain a bash script for:'),
  pythontip:    makeCmd('🐍', SYS.dev + ' Give Python tips or explain a Python concept:'),
  jstips:       makeCmd('🟨', SYS.dev + ' Give JavaScript/Node.js tips about:'),
  cpptips:      makeCmd('⚙️', SYS.dev + ' Explain a C++ concept or help with:'),
  javaoops:     makeCmd('☕', SYS.dev + ' Explain Java OOP or help with:'),
  gotips:       makeCmd('🐹', SYS.dev + ' Give Go language tips about:'),
  rusttips:     makeCmd('🦀', SYS.dev + ' Give Rust language guidance for:'),
  reacttips:    makeCmd('⚛️', SYS.dev + ' Give React/Next.js tips about:'),
  vuehelp:      makeCmd('💚', SYS.dev + ' Help with Vue.js concept or issue:'),
  nodehelp:     makeCmd('🟩', SYS.dev + ' Help with Node.js issue or concept:'),
  djangohelp:   makeCmd('🎸', SYS.dev + ' Help with Django or Python web dev:'),
  flasktip:     makeCmd('🌶️', SYS.dev + ' Help with Flask or Python backend:'),
  sqlhelp:      makeCmd('📋', SYS.dev + ' Help with SQL query or database design:'),
  nosqlhelp:    makeCmd('🍃', SYS.dev + ' Help with NoSQL (MongoDB, Redis etc.) design:'),
  csstips:      makeCmd('🎨', SYS.dev + ' Give CSS/styling tips for:'),
  htmlhelp:     makeCmd('🌐', SYS.dev + ' Help with HTML structure or semantic:'),
  linuxcmds:    makeCmd('🐧', SYS.dev + ' Give Linux command help for:'),
  networkingbas:makeCmd('🔌', SYS.dev + ' Explain networking concept:'),
  sysdesign:    makeCmd('🏛️', SYS.dev + ' Give system design guidance for:'),
  loadbalance:  makeCmd('⚖️', SYS.dev + ' Explain load balancing strategy for:'),
  caching:      makeCmd('💾', SYS.dev + ' Explain caching strategies for:'),
  websockets:   makeCmd('🔗', SYS.dev + ' Explain WebSocket usage for:'),
  grpchelp:     makeCmd('📡', SYS.dev + ' Help with gRPC design or usage:'),
  k8shelp:      makeCmd('☸️', SYS.dev + ' Give Kubernetes guidance for:'),
  mlbasics:     makeCmd('🤖', SYS.dev + ' Explain machine learning concept:'),
  deeplearning: makeCmd('🧠', SYS.dev + ' Explain deep learning topic:'),
  devcareer:    makeCmd('🚀', SYS.dev + ' Give software engineering career advice about:'),
  techinterview:makeCmd('💼', SYS.dev + ' Help prepare for technical interview question:'),
  coderoutine:  makeCmd('📅', SYS.dev + ' Suggest a daily coding routine or study plan for:'),
  opensource:   makeCmd('🌍', SYS.dev + ' Give open source contribution tips for:'),
  freelancedev: makeCmd('💰', SYS.dev + ' Give freelance dev career advice about:'),

  // ── Business (50) ──────────────────────────────────────────────────────────
  bizplan:      makeCmd('📋', SYS.biz + ' Create a mini business plan framework for:'),
  marketstrat2: makeCmd('📈', SYS.biz + ' Give marketing strategy advice for:'),
  salesscript:  makeCmd('🗣️', SYS.biz + ' Write a sales conversation or script approach for:'),
  coldcall:     makeCmd('📞', SYS.biz + ' Give cold calling tips or script for:'),
  emailpitch:   makeCmd('📧', SYS.biz + ' Write a business email pitch approach for:'),
  investordeck: makeCmd('💼', SYS.biz + ' Outline an investor deck structure for:'),
  pitchperfect: makeCmd('🎯', SYS.biz + ' Give pitching tips and structure for:'),
  competition:  makeCmd('⚔️', SYS.biz + ' Help analyze the competitive landscape for:'),
  swotanal:     makeCmd('🔲', SYS.biz + ' Do a SWOT analysis outline for:'),
  bizmodel:     makeCmd('🏗️', SYS.biz + ' Explain or suggest a business model for:'),
  revmodel:     makeCmd('💵', SYS.biz + ' Suggest revenue model strategies for:'),
  custpersona:  makeCmd('👤', SYS.biz + ' Create a customer persona for:'),
  valueprop:    makeCmd('💎', SYS.biz + ' Craft a value proposition for:'),
  gtmstrat:     makeCmd('🚀', SYS.biz + ' Give go-to-market strategy advice for:'),
  brandstory:   makeCmd('📖', SYS.biz + ' Help craft a brand story for:'),
  contentplan:  makeCmd('📅', SYS.biz + ' Create a content marketing plan for:'),
  growthhack:   makeCmd('📊', SYS.biz + ' Give growth hacking ideas for:'),
  scaleup:      makeCmd('📡', SYS.biz + ' Give startup scaling advice for:'),
  productlaunch:makeCmd('🎉', SYS.biz + ' Give product launch strategy for:'),
  teambuilding: makeCmd('👥', SYS.biz + ' Give team building advice for:'),
  hirescript:   makeCmd('📋', SYS.biz + ' Help create a hiring process or job description for:'),
  managertip:   makeCmd('🎓', SYS.biz + ' Give management and leadership tips for:'),
  delegatetip:  makeCmd('🤝', SYS.biz + ' Give delegation tips for:'),
  meetingagenda:makeCmd('📌', SYS.biz + ' Create a meeting agenda structure for:'),
  okrgoals:     makeCmd('🎯', SYS.biz + ' Help set OKR goals for:'),
  kpitrack:     makeCmd('📊', SYS.biz + ' Suggest KPIs to track for:'),
  performrev:   makeCmd('⭐', SYS.biz + ' Give performance review tips for:'),
  conflictsolv: makeCmd('🕊️', SYS.biz + ' Give conflict resolution strategies for:'),
  negotiatetip: makeCmd('🤝', SYS.biz + ' Give negotiation tactics for:'),
  salestip:     makeCmd('💰', SYS.biz + ' Give sales improvement tips for:'),
  closedeal:    makeCmd('🔒', SYS.biz + ' Give closing strategies for:'),
  followupemail:makeCmd('📩', SYS.biz + ' Write follow-up email approach for:'),
  customersucc: makeCmd('😊', SYS.biz + ' Give customer success strategies for:'),
  churnreduce:  makeCmd('🔄', SYS.biz + ' Give churn reduction strategies for:'),
  referralplan: makeCmd('👋', SYS.biz + ' Design a referral program for:'),
  partnerplan:  makeCmd('🤝', SYS.biz + ' Give business partnership strategies for:'),
  exitstrat:    makeCmd('🚪', SYS.biz + ' Outline exit strategy options for:'),
  fundraise:    makeCmd('💸', SYS.biz + ' Give fundraising advice for:'),
  vcfunding:    makeCmd('💼', SYS.biz + ' Give VC funding tips for:'),
  crowdfund:    makeCmd('🌊', SYS.biz + ' Give crowdfunding campaign advice for:'),
  ipoprep:      makeCmd('📈', SYS.biz + ' Explain IPO preparation steps for:'),
  accountingtip:makeCmd('🧮', SYS.biz + ' Give accounting or bookkeeping tips for:'),
  taxstrat:     makeCmd('🏦', SYS.biz + ' Give tax optimization strategies for:'),
  cashflow:     makeCmd('💧', SYS.biz + ' Give cash flow management tips for:'),
  invoicetip:   makeCmd('📄', SYS.biz + ' Give invoicing and payment collection tips for:'),
  profitmargin: makeCmd('📊', SYS.biz + ' Explain how to improve profit margins for:'),
  biznetwork:   makeCmd('🌐', SYS.biz + ' Give business networking tips for:'),
  brandrep:     makeCmd('⭐', SYS.biz + ' Give brand reputation management advice for:'),
  prcrisis:     makeCmd('🚨', SYS.biz + ' Give PR crisis management advice for:'),
  ecomstrat:    makeCmd('🛒', SYS.biz + ' Give e-commerce strategy advice for:'),
  saasmodel:    makeCmd('☁️', SYS.biz + ' Give SaaS business model advice for:'),

  // ── Psychology (50) ────────────────────────────────────────────────────────
  psychtip:     makeCmd('🧠', SYS.psych + ' Topic:'),
  cognbias:     makeCmd('🔮', SYS.psych + ' Explain this cognitive bias:'),
  selfaware:    makeCmd('🪞', SYS.psych + ' Give self-awareness tips about:'),
  emotiq:       makeCmd('💡', SYS.psych + ' Explain emotional intelligence in this context:'),
  empathypsych: makeCmd('💛', SYS.psych + ' Explain empathy dynamics in:'),
  bodylang:     makeCmd('🤸', SYS.psych + ' Explain body language signals in:'),
  readpeople:   makeCmd('👀', SYS.psych + ' Explain how to read people or this behavior:'),
  persuasion:   makeCmd('🎯', SYS.psych + ' Explain the psychology of persuasion in:'),
  darkpsych:    makeCmd('🌑', SYS.psych + ' Explain dark psychology patterns in:'),
  narcissism:   makeCmd('🪞', SYS.psych + ' Explain narcissistic patterns in:'),
  gaslighting:  makeCmd('🔥', SYS.psych + ' Explain gaslighting patterns in:'),
  attachsty:    makeCmd('💞', SYS.psych + ' Explain attachment styles in context of:'),
  traumabond:   makeCmd('⛓️', SYS.psych + ' Explain trauma bonding in:'),
  selfesteem:   makeCmd('🌟', SYS.psych + ' Give self-esteem building tips for:'),
  impostersynd: makeCmd('😟', SYS.psych + ' Explain imposter syndrome in:'),
  procrastpsych:makeCmd('⏰', SYS.psych + ' Explain the psychology of procrastination in:'),
  motivepsych:  makeCmd('🚀', SYS.psych + ' Explain motivation psychology in:'),
  habitpsych:   makeCmd('🔄', SYS.psych + ' Explain habit formation psychology for:'),
  addictpsych:  makeCmd('🔗', SYS.psych + ' Explain addiction psychology for:'),
  angercontrol: makeCmd('😤', SYS.psych + ' Give anger control strategies for:'),
  griefcycles:  makeCmd('💔', SYS.psych + ' Explain grief cycles in:'),
  anxietysci:   makeCmd('😰', SYS.psych + ' Explain anxiety psychology for:'),
  depressinfo:  makeCmd('🌧️', SYS.psych + ' Explain depression psychology for:'),
  burnsign:     makeCmd('🔥', SYS.psych + ' Explain burnout signs and recovery for:'),
  wlbalance:    makeCmd('⚖️', SYS.psych + ' Explain work-life balance psychology for:'),
  boundaries:   makeCmd('🛑', SYS.psych + ' Explain setting boundaries in:'),
  lovepsych:    makeCmd('💕', SYS.psych + ' Explain love psychology in:'),
  jealousy:     makeCmd('💚', SYS.psych + ' Explain jealousy psychology in:'),
  loneliness:   makeCmd('🌑', SYS.psych + ' Explain loneliness psychology in:'),
  socianxiety:  makeCmd('😟', SYS.psych + ' Explain social anxiety in:'),
  shyness:      makeCmd('😊', SYS.psych + ' Explain shyness vs introversion:'),
  intropsych:   makeCmd('🤫', SYS.psych + ' Explain introvert psychology in:'),
  extropsy:     makeCmd('🗣️', SYS.psych + ' Explain extrovert psychology in:'),
  empathpsy:    makeCmd('🌊', SYS.psych + ' Explain empath psychology in:'),
  resilience:   makeCmd('💪', SYS.psych + ' Explain psychological resilience for:'),
  growthpsy:    makeCmd('🌱', SYS.psych + ' Explain growth mindset psychology for:'),
  selfsabotage: makeCmd('⛏️', SYS.psych + ' Explain self-sabotage patterns in:'),
  perfectionism:makeCmd('✨', SYS.psych + ' Explain perfectionism psychology in:'),
  overthink:    makeCmd('🌀', SYS.psych + ' Explain overthinking psychology for:'),
  mindset3:     makeCmd('🧠', SYS.psych + ' Explain mindset concept:'),
  scarcitymind: makeCmd('😟', SYS.psych + ' Explain scarcity mindset in:'),
  gratitudepsy: makeCmd('🙏', SYS.psych + ' Explain gratitude psychology for:'),
  positivity:   makeCmd('☀️', SYS.psych + ' Explain positive psychology concept:'),
  reframe:      makeCmd('🔄', SYS.psych + ' Help reframe this negative thought or situation:'),
  cogshift:     makeCmd('⚡', SYS.psych + ' Explain cognitive shift strategies for:'),
  groupthink:   makeCmd('👥', SYS.psych + ' Explain groupthink dynamics in:'),
  conformity:   makeCmd('👔', SYS.psych + ' Explain conformity psychology in:'),
  obedience:    makeCmd('📋', SYS.psych + ' Explain obedience psychology in:'),
  powerpsych:   makeCmd('👑', SYS.psych + ' Explain power dynamics in:'),
  tribalpsych:  makeCmd('🔥', SYS.psych + ' Explain tribal/in-group psychology in:'),

  // ── Relationship (50) ──────────────────────────────────────────────────────
  firstdate:    makeCmd('🌹', SYS.relate + ' Give first date tips for:'),
  textrules:    makeCmd('📱', SYS.relate + ' Give texting etiquette tips for:'),
  datingapp:    makeCmd('💘', SYS.relate + ' Give dating app tips for:'),
  attractiontip:makeCmd('✨', SYS.relate + ' Explain attraction dynamics for:'),
  flirt4:       makeCmd('😏', SYS.relate + ' Give flirting tips for:'),
  confesscrush: makeCmd('💌', SYS.relate + ' Give advice on confessing feelings for:'),
  longdisttips: makeCmd('✈️', SYS.relate + ' Give long distance relationship tips for:'),
  breakupadvice:makeCmd('💔', SYS.relate + ' Give breakup advice for:'),
  moveon:       makeCmd('🌅', SYS.relate + ' Give moving on advice for:'),
  toxicrelat:   makeCmd('☠️', SYS.relate + ' Identify toxic relationship patterns in:'),
  commtips:     makeCmd('🗣️', SYS.relate + ' Give communication tips for couples in:'),
  lovematch:    makeCmd('💞', SYS.relate + ' Explain love compatibility for:'),
  compattips:   makeCmd('🔗', SYS.relate + ' Explain relationship compatibility factors:'),
  friendzone:   makeCmd('👫', SYS.relate + ' Give advice on:'),
  crush4:       makeCmd('💕', SYS.relate + ' Give advice about having a crush on:'),
  proposal2:    makeCmd('💍', SYS.relate + ' Give proposal tips for:'),
  wedtips:      makeCmd('💒', SYS.relate + ' Give wedding planning tips for:'),
  honeymoon:    makeCmd('🌴', SYS.relate + ' Suggest honeymoon ideas for:'),
  datingbndry:  makeCmd('🛑', SYS.relate + ' Give boundaries advice for dating situation:'),
  selfrespect:  makeCmd('👑', SYS.relate + ' Give self-respect advice for:'),
  exbackadv:    makeCmd('🔄', SYS.relate + ' Give advice about getting back with an ex:'),
  closure:      makeCmd('🚪', SYS.relate + ' Give closure advice for:'),
  forgiveness:  makeCmd('🕊️', SYS.relate + ' Give forgiveness advice for:'),
  selflove2:    makeCmd('💖', SYS.relate + ' Give self-love tips for:'),
  singlelife:   makeCmd('🌟', SYS.relate + ' Give single life advice for:'),
  marriageadv:  makeCmd('💒', SYS.relate + ' Give marriage advice for:'),
  introfriends: makeCmd('👋', SYS.relate + ' Give advice on making new friends:'),
  friendstips:  makeCmd('👥', SYS.relate + ' Give friendship maintenance tips for:'),
  toxfriends:   makeCmd('☠️', SYS.relate + ' Give advice on toxic friendships:'),
  conflit2:     makeCmd('⚡', SYS.relate + ' Give conflict resolution tips for:'),
  apologize:    makeCmd('🙏', SYS.relate + ' Give advice on how to apologize for:'),
  reconnect:    makeCmd('🔄', SYS.relate + ' Give advice on reconnecting with:'),
  redflags2:    makeCmd('🚩', SYS.relate + ' List red flags to watch for in:'),
  grnflags2:    makeCmd('🟢', SYS.relate + ' List green flags in a relationship context of:'),
  boundaries3:  makeCmd('🛑', SYS.relate + ' Help set healthy boundaries in:'),
  trustissues:  makeCmd('🔓', SYS.relate + ' Give advice on trust issues in:'),
  jealous3:     makeCmd('💚', SYS.relate + ' Give advice on managing jealousy in:'),
  coparent:     makeCmd('👨‍👩‍👧', SYS.relate + ' Give co-parenting advice for:'),
  familydrama:  makeCmd('👨‍👩‍👧‍👦', SYS.relate + ' Give advice on family conflict:'),
  parentalrel:  makeCmd('👨‍👩‍👧', SYS.relate + ' Give advice on parent-child relationship:'),
  siblingrel:   makeCmd('👫', SYS.relate + ' Give sibling relationship advice for:'),
  inlaws:       makeCmd('🏠', SYS.relate + ' Give in-law relationship advice for:'),
  workrelation: makeCmd('💼', SYS.relate + ' Give workplace relationship advice for:'),
  mentorrelat:  makeCmd('🎓', SYS.relate + ' Give mentor-mentee relationship advice for:'),
  networkrelat: makeCmd('🌐', SYS.relate + ' Give professional networking relationship tips for:'),
  bossfriend:   makeCmd('🤝', SYS.relate + ' Give advice on boss-employee relationship for:'),
  onlove:       makeCmd('💌', SYS.relate + ' Give deep insight on love and:'),
  lovevsattach: makeCmd('💞', SYS.relate + ' Explain the difference between love and attachment in:'),
  soulconx:     makeCmd('🌟', SYS.relate + ' Explain deep soul connection in:'),

  // ── Dark Humor (50) ────────────────────────────────────────────────────────
  darkmeme:     makeCmd('💀', SYS.dark + ' Topic:'),
  existcrisis:  makeCmd('🌀', SYS.dark + ' Make an existentially funny comment about:'),
  nihilism4:    makeCmd('😶', SYS.dark + ' Give a nihilistically funny perspective on:'),
  absurdist:    makeCmd('🎭', SYS.dark + ' Give an absurdist comedic take on:'),
  deathhumor:   makeCmd('💀', SYS.dark + ' Make a darkly funny joke about:'),
  satire3:      makeCmd('🗞️', SYS.dark + ' Write a satirical take on:'),
  sarcasm3:     makeCmd('😏', SYS.dark + ' Give a brutally sarcastic response to:'),
  irony3:       makeCmd('🙃', SYS.dark + ' Give an ironic comedic take on:'),
  cynic2:       makeCmd('😒', SYS.dark + ' Give a cynical but funny perspective on:'),
  deadpan:      makeCmd('😐', SYS.dark + ' Give a deadpan funny response to:'),
  selfdeprec:   makeCmd('😅', SYS.dark + ' Write a self-deprecating funny take on:'),
  awkward3:     makeCmd('😬', SYS.dark + ' Give an awkwardly funny response to:'),
  cringe3:      makeCmd('😬', SYS.dark + ' Give a cringeworthy but funny take on:'),
  taboo2:       makeCmd('🚫', SYS.dark + ' Give a taboo-but-funny comedic take on:'),
  controvercomd:makeCmd('⚡', SYS.dark + ' Give a controversial but comedic take on:'),
  unpopular3:   makeCmd('🎯', SYS.dark + ' Give an unpopular but funny opinion on:'),
  wrongopinion: makeCmd('🔄', SYS.dark + ' Give a hilariously wrong opinion about:'),
  callout2:     makeCmd('📢', SYS.dark + ' Roast or call out the absurdity of:'),
  rant3:        makeCmd('😤', SYS.dark + ' Give a comedic rant about:'),
  overreact:    makeCmd('😱', SYS.dark + ' Dramatically overreact to:'),
  worstcase3:   makeCmd('😭', SYS.dark + ' Give the worst-case scenario for:'),
  bestworst:    makeCmd('🏆', SYS.dark + ' Give the best worst take on:'),
  conspirocomd: makeCmd('🔍', SYS.dark + ' Give a comedic conspiracy theory about:'),
  mediocre:     makeCmd('🤷', SYS.dark + ' Give a mediocre, underwhelming response to:'),
  dramatic:     makeCmd('🎭', SYS.dark + ' Dramatically overanalyze:'),
  overthinkjoke:makeCmd('🌀', SYS.dark + ' Overthink and make it funny:'),
  pettycomic:   makeCmd('😤', SYS.dark + ' Give a pettily funny response to:'),
  anticlimaxjk: makeCmd('😑', SYS.dark + ' Give an anticlimactic funny response to:'),
  comicminimize:makeCmd('🤏', SYS.dark + ' Humorously minimize the importance of:'),
  comicexagger: makeCmd('📢', SYS.dark + ' Humorously exaggerate the importance of:'),
  roast3:       makeCmd('🔥', SYS.dark + ' Write a (respectful) roast about:'),
  meanspirit:   makeCmd('😈', SYS.dark + ' Give a mean but funny fictional take on:'),
  comicvillain: makeCmd('🦹', SYS.dark + ' Write a comedic villain monologue about:'),
  adulthumor:   makeCmd('😂', SYS.dark + ' Give a mature but clever funny take on:'),
  bitterhumor:  makeCmd('😤', SYS.dark + ' Give a bitterly funny response to:'),
  jaded:        makeCmd('😒', SYS.dark + ' Give a jaded, been-there-done-that funny response to:'),
  clownmode:    makeCmd('🤡', SYS.dark + ' Go full clown mode on:'),
  chaosmode:    makeCmd('🌪️', SYS.dark + ' Give a chaotic funny response to:'),
  cursedtake:   makeCmd('😈', SYS.dark + ' Give a cursed funny take on:'),
  edgelord:     makeCmd('😈', SYS.dark + ' Give a slightly edgy but funny take on:'),
  boomer2:      makeCmd('👴', SYS.dark + ' React to this like a funny boomer:'),
  genalpha:     makeCmd('👶', SYS.dark + ' React to this like a funny Gen Alpha:'),
  millennial2:  makeCmd('😬', SYS.dark + ' React to this like a funny millennial:'),
  genz2:        makeCmd('✨', SYS.dark + ' React to this in funny Gen Z style:'),
  corpspeak:    makeCmd('💼', SYS.dark + ' Translate this into funny corporate speak:'),
  passive:      makeCmd('😊', SYS.dark + ' Give a passive-aggressive funny response to:'),
  pettyrevenge: makeCmd('😈', SYS.dark + ' Suggest a petty but funny response to:'),
  firstworld:   makeCmd('😭', SYS.dark + ' Give a first-world-problems take on:'),
  karmacomic:   makeCmd('🔄', SYS.dark + ' Give a karmic funny take on:'),

  // ── Philosophy (50) ────────────────────────────────────────────────────────
  meaning:      makeCmd('🌌', SYS.phil + ' Explore the meaning or philosophical significance of:'),
  freewill3:    makeCmd('🔓', SYS.phil + ' Explore free will vs determinism in context of:'),
  determinism3: makeCmd('🔗', SYS.phil + ' Explore determinism philosophy regarding:'),
  consciousness:makeCmd('🧠', SYS.phil + ' Explore the philosophy of consciousness:'),
  dualism:      makeCmd('☯️', SYS.phil + ' Explore mind-body dualism in:'),
  empiricism:   makeCmd('🔬', SYS.phil + ' Explain empiricism in context of:'),
  rationalism:  makeCmd('🧮', SYS.phil + ' Explain rationalism in context of:'),
  pragmatism:   makeCmd('🤝', SYS.phil + ' Apply pragmatism philosophy to:'),
  utilitarian:  makeCmd('⚖️', SYS.phil + ' Apply utilitarianism to:'),
  deontology:   makeCmd('📜', SYS.phil + ' Apply deontological ethics to:'),
  virtue:       makeCmd('⚡', SYS.phil + ' Explore virtue ethics in context of:'),
  existential4: makeCmd('🌑', SYS.phil + ' Explore existentialism in context of:'),
  absurdism:    makeCmd('🎭', SYS.phil + ' Explore absurdism in context of:'),
  nihil4:       makeCmd('😶', SYS.phil + ' Explore nihilism in context of:'),
  stoicphil:    makeCmd('🏛️', SYS.phil + ' Apply Stoic philosophy to:'),
  epicurphil:   makeCmd('🌺', SYS.phil + ' Apply Epicurean philosophy to:'),
  buddhistphil: makeCmd('☮️', SYS.phil + ' Apply Buddhist philosophy to:'),
  taoistphil:   makeCmd('☯️', SYS.phil + ' Apply Taoist philosophy to:'),
  confucianphil:makeCmd('📜', SYS.phil + ' Apply Confucian philosophy to:'),
  kantphil:     makeCmd('📐', SYS.phil + ' Apply Kantian philosophy to:'),
  platophil:    makeCmd('🏛️', SYS.phil + ' Apply Platonic philosophy to:'),
  aristotle2:   makeCmd('📚', SYS.phil + ' Apply Aristotelian philosophy to:'),
  socratphil:   makeCmd('❓', SYS.phil + ' Apply Socratic method to explore:'),
  nietzphil:    makeCmd('⚡', SYS.phil + ' Apply Nietzsche\'s philosophy to:'),
  hegelphil:    makeCmd('🔄', SYS.phil + ' Apply Hegelian dialectic to:'),
  marxphil:     makeCmd('✊', SYS.phil + ' Apply Marxist philosophy to:'),
  foucaultphil: makeCmd('🔍', SYS.phil + ' Apply Foucault\'s analysis to:'),
  camusphil:    makeCmd('🌅', SYS.phil + ' Apply Camus\'s absurdism to:'),
  sartrephil:   makeCmd('🔑', SYS.phil + ' Apply Sartre\'s existentialism to:'),
  rawlsphil:    makeCmd('⚖️', SYS.phil + ' Apply Rawlsian justice theory to:'),
  popperphil:   makeCmd('🔬', SYS.phil + ' Apply Popperian falsificationism to:'),
  dennett:      makeCmd('🧠', SYS.phil + ' Apply Dennett\'s philosophy of mind to:'),
  chalmersphil: makeCmd('💡', SYS.phil + ' Explore Chalmers\' hard problem of consciousness in:'),
  philzone:     makeCmd('🌌', SYS.phil + ' Apply philosophical framework to:'),
  ethicsof:     makeCmd('⚖️', SYS.phil + ' Explore the ethics of:'),
  moralobject:  makeCmd('📜', SYS.phil + ' Explore moral objectivism vs relativism in:'),
  metaphysics:  makeCmd('🌌', SYS.phil + ' Explore the metaphysics of:'),
  ontology:     makeCmd('🧩', SYS.phil + ' Explore the ontology of:'),
  epistemology: makeCmd('📚', SYS.phil + ' Explore epistemological questions about:'),
  aesthetics:   makeCmd('🎨', SYS.phil + ' Explore the aesthetics of:'),
  politphil:    makeCmd('🏛️', SYS.phil + ' Explore the political philosophy of:'),
  langphil:     makeCmd('🗣️', SYS.phil + ' Explore the philosophy of language in:'),
  sciencephil:  makeCmd('🔬', SYS.phil + ' Explore the philosophy of science in:'),
  mathphil:     makeCmd('∞', SYS.phil + ' Explore the philosophy of mathematics in:'),
  timephil:     makeCmd('⏰', SYS.phil + ' Explore the philosophy of time in:'),
  identphil:    makeCmd('👤', SYS.phil + ' Explore the philosophy of personal identity in:'),
  deathphil:    makeCmd('💀', SYS.phil + ' Explore the philosophy of death in:'),
  godphil:      makeCmd('✝️', SYS.phil + ' Explore theological philosophy of:'),
  naturphil:    makeCmd('🌿', SYS.phil + ' Explore the philosophy of nature in:'),
  techphil:     makeCmd('⚙️', SYS.phil + ' Explore the philosophy of technology in:'),

  // ── Conspiracy (50) ────────────────────────────────────────────────────────
  flatearth2:   makeCmd('🌍', SYS.conspi + ' Topic: flat earth'),
  moonconspi:   makeCmd('🌑', SYS.conspi + ' Topic: moon landing'),
  illuminati3:  makeCmd('👁️', SYS.conspi + ' Topic: illuminati'),
  freemason2:   makeCmd('🔺', SYS.conspi + ' Topic: freemasons'),
  reptilian2:   makeCmd('🦎', SYS.conspi + ' Topic: reptilian overlords'),
  chemtrail2:   makeCmd('✈️', SYS.conspi + ' Topic: chemtrails'),
  bilderberg2:  makeCmd('🏦', SYS.conspi + ' Topic: Bilderberg group'),
  deepstate3:   makeCmd('🕵️', SYS.conspi + ' Topic:'),
  shadowgov:    makeCmd('🌑', SYS.conspi + ' Topic: shadow government'),
  nwoconspi:    makeCmd('🌐', SYS.conspi + ' Topic: New World Order'),
  mkultra2:     makeCmd('🧪', SYS.conspi + ' Topic: MK-Ultra'),
  jfk2:         makeCmd('🎯', SYS.conspi + ' Topic: JFK assassination'),
  nineleven:    makeCmd('🏙️', SYS.conspi + ' Topic: 9/11'),
  area51b:      makeCmd('👽', SYS.conspi + ' Topic: Area 51 and aliens'),
  roswell3:     makeCmd('🛸', SYS.conspi + ' Topic: Roswell crash'),
  ufoconspi:    makeCmd('🛸', SYS.conspi + ' Topic:'),
  annunaki2:    makeCmd('👽', SYS.conspi + ' Topic: Annunaki ancient aliens'),
  simulation3:  makeCmd('💻', SYS.conspi + ' Topic: we live in a simulation'),
  mandela2:     makeCmd('🔄', SYS.conspi + ' Topic: Mandela effect'),
  glitch2:      makeCmd('⚡', SYS.conspi + ' Topic: matrix glitches in reality'),
  cern3:        makeCmd('⚛️', SYS.conspi + ' Topic: CERN opening portals'),
  waterfluoride2:makeCmd('💧', SYS.conspi + ' Topic: water fluoridation'),
  vaccine3:     makeCmd('💉', SYS.conspi + ' Fictional satirical take on vaccine conspiracy about:'),
  fiveg2:       makeCmd('📡', SYS.conspi + ' Topic: 5G towers'),
  haarp2:       makeCmd('⚡', SYS.conspi + ' Topic: HAARP weather control'),
  geoengineer:  makeCmd('☁️', SYS.conspi + ' Topic: geoengineering'),
  smartdust:    makeCmd('🔬', SYS.conspi + ' Topic: smart dust surveillance'),
  nanobots3:    makeCmd('🤖', SYS.conspi + ' Topic: nanobots in vaccines'),
  skinwalker2:  makeCmd('🐺', SYS.conspi + ' Topic: Skinwalker Ranch'),
  bigfoot3:     makeCmd('🦶', SYS.conspi + ' Topic: Bigfoot'),
  lochness3:    makeCmd('🦕', SYS.conspi + ' Topic: Loch Ness Monster'),
  bermuda2:     makeCmd('🌊', SYS.conspi + ' Topic: Bermuda Triangle'),
  eliteconspi:  makeCmd('👑', SYS.conspi + ' Topic:'),
  bankersworld: makeCmd('🏦', SYS.conspi + ' Topic: global banking elite control'),
  mediapuppet:  makeCmd('📺', SYS.conspi + ' Topic: media control conspiracy'),
  foodconspi:   makeCmd('🍔', SYS.conspi + ' Topic: food industry conspiracy'),
  pharmconspi:  makeCmd('💊', SYS.conspi + ' Topic: pharmaceutical industry conspiracy'),
  oilconspi:    makeCmd('🛢️', SYS.conspi + ' Topic: oil industry suppressing clean energy'),
  techconspi:   makeCmd('📱', SYS.conspi + ' Topic: big tech surveillance'),
  aiconspire:   makeCmd('🤖', SYS.conspi + ' Topic: AI takeover conspiracy'),
  psychconspi:  makeCmd('🧠', SYS.conspi + ' Topic: psychology being used for mind control'),
  educonspi:    makeCmd('📚', SYS.conspi + ' Topic: education system conspiracy'),
  weatherconspi:makeCmd('🌩️', SYS.conspi + ' Topic: weather control'),
  historyconspi:makeCmd('📜', SYS.conspi + ' Topic: hidden history and lost civilizations'),
  timelinconspi:makeCmd('⏰', SYS.conspi + ' Topic: timeline manipulation'),
  stargates2:   makeCmd('🌀', SYS.conspi + ' Topic: ancient stargates and portals'),
  ancienttech2: makeCmd('⚙️', SYS.conspi + ' Topic: advanced ancient technology'),
  pyramidconspi:makeCmd('🔺', SYS.conspi + ' Topic: pyramid secrets and alien connection'),
  atlantisconspi:makeCmd('🌊', SYS.conspi + ' Topic: Atlantis'),
  timeconspi:   makeCmd('⏳', SYS.conspi + ' Topic: time travel being hidden from public'),

  // ── Self-help (50) ─────────────────────────────────────────────────────────
  morningrout3: makeCmd('🌅', SYS.self + ' Create a morning routine framework for:'),
  nightrout3:   makeCmd('🌙', SYS.self + ' Create an evening routine for:'),
  productivity3:makeCmd('⚡', SYS.self + ' Give productivity tips for:'),
  deepwork2:    makeCmd('🎯', SYS.self + ' Explain deep work strategies for:'),
  pomodorotip:  makeCmd('🍅', SYS.self + ' Explain the Pomodoro technique for:'),
  gtdmethod:    makeCmd('✅', SYS.self + ' Explain the GTD method for:'),
  minimalist3:  makeCmd('🧘', SYS.self + ' Give minimalist lifestyle advice for:'),
  essentialism: makeCmd('🎯', SYS.self + ' Apply essentialism principles to:'),
  digitaldetox: makeCmd('📵', SYS.self + ' Give digital detox tips for:'),
  dopaminereset:makeCmd('🧠', SYS.self + ' Explain dopamine reset strategies for:'),
  smallwins:    makeCmd('🏆', SYS.self + ' Give small wins framework advice for:'),
  keystonehabit:makeCmd('🗝️', SYS.self + ' Explain keystone habit concept for:'),
  corevalues:   makeCmd('💎', SYS.self + ' Help identify core values for:'),
  purpose:      makeCmd('🌟', SYS.self + ' Help discover purpose in:'),
  ikigai:       makeCmd('⭕', SYS.self + ' Apply ikigai framework to:'),
  visionboard:  makeCmd('🎯', SYS.self + ' Help create a vision board concept for:'),
  goalset2:     makeCmd('🎯', SYS.self + ' Help set effective goals for:'),
  smartgoal:    makeCmd('✅', SYS.self + ' Apply SMART goal framework to:'),
  milestone:    makeCmd('🏁', SYS.self + ' Help set milestones for:'),
  accountability:makeCmd('🤝', SYS.self + ' Give accountability tips for:'),
  mentor3:      makeCmd('🎓', SYS.self + ' Give mentor/mentee advice for:'),
  journaling3:  makeCmd('📔', SYS.self + ' Give journaling tips for:'),
  gratitudejrn: makeCmd('🙏', SYS.self + ' Give gratitude journaling tips for:'),
  affirmation4: makeCmd('✨', SYS.self + ' Create powerful affirmations for:'),
  visualize3:   makeCmd('🌌', SYS.self + ' Explain visualization techniques for:'),
  meditation3:  makeCmd('🧘', SYS.self + ' Give meditation guidance for:'),
  breathwork3:  makeCmd('💨', SYS.self + ' Explain breathwork techniques for:'),
  coldshower2:  makeCmd('🧊', SYS.self + ' Explain cold shower benefits for:'),
  exercise3:    makeCmd('💪', SYS.self + ' Give exercise routine advice for:'),
  sleephyg:     makeCmd('😴', SYS.self + ' Give sleep hygiene tips for:'),
  nootropic2:   makeCmd('🧠', SYS.self + ' Explain nootropics and brain optimization for:'),
  biohack3:     makeCmd('⚗️', SYS.self + ' Give biohacking tips for:'),
  fastingtip:   makeCmd('⏱️', SYS.self + ' Give intermittent fasting tips for:'),
  balance3:     makeCmd('⚖️', SYS.self + ' Give life balance advice for:'),
  harmony:      makeCmd('☮️', SYS.self + ' Give inner harmony tips for:'),
  resilience4:  makeCmd('💪', SYS.self + ' Build resilience strategy for:'),
  confidence:   makeCmd('💪', SYS.self + ' Give confidence building tips for:'),
  public2:      makeCmd('🎤', SYS.self + ' Give public speaking tips for:'),
  introsocial:  makeCmd('🤝', SYS.self + ' Give social skills tips for introverts in:'),
  charisma:     makeCmd('✨', SYS.self + ' Give charisma building tips for:'),
  execpresence: makeCmd('👔', SYS.self + ' Give executive presence tips for:'),
  authority:    makeCmd('👑', SYS.self + ' Give tips on building authority in:'),
  discipline3:  makeCmd('🔒', SYS.self + ' Give discipline building advice for:'),
  consistency2: makeCmd('📅', SYS.self + ' Give consistency tips for:'),
  patience4:    makeCmd('⏳', SYS.self + ' Give patience-building advice for:'),
  detachment:   makeCmd('🧘', SYS.self + ' Explain healthy emotional detachment in:'),
  innerchild:   makeCmd('💛', SYS.self + ' Give inner child healing tips for:'),
  shadowwork:   makeCmd('🌑', SYS.self + ' Explain shadow work for:'),
  selfacceptance:makeCmd('💖', SYS.self + ' Give self-acceptance tips for:'),
  worthiness:   makeCmd('⭐', SYS.self + ' Give advice on building sense of worthiness for:'),

  // ── Trivia (50) ────────────────────────────────────────────────────────────
  weirdlaw:     makeCmd('⚖️', SYS.trivia + ' Topic: weird laws around the world'),
  strangebiz:   makeCmd('💼', SYS.trivia + ' Topic: strange businesses that actually exist'),
  oddfact2:     makeCmd('🤯', SYS.trivia + ' Topic:'),
  recordbrk:    makeCmd('🏆', SYS.trivia + ' Topic: world records'),
  firstever2:   makeCmd('🥇', SYS.trivia + ' Topic: first in history'),
  ancienttech3: makeCmd('⚙️', SYS.trivia + ' Topic: ancient technology'),
  lostciv2:     makeCmd('🏛️', SYS.trivia + ' Topic: lost civilizations'),
  mysteryfact2: makeCmd('🔍', SYS.trivia + ' Topic: unsolved mysteries'),
  paranormal3:  makeCmd('👻', SYS.trivia + ' Topic: paranormal facts'),
  hauntedplace: makeCmd('🏚️', SYS.trivia + ' Topic: haunted places'),
  historicfail: makeCmd('💥', SYS.trivia + ' Topic: epic historical failures'),
  luckyescape:  makeCmd('🍀', SYS.trivia + ' Topic: miraculous or lucky escapes'),
  bravehero:    makeCmd('🦸', SYS.trivia + ' Topic: unsung heroes in history'),
  forgottenhist:makeCmd('📜', SYS.trivia + ' Topic: forgotten history'),
  althistory:   makeCmd('🔄', SYS.trivia + ' Topic: what if moments in history'),
  animalbehav:  makeCmd('🦁', SYS.trivia + ' Topic: unusual animal behavior'),
  plantfacts:   makeCmd('🌿', SYS.trivia + ' Topic: unusual plant facts'),
  oceantriv:    makeCmd('🌊', SYS.trivia + ' Topic: deep ocean mysteries'),
  spacetriv:    makeCmd('🚀', SYS.trivia + ' Topic: space facts'),
  mathfun:      makeCmd('🔢', SYS.trivia + ' Topic: fun math facts'),
  languagefun:  makeCmd('🗣️', SYS.trivia + ' Topic: unusual language facts'),
  foodhistory:  makeCmd('🍕', SYS.trivia + ' Topic: food history and origins'),
  inventfact:   makeCmd('💡', SYS.trivia + ' Topic: invention history'),
  scienceweird: makeCmd('🔬', SYS.trivia + ' Topic: weird science facts'),
  psychtriv:    makeCmd('🧠', SYS.trivia + ' Topic: psychology facts'),
  humanbody:    makeCmd('🫀', SYS.trivia + ' Topic: human body facts'),
  animalsuper:  makeCmd('🦸', SYS.trivia + ' Topic: animal superpowers'),
  geogfacts:    makeCmd('🌍', SYS.trivia + ' Topic: geography facts'),
  popculttrivia:makeCmd('🎬', SYS.trivia + ' Topic: pop culture trivia'),
  musichistory: makeCmd('🎵', SYS.trivia + ' Topic: music history trivia'),
  arthistoryt:  makeCmd('🎨', SYS.trivia + ' Topic: art history trivia'),
  sportstriviac:makeCmd('⚽', SYS.trivia + ' Topic: sports trivia'),
  movietriv:    makeCmd('🎬', SYS.trivia + ' Topic: movie trivia'),
  tvtriv:       makeCmd('📺', SYS.trivia + ' Topic: TV show trivia'),
  booktriv:     makeCmd('📚', SYS.trivia + ' Topic: book and literature trivia'),
  gamehistory:  makeCmd('🎮', SYS.trivia + ' Topic: gaming history trivia'),
  interntrivia: makeCmd('🌐', SYS.trivia + ' Topic: internet history trivia'),
  robotics:     makeCmd('🤖', SYS.trivia + ' Topic: robotics and automation facts'),
  cryptofact2:  makeCmd('₿', SYS.trivia + ' Topic: cryptocurrency history facts'),
  aifact2:      makeCmd('🤖', SYS.trivia + ' Topic: AI and machine learning facts'),
  countrytriv:  makeCmd('🌍', SYS.trivia + ' Topic: country facts and trivia'),
  citytriv:     makeCmd('🏙️', SYS.trivia + ' Topic: famous city facts'),
  monarchytriv: makeCmd('👑', SYS.trivia + ' Topic: royal family and monarchy trivia'),
  wartriv:      makeCmd('⚔️', SYS.trivia + ' Topic: war history facts'),
  spytriv:      makeCmd('🕵️', SYS.trivia + ' Topic: espionage and spy facts'),
  crimetriv:    makeCmd('🔍', SYS.trivia + ' Topic: famous crime facts'),
  medtriv:      makeCmd('🏥', SYS.trivia + ' Topic: medical history trivia'),
  physctriv:    makeCmd('⚡', SYS.trivia + ' Topic: physics trivia'),
  chemtriv:     makeCmd('🧪', SYS.trivia + ' Topic: chemistry trivia'),
  biologytriv:  makeCmd('🧬', SYS.trivia + ' Topic: biology trivia'),

  // ── Science (50) ───────────────────────────────────────────────────────────
  quantumfact2: makeCmd('⚛️', SYS.sci + ' Explain quantum mechanics concept:'),
  relativfact:  makeCmd('🌌', SYS.sci + ' Explain relativity concept:'),
  darkmatter2:  makeCmd('🌑', SYS.sci + ' Explain dark matter in:'),
  darkenergysc: makeCmd('⚡', SYS.sci + ' Explain dark energy in:'),
  blackhole3:   makeCmd('🕳️', SYS.sci + ' Explain black hole physics:'),
  wormhole3:    makeCmd('🌀', SYS.sci + ' Explain wormholes in:'),
  multiverse2:  makeCmd('🌌', SYS.sci + ' Explain multiverse theory:'),
  stringtheory: makeCmd('〰️', SYS.sci + ' Explain string theory:'),
  darwintips:   makeCmd('🦕', SYS.sci + ' Explain evolution concept:'),
  genetics2:    makeCmd('🧬', SYS.sci + ' Explain genetics concept:'),
  crispr4:      makeCmd('✂️', SYS.sci + ' Explain CRISPR gene editing:'),
  stemcell2:    makeCmd('🔬', SYS.sci + ' Explain stem cell science:'),
  neuroplast2:  makeCmd('🧠', SYS.sci + ' Explain neuroplasticity:'),
  synapse2:     makeCmd('⚡', SYS.sci + ' Explain synapse and brain communication:'),
  microbiome2:  makeCmd('🦠', SYS.sci + ' Explain microbiome science:'),
  immunesys:    makeCmd('🛡️', SYS.sci + ' Explain immune system:'),
  epigenetics:  makeCmd('🧬', SYS.sci + ' Explain epigenetics:'),
  ecosystems:   makeCmd('🌿', SYS.sci + ' Explain ecosystem:'),
  evolution4:   makeCmd('🦕', SYS.sci + ' Explain evolutionary concept:'),
  climatesci:   makeCmd('🌡️', SYS.sci + ' Explain climate science:'),
  geologysci:   makeCmd('🗻', SYS.sci + ' Explain geology concept:'),
  tectonicsci:  makeCmd('🌍', SYS.sci + ' Explain plate tectonics:'),
  volcanosci:   makeCmd('🌋', SYS.sci + ' Explain volcano science:'),
  solarsys2:    makeCmd('🌞', SYS.sci + ' Explain solar system:'),
  astrophysics: makeCmd('🔭', SYS.sci + ' Explain astrophysics concept:'),
  thermodynamics:makeCmd('🔥', SYS.sci + ' Explain thermodynamics:'),
  electromag:   makeCmd('⚡', SYS.sci + ' Explain electromagnetism:'),
  nuclearphys:  makeCmd('⚛️', SYS.sci + ' Explain nuclear physics:'),
  particlephys: makeCmd('⚛️', SYS.sci + ' Explain particle physics:'),
  fluidmech:    makeCmd('💧', SYS.sci + ' Explain fluid mechanics:'),
  acoustics:    makeCmd('🎵', SYS.sci + ' Explain acoustics science:'),
  opticssci:    makeCmd('🔭', SYS.sci + ' Explain optics:'),
  materialssci: makeCmd('🔬', SYS.sci + ' Explain materials science:'),
  nanotechsci:  makeCmd('🔬', SYS.sci + ' Explain nanotechnology:'),
  biotech:      makeCmd('🧬', SYS.sci + ' Explain biotechnology:'),
  agrisci:      makeCmd('🌾', SYS.sci + ' Explain agricultural science:'),
  weathersci:   makeCmd('🌩️', SYS.sci + ' Explain meteorology/weather science:'),
  oceansci:     makeCmd('🌊', SYS.sci + ' Explain oceanography:'),
  envscience:   makeCmd('🌿', SYS.sci + ' Explain environmental science:'),
  roboticsci:   makeCmd('🤖', SYS.sci + ' Explain robotics science:'),
  aiscience:    makeCmd('🧠', SYS.sci + ' Explain artificial intelligence science:'),
  neurosci:     makeCmd('🧠', SYS.sci + ' Explain neuroscience concept:'),
  cognitivesci: makeCmd('💡', SYS.sci + ' Explain cognitive science:'),
  linguisticssci:makeCmd('🗣️', SYS.sci + ' Explain linguistics science:'),
  socscience:   makeCmd('👥', SYS.sci + ' Explain social science concept:'),
  econscience:  makeCmd('📊', SYS.sci + ' Explain economics science:'),
  politicalsci: makeCmd('🏛️', SYS.sci + ' Explain political science:'),
  anthroscience:makeCmd('🌍', SYS.sci + ' Explain anthropology:'),
  archaescience:makeCmd('⛏️', SYS.sci + ' Explain archaeology:'),
  archivescience:makeCmd('📜', SYS.sci + ' Explain archival science:'),
};
