'use strict';
/**
 * megapack3.js — Ultra Command Pack 3
 * 500 AI-powered commands: Social Media, Life Advice, Fitness, Leadership,
 * Crypto/Web3, Kids/Family, Weird/Absurd, Romance, Career, Spirituality
 */
const pollinations = require('../lib/pollinations');

function makeCmd(emoji, sys) {
  return async (sock, msg, args) => {
    const jid = msg.key.remoteJid;
    const topic = args.join(' ');
    if (!topic) return sock.sendMessage(jid, { text: `${emoji} _Give me a topic or question!_` }, { quoted: msg });
    await sock.sendMessage(jid, { text: `${emoji} _Processing..._` }, { quoted: msg });
    try {
      const reply = await pollinations.textGenerate([
        { role: 'system', content: sys },
        { role: 'user', content: topic },
      ]);
      await sock.sendMessage(jid, { text: `${emoji} ${reply}\n\n_⚡ DollarBot V-Ultra_` }, { quoted: msg });
    } catch (e) {
      await sock.sendMessage(jid, { text: `❌ Error: ${e.message}` }, { quoted: msg });
    }
  };
}

const SYS = {
  social: 'You are a social media growth expert. Give practical, up-to-date social media advice. WhatsApp markdown only. No tables or HTML.',
  life: 'You are a wise life coach. Give honest, practical life advice. WhatsApp markdown only. No tables or HTML.',
  fit: 'You are a certified fitness trainer. Give specific, science-based fitness advice. WhatsApp markdown only. No tables or HTML.',
  lead: 'You are an executive leadership coach. Give clear, actionable leadership advice. WhatsApp markdown only. No tables or HTML.',
  web3: 'You are a blockchain and Web3 expert. Explain crypto and Web3 concepts clearly. WhatsApp markdown only. No tables or HTML.',
  fam: 'You are a family counselor and child development expert. Give warm, practical family advice. WhatsApp markdown only. No tables or HTML.',
  weird: 'You are a creative, weird-fiction specialist. Give entertaining, imaginative, slightly absurd responses. WhatsApp markdown only.',
  romance: 'You are a romance coach. Give warm, genuine romantic advice and content. WhatsApp markdown only. No tables or HTML.',
  career: 'You are a career coach. Give practical, actionable career advice. WhatsApp markdown only. No tables or HTML.',
  spirit: 'You are a spiritual guide drawing from universal wisdom traditions. Give grounded, meaningful spiritual insights. WhatsApp markdown only.',
};

module.exports = {
  // ── Social Media (50) ──────────────────────────────────────────────────────
  twitterstrat: makeCmd('🐦', SYS.social + ' Give Twitter/X strategy tips for:'),
  instastrat2:  makeCmd('📸', SYS.social + ' Give Instagram strategy tips for:'),
  tiktokstrat2: makeCmd('🎵', SYS.social + ' Give TikTok strategy tips for:'),
  linkedinstrat2:makeCmd('💼', SYS.social + ' Give LinkedIn strategy tips for:'),
  fbstrat:      makeCmd('📘', SYS.social + ' Give Facebook strategy tips for:'),
  ytstrat:      makeCmd('▶️', SYS.social + ' Give YouTube strategy tips for:'),
  pinterestst2: makeCmd('📌', SYS.social + ' Give Pinterest strategy tips for:'),
  snapstrat:    makeCmd('👻', SYS.social + ' Give Snapchat strategy tips for:'),
  threadsstrat: makeCmd('🔀', SYS.social + ' Give Threads strategy tips for:'),
  redditstrat2: makeCmd('🟠', SYS.social + ' Give Reddit strategy tips for:'),
  discordstrat2:makeCmd('💬', SYS.social + ' Give Discord community tips for:'),
  twitchstrat2: makeCmd('💜', SYS.social + ' Give Twitch streaming tips for:'),
  contentcal2:  makeCmd('📅', SYS.social + ' Create a content calendar for:'),
  postsched2:   makeCmd('⏰', SYS.social + ' Give posting schedule tips for:'),
  hashtag4:     makeCmd('#️⃣', SYS.social + ' Give hashtag strategy for:'),
  caption4:     makeCmd('✍️', SYS.social + ' Write social media captions for:'),
  viral4:       makeCmd('🔥', SYS.social + ' Give viral content tips for:'),
  reelstip2:    makeCmd('🎬', SYS.social + ' Give Reels/Shorts tips for:'),
  storytip2:    makeCmd('📖', SYS.social + ' Give Stories tips for:'),
  carousel2:    makeCmd('🎠', SYS.social + ' Give carousel post tips for:'),
  infograph2:   makeCmd('📊', SYS.social + ' Give infographic tips for:'),
  podcast4:     makeCmd('🎙️', SYS.social + ' Give podcast growth tips for:'),
  newsletter2:  makeCmd('📧', SYS.social + ' Give newsletter growth tips for:'),
  emailmkt3:    makeCmd('📬', SYS.social + ' Give email marketing tips for:'),
  seobasic:     makeCmd('🔍', SYS.social + ' Give SEO tips for:'),
  blogstrat2:   makeCmd('✍️', SYS.social + ' Give blog strategy tips for:'),
  vlogstrat2:   makeCmd('🎥', SYS.social + ' Give vlog strategy tips for:'),
  webcopy2:     makeCmd('💻', SYS.social + ' Give website copy tips for:'),
  adcopy2:      makeCmd('📢', SYS.social + ' Give ad copy tips for:'),
  ctaguide:     makeCmd('👆', SYS.social + ' Give CTA (call-to-action) tips for:'),
  funneltip2:   makeCmd('📊', SYS.social + ' Give sales funnel tips for:'),
  analytics3:   makeCmd('📈', SYS.social + ' Give analytics tips for:'),
  growthstrat3: makeCmd('🚀', SYS.social + ' Give growth strategy for:'),
  monetize3:    makeCmd('💰', SYS.social + ' Give monetization tips for:'),
  sponsorship2: makeCmd('🤝', SYS.social + ' Give sponsorship tips for:'),
  affiliate3:   makeCmd('🔗', SYS.social + ' Give affiliate marketing tips for:'),
  merch2:       makeCmd('👕', SYS.social + ' Give merchandise tips for:'),
  brand3:       makeCmd('✨', SYS.social + ' Give personal brand tips for:'),
  ugc2:         makeCmd('👥', SYS.social + ' Give UGC (user-generated content) tips for:'),
  influencer2:  makeCmd('🌟', SYS.social + ' Give influencer tips for:'),
  microinfl2:   makeCmd('✨', SYS.social + ' Give micro-influencer tips for:'),
  collab2:      makeCmd('🤝', SYS.social + ' Give collaboration tips for:'),
  trendcap2:    makeCmd('📈', SYS.social + ' Give trend capitalization tips for:'),
  audiobuild2:  makeCmd('👥', SYS.social + ' Give audience building tips for:'),
  community2:   makeCmd('🤝', SYS.social + ' Give online community tips for:'),
  engagetip:    makeCmd('💬', SYS.social + ' Give engagement rate tips for:'),
  dmstrategy:   makeCmd('📩', SYS.social + ' Give DM/outreach strategy for:'),
  crosstmkting: makeCmd('🔄', SYS.social + ' Give cross-platform marketing tips for:'),
  paidads:      makeCmd('💰', SYS.social + ' Give paid ads tips for:'),
  retarget:     makeCmd('🎯', SYS.social + ' Give retargeting tips for:'),

  // ── Life Advice (50) ──────────────────────────────────────────────────────
  quarterlife2: makeCmd('🎯', SYS.life + ' Give quarter-life crisis advice for:'),
  midlife2:     makeCmd('🔄', SYS.life + ' Give midlife transition advice for:'),
  direction2:   makeCmd('🧭', SYS.life + ' Give life direction advice for:'),
  lifepivot:    makeCmd('🔄', SYS.life + ' Give life pivot advice for:'),
  lifereinvent: makeCmd('🦋', SYS.life + ' Give life reinvention advice for:'),
  habit4:       makeCmd('🔄', SYS.life + ' Give habit building advice for:'),
  routine3:     makeCmd('📅', SYS.life + ' Give daily routine advice for:'),
  discipline4:  makeCmd('🔒', SYS.life + ' Give discipline building advice for:'),
  consistency3: makeCmd('📅', SYS.life + ' Give consistency tips for:'),
  patience5:    makeCmd('⏳', SYS.life + ' Give patience advice for:'),
  persistence:  makeCmd('💪', SYS.life + ' Give persistence advice for:'),
  resilience5:  makeCmd('🔥', SYS.life + ' Give resilience advice for:'),
  courage3:     makeCmd('🦁', SYS.life + ' Give courage advice for:'),
  boldness:     makeCmd('⚡', SYS.life + ' Give advice on being bold about:'),
  comfort2:     makeCmd('🛋️', SYS.life + ' Give advice on leaving comfort zone for:'),
  growth3:      makeCmd('🌱', SYS.life + ' Give personal growth advice for:'),
  learning3:    makeCmd('📚', SYS.life + ' Give learning advice for:'),
  failure3:     makeCmd('💥', SYS.life + ' Give advice on dealing with failure in:'),
  mistakes3:    makeCmd('🔄', SYS.life + ' Give advice on handling mistakes in:'),
  lessons3:     makeCmd('💡', SYS.life + ' Share life lessons about:'),
  wisdom4:      makeCmd('🦉', SYS.life + ' Share wisdom about:'),
  perspective4: makeCmd('👁️', SYS.life + ' Give perspective-shifting advice on:'),
  mindopen2:    makeCmd('🔓', SYS.life + ' Give open-mindedness advice for:'),
  empathy3:     makeCmd('💛', SYS.life + ' Give empathy advice for:'),
  compassion3:  makeCmd('🕊️', SYS.life + ' Give compassion advice for:'),
  kindness3:    makeCmd('💛', SYS.life + ' Give kindness advice for:'),
  generosity2:  makeCmd('🎁', SYS.life + ' Give generosity advice for:'),
  service3:     makeCmd('🤝', SYS.life + ' Give advice on service and giving in:'),
  humility2:    makeCmd('🙏', SYS.life + ' Give humility advice for:'),
  integrity3:   makeCmd('💎', SYS.life + ' Give integrity advice for:'),
  honesty3:     makeCmd('✅', SYS.life + ' Give honesty advice for:'),
  authentic3:   makeCmd('🌟', SYS.life + ' Give authenticity advice for:'),
  vulnerable3:  makeCmd('💛', SYS.life + ' Give advice on vulnerability in:'),
  brave3:       makeCmd('🦁', SYS.life + ' Give bravery advice for:'),
  dare3:        makeCmd('🎯', SYS.life + ' Give advice on taking dares and risks in:'),
  risk3:        makeCmd('🎲', SYS.life + ' Give risk-taking advice for:'),
  chance3:      makeCmd('🍀', SYS.life + ' Give advice on taking chances in:'),
  opportunity3: makeCmd('🚪', SYS.life + ' Give advice on recognizing opportunities in:'),
  timing2:      makeCmd('⏰', SYS.life + ' Give timing advice for:'),
  trust3:       makeCmd('🔓', SYS.life + ' Give trust-building advice for:'),
  faith3:       makeCmd('✨', SYS.life + ' Give faith and belief advice for:'),
  hope2:        makeCmd('🌅', SYS.life + ' Give advice on maintaining hope in:'),
  gratitude4:   makeCmd('🙏', SYS.life + ' Give gratitude practice advice for:'),
  contentment:  makeCmd('☮️', SYS.life + ' Give contentment advice for:'),
  acceptance4:  makeCmd('🤝', SYS.life + ' Give acceptance advice for:'),
  letting go:   makeCmd('🕊️', SYS.life + ' Give letting-go advice for:'),
  simplify2:    makeCmd('🧘', SYS.life + ' Give simplifying life advice for:'),
  prioritize:   makeCmd('🎯', SYS.life + ' Give prioritization advice for:'),
  declutter:    makeCmd('✨', SYS.life + ' Give decluttering (mental/physical) advice for:'),
  clarity:      makeCmd('💡', SYS.life + ' Give mental clarity advice for:'),

  // ── Fitness (50) ──────────────────────────────────────────────────────────
  pushuptip:    makeCmd('💪', SYS.fit + ' Give push-up training tips for:'),
  pulluptip:    makeCmd('💪', SYS.fit + ' Give pull-up training tips for:'),
  squattip:     makeCmd('🦵', SYS.fit + ' Give squat technique tips for:'),
  deadlifttip:  makeCmd('🏋️', SYS.fit + ' Give deadlift technique tips for:'),
  benchpresstip:makeCmd('🏋️', SYS.fit + ' Give bench press tips for:'),
  ohpresstip:   makeCmd('🏋️', SYS.fit + ' Give overhead press tips for:'),
  rowtip:       makeCmd('🏋️', SYS.fit + ' Give rowing exercise tips for:'),
  lungetip:     makeCmd('🦵', SYS.fit + ' Give lunge exercise tips for:'),
  planktip:     makeCmd('💪', SYS.fit + ' Give plank exercise tips for:'),
  coretip:      makeCmd('💪', SYS.fit + ' Give core training tips for:'),
  burpeetip:    makeCmd('⚡', SYS.fit + ' Give burpee tips for:'),
  boxjumptip:   makeCmd('📦', SYS.fit + ' Give box jump tips for:'),
  resistband:   makeCmd('🪢', SYS.fit + ' Give resistance band workout tips for:'),
  homeworkout:  makeCmd('🏠', SYS.fit + ' Give home workout tips for:'),
  gymbegin:     makeCmd('🏋️', SYS.fit + ' Give gym beginner tips for:'),
  gymadvance:   makeCmd('🏆', SYS.fit + ' Give advanced gym tips for:'),
  bodyweight:   makeCmd('🤸', SYS.fit + ' Give bodyweight workout tips for:'),
  funcfitness2: makeCmd('⚡', SYS.fit + ' Give functional fitness tips for:'),
  sporttrain2:  makeCmd('🏃', SYS.fit + ' Give sport-specific training tips for:'),
  powerdev2:    makeCmd('⚡', SYS.fit + ' Give power development tips for:'),
  explosive:    makeCmd('💥', SYS.fit + ' Give explosive training tips for:'),
  agility2:     makeCmd('🏃', SYS.fit + ' Give agility training tips for:'),
  coordination2:makeCmd('🎯', SYS.fit + ' Give coordination tips for:'),
  balance4:     makeCmd('⚖️', SYS.fit + ' Give balance training tips for:'),
  endurance3:   makeCmd('🏃', SYS.fit + ' Give endurance training tips for:'),
  stamina2:     makeCmd('💪', SYS.fit + ' Give stamina building tips for:'),
  warmuptip:    makeCmd('🔥', SYS.fit + ' Give warm-up tips for:'),
  cooldowntip:  makeCmd('❄️', SYS.fit + ' Give cool-down tips for:'),
  proteintip:   makeCmd('🥩', SYS.fit + ' Give protein intake tips for:'),
  preworkout:   makeCmd('⚡', SYS.fit + ' Give pre-workout nutrition tips for:'),
  postworkout:  makeCmd('🥤', SYS.fit + ' Give post-workout nutrition tips for:'),
  suppguide:    makeCmd('💊', SYS.fit + ' Give supplement guidance for:'),
  creatine:     makeCmd('⚡', SYS.fit + ' Explain creatine for:'),
  proteintypes: makeCmd('🥩', SYS.fit + ' Explain protein types for:'),
  musclegrp:    makeCmd('💪', SYS.fit + ' Give targeted muscle group tips for:'),
  splitworkout: makeCmd('📋', SYS.fit + ' Design a workout split for:'),
  periodize:    makeCmd('📅', SYS.fit + ' Explain periodization for:'),
  deload:       makeCmd('🔄', SYS.fit + ' Explain deload week for:'),
  progressivo:  makeCmd('📈', SYS.fit + ' Explain progressive overload for:'),
  formtip:      makeCmd('✅', SYS.fit + ' Give exercise form tips for:'),
  injrecov:     makeCmd('🩹', SYS.fit + ' Give injury recovery tips for:'),
  rehab2:       makeCmd('🏥', SYS.fit + ' Give rehabilitation exercise tips for:'),
  flexibilityt: makeCmd('🧘', SYS.fit + ' Give flexibility training tips for:'),
  mobilityexc:  makeCmd('🦵', SYS.fit + ' Give mobility exercises for:'),
  fitgoals:     makeCmd('🎯', SYS.fit + ' Help set fitness goals for:'),
  fitplanning:  makeCmd('📅', SYS.fit + ' Create a fitness plan for:'),
  fitroutine:   makeCmd('🔄', SYS.fit + ' Create a fitness routine for:'),
  fitprogress:  makeCmd('📊', SYS.fit + ' Give fitness progress tracking tips for:'),
  fitmotivate:  makeCmd('🔥', SYS.fit + ' Give fitness motivation tips for:'),
  fitlifestyle: makeCmd('🌟', SYS.fit + ' Give active lifestyle tips for:'),

  // ── Leadership (50) ───────────────────────────────────────────────────────
  leadstyle2:   makeCmd('👑', SYS.lead + ' Explain leadership style:'),
  servlead2:    makeCmd('🤝', SYS.lead + ' Explain servant leadership for:'),
  translead:    makeCmd('⚡', SYS.lead + ' Explain transformational leadership for:'),
  situationlead:makeCmd('🎯', SYS.lead + ' Explain situational leadership for:'),
  adaptlead2:   makeCmd('🔄', SYS.lead + ' Give adaptive leadership tips for:'),
  emotionald:   makeCmd('💛', SYS.lead + ' Give emotional leadership tips for:'),
  vision4:      makeCmd('🔭', SYS.lead + ' Give vision-setting tips for:'),
  innovation3:  makeCmd('💡', SYS.lead + ' Give innovation leadership tips for:'),
  creatlead2:   makeCmd('🎨', SYS.lead + ' Give creative leadership tips for:'),
  teamcollab:   makeCmd('👥', SYS.lead + ' Give team collaboration tips for:'),
  trust4:       makeCmd('🔓', SYS.lead + ' Give trust-building leadership tips for:'),
  psysafety:    makeCmd('🛡️', SYS.lead + ' Explain psychological safety for:'),
  teamdynamic:  makeCmd('⚡', SYS.lead + ' Give team dynamics advice for:'),
  diversinclus: makeCmd('🌈', SYS.lead + ' Give diversity and inclusion tips for:'),
  empower2:     makeCmd('💪', SYS.lead + ' Give empowerment leadership tips for:'),
  delegatecmd:  makeCmd('🤝', SYS.lead + ' Give delegation advice for:'),
  feedbacklead: makeCmd('💬', SYS.lead + ' Give feedback-giving tips for:'),
  coaching4:    makeCmd('🎯', SYS.lead + ' Give coaching leadership tips for:'),
  mentorlead:   makeCmd('🎓', SYS.lead + ' Give mentoring leadership tips for:'),
  champchange:  makeCmd('⚡', SYS.lead + ' Give change champion tips for:'),
  changemgt2:   makeCmd('🔄', SYS.lead + ' Give change management tips for:'),
  culturebuild: makeCmd('🌟', SYS.lead + ' Give culture building tips for:'),
  motivation4:  makeCmd('🔥', SYS.lead + ' Give team motivation tips for:'),
  recognition2: makeCmd('🏆', SYS.lead + ' Give recognition and reward tips for:'),
  accountability3:makeCmd('✅', SYS.lead + ' Give accountability leadership tips for:'),
  ownership2:   makeCmd('🔑', SYS.lead + ' Give ownership culture tips for:'),
  decismaking2: makeCmd('🎯', SYS.lead + ' Give decision-making tips for:'),
  problemlead:  makeCmd('🔍', SYS.lead + ' Give problem-solving leadership tips for:'),
  conflictlead: makeCmd('⚡', SYS.lead + ' Give conflict resolution leadership tips for:'),
  negotiat3:    makeCmd('🤝', SYS.lead + ' Give negotiation leadership tips for:'),
  influence4:   makeCmd('✨', SYS.lead + ' Give influence and persuasion tips for:'),
  storytell3:   makeCmd('📖', SYS.lead + ' Give leadership storytelling tips for:'),
  visionset:    makeCmd('🔭', SYS.lead + ' Give vision-setting tips for:'),
  mission3:     makeCmd('🎯', SYS.lead + ' Give mission-defining tips for:'),
  strategy4:    makeCmd('♟️', SYS.lead + ' Give leadership strategy tips for:'),
  execution3:   makeCmd('✅', SYS.lead + ' Give execution and delivery tips for:'),
  alignment3:   makeCmd('🎯', SYS.lead + ' Give team alignment tips for:'),
  measurement3: makeCmd('📊', SYS.lead + ' Give metrics and measurement tips for:'),
  iteration2:   makeCmd('🔄', SYS.lead + ' Give iterative improvement tips for:'),
  agile3:       makeCmd('⚡', SYS.lead + ' Give agile leadership tips for:'),
  scrum3:       makeCmd('🔄', SYS.lead + ' Give Scrum framework tips for:'),
  kanban3:      makeCmd('📋', SYS.lead + ' Give Kanban method tips for:'),
  firsttimelead:makeCmd('🌱', SYS.lead + ' Give first-time leader tips for:'),
  exec2:        makeCmd('👔', SYS.lead + ' Give executive leadership tips for:'),
  boardlead:    makeCmd('🏛️', SYS.lead + ' Give board-level leadership tips for:'),
  startuplead:  makeCmd('🚀', SYS.lead + ' Give startup leadership tips for:'),
  remotelead:   makeCmd('💻', SYS.lead + ' Give remote team leadership tips for:'),
  crisisleader: makeCmd('🚨', SYS.lead + ' Give crisis leadership tips for:'),
  futurelead:   makeCmd('🔮', SYS.lead + ' Give future leadership tips for:'),
  leadlegacy:   makeCmd('🏆', SYS.lead + ' Give leadership legacy tips for:'),

  // ── Crypto / Web3 (50) ────────────────────────────────────────────────────
  blockchain4:  makeCmd('⛓️', SYS.web3 + ' Explain blockchain concept:'),
  distributed2: makeCmd('🌐', SYS.web3 + ' Explain distributed systems in Web3:'),
  decentraliz: makeCmd('🔓', SYS.web3 + ' Explain decentralization:'),
  consensus2:   makeCmd('✅', SYS.web3 + ' Explain consensus mechanisms:'),
  proofwork2:   makeCmd('⛏️', SYS.web3 + ' Explain Proof of Work:'),
  proofstake2:  makeCmd('🔐', SYS.web3 + ' Explain Proof of Stake:'),
  validator2:   makeCmd('✅', SYS.web3 + ' Explain blockchain validators:'),
  nodes:        makeCmd('🌐', SYS.web3 + ' Explain blockchain nodes:'),
  mining3:      makeCmd('⛏️', SYS.web3 + ' Explain crypto mining:'),
  wallets3:     makeCmd('👛', SYS.web3 + ' Explain crypto wallets:'),
  seedphrase:   makeCmd('🔐', SYS.web3 + ' Explain seed phrases and security:'),
  privatekey2:  makeCmd('🔑', SYS.web3 + ' Explain private keys:'),
  publickey2:   makeCmd('🔓', SYS.web3 + ' Explain public keys:'),
  transaction3: makeCmd('📤', SYS.web3 + ' Explain blockchain transactions:'),
  block3:       makeCmd('🧱', SYS.web3 + ' Explain blocks in blockchain:'),
  hash3:        makeCmd('🔐', SYS.web3 + ' Explain cryptographic hashing:'),
  merkle2:      makeCmd('🌳', SYS.web3 + ' Explain Merkle trees:'),
  smartcon3:    makeCmd('📜', SYS.web3 + ' Explain smart contracts:'),
  evm2:         makeCmd('⚙️', SYS.web3 + ' Explain EVM (Ethereum Virtual Machine):'),
  solidity2:    makeCmd('🔷', SYS.web3 + ' Give Solidity programming tips for:'),
  defi5:        makeCmd('🔗', SYS.web3 + ' Explain DeFi concept:'),
  amm2:         makeCmd('🔄', SYS.web3 + ' Explain Automated Market Makers:'),
  liquidity3:   makeCmd('💧', SYS.web3 + ' Explain liquidity in DeFi:'),
  yield3:       makeCmd('📈', SYS.web3 + ' Explain yield farming:'),
  staking3:     makeCmd('🔒', SYS.web3 + ' Explain crypto staking:'),
  farm3:        makeCmd('🌾', SYS.web3 + ' Explain yield farming strategies:'),
  pool3:        makeCmd('💧', SYS.web3 + ' Explain liquidity pools:'),
  bridge3:      makeCmd('🌉', SYS.web3 + ' Explain cross-chain bridges:'),
  oracle3:      makeCmd('🔮', SYS.web3 + ' Explain blockchain oracles:'),
  dao3:         makeCmd('🏛️', SYS.web3 + ' Explain DAOs:'),
  governance3:  makeCmd('⚖️', SYS.web3 + ' Explain blockchain governance:'),
  token3:       makeCmd('🪙', SYS.web3 + ' Explain token economics:'),
  nft4:         makeCmd('🖼️', SYS.web3 + ' Explain NFTs:'),
  metaverse3:   makeCmd('🌐', SYS.web3 + ' Explain metaverse concept:'),
  web3social2:  makeCmd('👥', SYS.web3 + ' Explain Web3 social platforms:'),
  sbt2:         makeCmd('🏆', SYS.web3 + ' Explain Soulbound Tokens:'),
  did3:         makeCmd('🆔', SYS.web3 + ' Explain decentralized identity:'),
  privacy3:     makeCmd('🔐', SYS.web3 + ' Explain blockchain privacy:'),
  scalability:  makeCmd('📈', SYS.web3 + ' Explain blockchain scalability:'),
  layer2:       makeCmd('⬆️', SYS.web3 + ' Explain Layer 2 solutions:'),
  sidechain:    makeCmd('🔗', SYS.web3 + ' Explain sidechains:'),
  rollups:      makeCmd('🔄', SYS.web3 + ' Explain rollup technology:'),
  zeroknowled:  makeCmd('🔐', SYS.web3 + ' Explain zero-knowledge proofs:'),
  tokenomics:   makeCmd('📊', SYS.web3 + ' Explain tokenomics for:'),
  whitepaper:   makeCmd('📄', SYS.web3 + ' Explain how to read a whitepaper:'),
  cryptowallet: makeCmd('👛', SYS.web3 + ' Give crypto wallet security tips:'),
  defirisks:    makeCmd('⚠️', SYS.web3 + ' Explain DeFi risks for:'),
  cryptotax:    makeCmd('🏦', SYS.web3 + ' Explain crypto tax basics:'),
  cryptoport:   makeCmd('📊', SYS.web3 + ' Give crypto portfolio tips:'),
  altcoin3:     makeCmd('🪙', SYS.web3 + ' Analyze altcoin:'),
  nftart:       makeCmd('🎨', SYS.web3 + ' Explain NFT art and market:'),

  // ── Kids / Family (50) ────────────────────────────────────────────────────
  parenttip3:   makeCmd('👨‍👩‍👧', SYS.fam + ' Give parenting tips for:'),
  kidsdev2:     makeCmd('🌱', SYS.fam + ' Give child development advice for:'),
  toddlertip:   makeCmd('👶', SYS.fam + ' Give toddler parenting tips for:'),
  preschool2:   makeCmd('🧒', SYS.fam + ' Give preschool age parenting tips for:'),
  elementaryp:  makeCmd('📚', SYS.fam + ' Give elementary school tips for:'),
  teenparent:   makeCmd('🧒', SYS.fam + ' Give teen parenting tips for:'),
  adulting2:    makeCmd('🎓', SYS.fam + ' Give adulting advice for:'),
  firstjob3:    makeCmd('💼', SYS.fam + ' Give first job advice for:'),
  movingout3:   makeCmd('🏠', SYS.fam + ' Give moving out advice for:'),
  independence: makeCmd('🗝️', SYS.fam + ' Give independence advice for:'),
  chores2:      makeCmd('🧹', SYS.fam + ' Give chore management tips for:'),
  allowance2:   makeCmd('💰', SYS.fam + ' Give allowance and money teaching tips for:'),
  kidsfinance:  makeCmd('💰', SYS.fam + ' Give financial education tips for kids about:'),
  kidsstory3:   makeCmd('📖', SYS.fam + ' Tell a children\'s story about:'),
  bedtimerec3:  makeCmd('🌙', SYS.fam + ' Give bedtime routine tips for:'),
  cartoon3:     makeCmd('🎨', SYS.fam + ' Recommend cartoons for:'),
  educgame2:    makeCmd('🎮', SYS.fam + ' Suggest educational games for:'),
  kidsapp2:     makeCmd('📱', SYS.fam + ' Suggest educational apps for:'),
  screentip2:   makeCmd('📺', SYS.fam + ' Give screen time tips for:'),
  outdooract2:  makeCmd('🌿', SYS.fam + ' Suggest outdoor activities for:'),
  familygame2:  makeCmd('🎲', SYS.fam + ' Suggest family game ideas for:'),
  dinnerconv2:  makeCmd('🍽️', SYS.fam + ' Suggest dinner conversation topics for:'),
  familymeet2:  makeCmd('📋', SYS.fam + ' Give family meeting tips for:'),
  vacationfam:  makeCmd('✈️', SYS.fam + ' Give family vacation tips for:'),
  holiday4:     makeCmd('🎉', SYS.fam + ' Give family holiday tips for:'),
  birthday4:    makeCmd('🎂', SYS.fam + ' Give birthday party tips for:'),
  tradition2:   makeCmd('🌟', SYS.fam + ' Give family tradition ideas for:'),
  ritual3:      makeCmd('🕯️', SYS.fam + ' Give family ritual ideas for:'),
  celebrate3:   makeCmd('🎉', SYS.fam + ' Give celebration tips for:'),
  memorycreate: makeCmd('📸', SYS.fam + ' Give tips on creating family memories for:'),
  familyval2:   makeCmd('💎', SYS.fam + ' Give family values tips for:'),
  teachkids2:   makeCmd('📚', SYS.fam + ' Give tips on teaching kids about:'),
  communicfam:  makeCmd('💬', SYS.fam + ' Give family communication tips for:'),
  listenkids:   makeCmd('👂', SYS.fam + ' Give tips on listening to children about:'),
  boundfam:     makeCmd('🛑', SYS.fam + ' Give family boundaries tips for:'),
  discifam:     makeCmd('✅', SYS.fam + ' Give positive discipline tips for:'),
  lovekids2:    makeCmd('💛', SYS.fam + ' Give advice on expressing love to kids:'),
  attachsec:    makeCmd('🔗', SYS.fam + ' Give attachment parenting tips for:'),
  emotionkids:  makeCmd('💛', SYS.fam + ' Give emotional intelligence tips for kids:'),
  empathkids2:  makeCmd('🤝', SYS.fam + ' Give empathy-building tips for kids:'),
  gratidekids:  makeCmd('🙏', SYS.fam + ' Give gratitude practice tips for kids:'),
  resiliencekid:makeCmd('💪', SYS.fam + ' Give resilience-building tips for kids:'),
  conflictkids: makeCmd('🤝', SYS.fam + ' Give conflict resolution tips for kids:'),
  bully3:       makeCmd('🛡️', SYS.fam + ' Give advice on dealing with bullying:'),
  friendkids:   makeCmd('👫', SYS.fam + ' Give tips on helping kids make friends:'),
  socskillskid: makeCmd('🤝', SYS.fam + ' Give social skills tips for kids:'),
  neurodiverse: makeCmd('🧠', SYS.fam + ' Give neurodiverse parenting tips for:'),
  adhd:         makeCmd('⚡', SYS.fam + ' Give ADHD parenting tips for:'),
  anxietykids:  makeCmd('😰', SYS.fam + ' Give anxiety support tips for kids:'),

  // ── Weird / Absurd (50) ───────────────────────────────────────────────────
  backrooms3:   makeCmd('🚪', SYS.weird + ' Describe a new Backrooms level about:'),
  liminalstory: makeCmd('🌀', SYS.weird + ' Write a liminal space horror story about:'),
  dreamlogic:   makeCmd('💭', SYS.weird + ' Write a dream-logic narrative about:'),
  weirdcore2:   makeCmd('✨', SYS.weird + ' Create a weirdcore aesthetic scenario for:'),
  dreamcore2:   makeCmd('🌙', SYS.weird + ' Create a dreamcore story about:'),
  vaporwcore:   makeCmd('🌴', SYS.weird + ' Create a vaporwave story about:'),
  alter3:       makeCmd('🔄', SYS.weird + ' Create an alternate reality version of:'),
  glitch3:      makeCmd('⚡', SYS.weird + ' Write a reality glitch story about:'),
  timelooptxt:  makeCmd('⏰', SYS.weird + ' Write a time loop narrative about:'),
  paradox3:     makeCmd('🌀', SYS.weird + ' Describe a paradox scenario about:'),
  simulatism:   makeCmd('💻', SYS.weird + ' Write a simulation theory story about:'),
  brainjar:     makeCmd('🧠', SYS.weird + ' Write a brain-in-a-jar philosophical scenario about:'),
  solipsism2:   makeCmd('👁️', SYS.weird + ' Write a solipsism story about:'),
  void3:        makeCmd('⬛', SYS.weird + ' Describe the void in context of:'),
  infinregress: makeCmd('∞', SYS.weird + ' Describe infinite regress for:'),
  strangeloop2: makeCmd('🔄', SYS.weird + ' Write a strange loop narrative about:'),
  godelstory:   makeCmd('🔮', SYS.weird + ' Write a Gödel incompleteness story about:'),
  haltingprob:  makeCmd('🛑', SYS.weird + ' Describe the halting problem as a story about:'),
  paperclipmx:  makeCmd('📎', SYS.weird + ' Write a paperclip maximizer AI story about:'),
  aipocalypse:  makeCmd('🤖', SYS.weird + ' Write a darkly comedic AI apocalypse about:'),
  aliencontact: makeCmd('👽', SYS.weird + ' Write a first alien contact story about:'),
  fermiparadox: makeCmd('🌌', SYS.weird + ' Explore the Fermi Paradox in context of:'),
  darkforest:   makeCmd('🌑', SYS.weird + ' Write a Dark Forest theory scenario about:'),
  boltzmann:    makeCmd('🧠', SYS.weird + ' Write a Boltzmann brain scenario about:'),
  multivworld:  makeCmd('🌌', SYS.weird + ' Describe a multiverse where:'),
  quantumhell:  makeCmd('⚛️', SYS.weird + ' Describe the quantum horror of:'),
  mandelaworld: makeCmd('🔄', SYS.weird + ' Describe an alternate Mandela Effect world where:'),
  cursedobj:    makeCmd('😈', SYS.weird + ' Write a cursed object story about:'),
  horrormonste: makeCmd('👾', SYS.weird + ' Create a horror monster based on:'),
  scpnew:       makeCmd('📋', SYS.weird + ' Write a new SCP entry about:'),
  anomaly2:     makeCmd('⚠️', SYS.weird + ' Describe an anomalous entity related to:'),
  eldritch:     makeCmd('🌑', SYS.weird + ' Write Eldritch horror about:'),
  cosmichorror: makeCmd('🌌', SYS.weird + ' Write cosmic horror about:'),
  lovecraftian: makeCmd('📜', SYS.weird + ' Write Lovecraftian horror about:'),
  existhorror:  makeCmd('😱', SYS.weird + ' Write existential horror about:'),
  bodyhorror:   makeCmd('💀', SYS.weird + ' Write body horror about:'),
  psychhorror:  makeCmd('🧠', SYS.weird + ' Write psychological horror about:'),
  numbstation:  makeCmd('📻', SYS.weird + ' Write a numbers station transmission about:'),
  cryptictxt:   makeCmd('🔐', SYS.weird + ' Write cryptic mysterious text about:'),
  analog3:      makeCmd('📺', SYS.weird + ' Write an analog horror story about:'),
  corruptmem:   makeCmd('💻', SYS.weird + ' Write a corrupted memory narrative about:'),
  deepweb2:     makeCmd('🌑', SYS.weird + ' Write a fictional deep web story about:'),
  errorpage:    makeCmd('❌', SYS.weird + ' Write an ominous error message story about:'),
  redroom:      makeCmd('🔴', SYS.weird + ' Write a red room style story about:'),
  fourthwall:   makeCmd('🎭', SYS.weird + ' Break the fourth wall in a story about:'),
  metahorror:   makeCmd('📱', SYS.weird + ' Write meta-horror about:'),
  truebackroom: makeCmd('🚪', SYS.weird + ' Write a noclip story about:'),
  glitchentity: makeCmd('⚡', SYS.weird + ' Create a glitch entity for:'),
  scpclassify:  makeCmd('📋', SYS.weird + ' Classify a new anomaly in context of:'),
  creepysound:  makeCmd('🔊', SYS.weird + ' Describe a creepy sound phenomenon about:'),

  // ── Romance (50) ──────────────────────────────────────────────────────────
  lovelang3:    makeCmd('💕', SYS.romance + ' Explain the love language of:'),
  qualtime3:    makeCmd('⏰', SYS.romance + ' Give quality time date ideas for:'),
  wordsaffirm2: makeCmd('💬', SYS.romance + ' Write words of affirmation for:'),
  actservice:   makeCmd('🤝', SYS.romance + ' Give acts of service ideas for:'),
  receivegift:  makeCmd('🎁', SYS.romance + ' Give thoughtful gift ideas for:'),
  phystouch2:   makeCmd('🤗', SYS.romance + ' Give physical touch romance tips for:'),
  attractionsc2:makeCmd('✨', SYS.romance + ' Explain attraction dynamics for:'),
  chemistry3:   makeCmd('⚗️', SYS.romance + ' Describe romantic chemistry in:'),
  firstkiss2:   makeCmd('💋', SYS.romance + ' Give romantic first kiss advice for:'),
  anniversarytips:makeCmd('🎉', SYS.romance + ' Give anniversary ideas for:'),
  propose3:     makeCmd('💍', SYS.romance + ' Give proposal tips for:'),
  romantic3:    makeCmd('🌹', SYS.romance + ' Give romantic gesture ideas for:'),
  surpriseplnn: makeCmd('🎉', SYS.romance + ' Give surprise planning tips for:'),
  datenight3:   makeCmd('🌙', SYS.romance + ' Plan a date night for:'),
  daydateplan:  makeCmd('☀️', SYS.romance + ' Plan a day date for:'),
  staycation3:  makeCmd('🏠', SYS.romance + ' Plan a romantic staycation for:'),
  spontaneous3: makeCmd('⚡', SYS.romance + ' Give spontaneous romance tips for:'),
  adventdate:   makeCmd('🗺️', SYS.romance + ' Plan an adventure date for:'),
  homecook3:    makeCmd('🍽️', SYS.romance + ' Give romantic home cooking tips for:'),
  coupletrav2:  makeCmd('✈️', SYS.romance + ' Give romantic travel tips for:'),
  sexchem:      makeCmd('🔥', SYS.romance + ' Give romantic chemistry tips for:'),
  intimacy3:    makeCmd('💛', SYS.romance + ' Give emotional intimacy tips for:'),
  sensuality2:  makeCmd('🌹', SYS.romance + ' Give sensuality advice for:'),
  seduction3:   makeCmd('😏', SYS.romance + ' Give romantic seduction tips for:'),
  flirt5:       makeCmd('😘', SYS.romance + ' Give romantic flirting tips for:'),
  textrule3:    makeCmd('📱', SYS.romance + ' Give romantic texting tips for:'),
  deepconv3:    makeCmd('💬', SYS.romance + ' Suggest deep couple conversation topics for:'),
  vulnlove:     makeCmd('💛', SYS.romance + ' Give vulnerability in love tips for:'),
  rawlove:      makeCmd('❤️', SYS.romance + ' Describe what raw, honest love looks like in:'),
  uncondit2:    makeCmd('💞', SYS.romance + ' Describe unconditional love in:'),
  devot:        makeCmd('🙏', SYS.romance + ' Write romantic devotion content for:'),
  passionlove:  makeCmd('🔥', SYS.romance + ' Give passionate love tips for:'),
  maintenance:  makeCmd('🔧', SYS.romance + ' Give relationship maintenance tips for:'),
  growcouple:   makeCmd('🌱', SYS.romance + ' Give growing together advice for:'),
  futurecouple: makeCmd('🔮', SYS.romance + ' Give future planning advice for couples:'),
  marriagetips: makeCmd('💒', SYS.romance + ' Give marriage success tips for:'),
  renewvows:    makeCmd('💍', SYS.romance + ' Give vow renewal tips for:'),
  lovepoem:     makeCmd('📜', SYS.romance + ' Write a love poem for:'),
  loveletter:   makeCmd('💌', SYS.romance + ' Write a love letter for:'),
  valentinetip: makeCmd('💝', SYS.romance + ' Give Valentine\'s Day ideas for:'),
  monthlover:   makeCmd('📅', SYS.romance + ' Give monthly romance tips for:'),
  dailylove:    makeCmd('💛', SYS.romance + ' Give daily love tips for:'),
  trustlove:    makeCmd('🔓', SYS.romance + ' Give trust-building love tips for:'),
  honestylove:  makeCmd('✅', SYS.romance + ' Give honesty in love advice for:'),
  forgiveness2: makeCmd('🕊️', SYS.romance + ' Give forgiveness in love advice for:'),
  communiclove: makeCmd('💬', SYS.romance + ' Give communication tips for couples:'),
  conflictlove: makeCmd('⚡', SYS.romance + ' Give conflict resolution tips for couples:'),
  reconnectlv:  makeCmd('🔄', SYS.romance + ' Give reconnection tips for couples:'),
  futurevision: makeCmd('🔭', SYS.romance + ' Help create a shared future vision for:'),
  soulconx2:    makeCmd('🌌', SYS.romance + ' Describe a deep soul connection about:'),

  // ── Career (50) ───────────────────────────────────────────────────────────
  resume5:      makeCmd('📄', SYS.career + ' Give resume tips for:'),
  coverltr3:    makeCmd('📧', SYS.career + ' Give cover letter tips for:'),
  linkedin3:    makeCmd('💼', SYS.career + ' Give LinkedIn profile tips for:'),
  network4:     makeCmd('🌐', SYS.career + ' Give networking tips for:'),
  reachout2:    makeCmd('📤', SYS.career + ' Give professional outreach tips for:'),
  coldmsg2:     makeCmd('📩', SYS.career + ' Give cold messaging tips for:'),
  informinterv: makeCmd('☕', SYS.career + ' Give informational interview tips for:'),
  referral3:    makeCmd('🤝', SYS.career + ' Give referral strategy tips for:'),
  intervprep3:  makeCmd('🎯', SYS.career + ' Give interview prep tips for:'),
  behavioralq2: makeCmd('💬', SYS.career + ' Answer behavioral interview question:'),
  star2:        makeCmd('⭐', SYS.career + ' Help structure a STAR method answer for:'),
  casestudy2:   makeCmd('📋', SYS.career + ' Give case study tips for:'),
  techintervtip:makeCmd('💻', SYS.career + ' Give technical interview tips for:'),
  systemdesgn2: makeCmd('🏗️', SYS.career + ' Give system design interview tips for:'),
  onsitetip:    makeCmd('🏢', SYS.career + ' Give on-site interview tips for:'),
  offernego3:   makeCmd('💰', SYS.career + ' Give offer negotiation tips for:'),
  counteroff2:  makeCmd('🔄', SYS.career + ' Give counter-offer advice for:'),
  benpackage2:  makeCmd('📦', SYS.career + ' Give benefits package evaluation tips for:'),
  equity3:      makeCmd('📊', SYS.career + ' Give equity/stock option evaluation tips for:'),
  vesting2:     makeCmd('⏱️', SYS.career + ' Explain vesting schedule for:'),
  startupvscorp:makeCmd('⚖️', SYS.career + ' Compare startup vs corporate for:'),
  remotejob3:   makeCmd('💻', SYS.career + ' Give remote job tips for:'),
  hybridwork:   makeCmd('🏠', SYS.career + ' Give hybrid work tips for:'),
  sidegig2:     makeCmd('💡', SYS.career + ' Give side gig tips for:'),
  freelance5:   makeCmd('💼', SYS.career + ' Give freelancing tips for:'),
  consultant3:  makeCmd('🎯', SYS.career + ' Give consulting tips for:'),
  transition3:  makeCmd('🔄', SYS.career + ' Give career transition tips for:'),
  industswitch: makeCmd('🔄', SYS.career + ' Give industry switch tips for:'),
  skillup:      makeCmd('📈', SYS.career + ' Give skill-building tips for:'),
  levelup2:     makeCmd('⬆️', SYS.career + ' Give career level-up tips for:'),
  promotion3:   makeCmd('🏆', SYS.career + ' Give promotion tips for:'),
  executpath:   makeCmd('👔', SYS.career + ' Give executive career path tips for:'),
  founder3:     makeCmd('🚀', SYS.career + ' Give founder/entrepreneur tips for:'),
  cofounder2:   makeCmd('🤝', SYS.career + ' Give co-founder tips for:'),
  firstjob4:    makeCmd('🌱', SYS.career + ' Give first job tips for:'),
  earlycareer:  makeCmd('🌱', SYS.career + ' Give early career tips for:'),
  midcareer:    makeCmd('📈', SYS.career + ' Give mid-career tips for:'),
  latecareer:   makeCmd('🏆', SYS.career + ' Give late-career tips for:'),
  retire3:      makeCmd('🏖️', SYS.career + ' Give career retirement planning tips for:'),
  portfol3:     makeCmd('💼', SYS.career + ' Give professional portfolio tips for:'),
  onlinepres:   makeCmd('🌐', SYS.career + ' Give online presence tips for:'),
  thoughtlead:  makeCmd('💡', SYS.career + ' Give thought leadership tips for:'),
  pubspeak2:    makeCmd('🎤', SYS.career + ' Give public speaking career tips for:'),
  writcareer:   makeCmd('✍️', SYS.career + ' Give writing career tips for:'),
  mediacareer:  makeCmd('🎬', SYS.career + ' Give media career tips for:'),
  techcareer:   makeCmd('💻', SYS.career + ' Give tech career tips for:'),
  creativecar:  makeCmd('🎨', SYS.career + ' Give creative career tips for:'),
  healthcareer: makeCmd('🏥', SYS.career + ' Give healthcare career tips for:'),
  lawcareer:    makeCmd('⚖️', SYS.career + ' Give law career tips for:'),
  financecar:   makeCmd('💰', SYS.career + ' Give finance career tips for:'),

  // ── Spirituality (50) ─────────────────────────────────────────────────────
  chakra3:      makeCmd('🌈', SYS.spirit + ' Explain chakra:'),
  rootchakra:   makeCmd('🔴', SYS.spirit + ' Explain root chakra for:'),
  sacralchakra: makeCmd('🟠', SYS.spirit + ' Explain sacral chakra for:'),
  solarchakra:  makeCmd('🟡', SYS.spirit + ' Explain solar plexus chakra for:'),
  heartchakra:  makeCmd('💚', SYS.spirit + ' Explain heart chakra for:'),
  throatchakra: makeCmd('🔵', SYS.spirit + ' Explain throat chakra for:'),
  thirdeyechk:  makeCmd('💜', SYS.spirit + ' Explain third eye chakra for:'),
  crownchakra:  makeCmd('⚪', SYS.spirit + ' Explain crown chakra for:'),
  kundalini2:   makeCmd('🌀', SYS.spirit + ' Explain kundalini energy:'),
  aura3:        makeCmd('✨', SYS.spirit + ' Explain aura and energy field:'),
  energyheal2:  makeCmd('🙌', SYS.spirit + ' Explain energy healing for:'),
  reiki3:       makeCmd('🙌', SYS.spirit + ' Explain Reiki healing for:'),
  crystalh:     makeCmd('💎', SYS.spirit + ' Explain crystal healing for:'),
  moonphase2:   makeCmd('🌙', SYS.spirit + ' Explain moon phase energy for:'),
  fullmoon2:    makeCmd('🌕', SYS.spirit + ' Explain full moon rituals for:'),
  newmoon2:     makeCmd('🌑', SYS.spirit + ' Explain new moon rituals for:'),
  mercuryret:   makeCmd('☿', SYS.spirit + ' Explain Mercury retrograde for:'),
  natal2:       makeCmd('⭐', SYS.spirit + ' Explain natal chart for:'),
  risingsign:   makeCmd('⬆️', SYS.spirit + ' Explain rising sign:'),
  sunsign:      makeCmd('☀️', SYS.spirit + ' Explain sun sign:'),
  moonsign:     makeCmd('🌙', SYS.spirit + ' Explain moon sign:'),
  saturnreturn: makeCmd('🪐', SYS.spirit + ' Explain Saturn return:'),
  venussign:    makeCmd('♀️', SYS.spirit + ' Explain Venus in astrology:'),
  marssign:     makeCmd('♂️', SYS.spirit + ' Explain Mars in astrology:'),
  jupitersgn:   makeCmd('⚡', SYS.spirit + ' Explain Jupiter in astrology:'),
  tarot4:       makeCmd('🃏', SYS.spirit + ' Give a tarot reading for:'),
  majorarcana:  makeCmd('🔮', SYS.spirit + ' Explain Major Arcana card:'),
  minorarcana:  makeCmd('🃏', SYS.spirit + ' Explain Minor Arcana card:'),
  tarotread2:   makeCmd('🔮', SYS.spirit + ' Give tarot spread interpretation for:'),
  intuition2:   makeCmd('💡', SYS.spirit + ' Give intuition-strengthening tips for:'),
  psychic3:     makeCmd('🔮', SYS.spirit + ' Explain psychic abilities:'),
  clairvoyant:  makeCmd('👁️', SYS.spirit + ' Explain clairvoyance:'),
  clairaud:     makeCmd('👂', SYS.spirit + ' Explain clairaudience:'),
  manifestlaw:  makeCmd('✨', SYS.spirit + ' Explain law of attraction for:'),
  loa2:         makeCmd('🧲', SYS.spirit + ' Give law of attraction tips for:'),
  sigil2:       makeCmd('✨', SYS.spirit + ' Explain sigil magic for:'),
  ritual4:      makeCmd('🕯️', SYS.spirit + ' Create a ritual for:'),
  altar2:       makeCmd('🕯️', SYS.spirit + ' Give altar setup tips for:'),
  ancestor2:    makeCmd('👴', SYS.spirit + ' Explain ancestor work for:'),
  karmalaw2:    makeCmd('⚖️', SYS.spirit + ' Explain karma for:'),
  dharma3:      makeCmd('☸️', SYS.spirit + ' Explain dharma for:'),
  liberation2:  makeCmd('🕊️', SYS.spirit + ' Explain spiritual liberation for:'),
  meditation4:  makeCmd('🧘', SYS.spirit + ' Give meditation tips for:'),
  mantra:       makeCmd('🕉️', SYS.spirit + ' Give mantra meditation tips for:'),
  prayertip:    makeCmd('🙏', SYS.spirit + ' Give prayer tips for:'),
  soulpurpose:  makeCmd('⭐', SYS.spirit + ' Help discover soul purpose for:'),
  higherself:   makeCmd('✨', SYS.spirit + ' Explain higher self connection for:'),
  spiritual2:   makeCmd('🌟', SYS.spirit + ' Give spiritual awakening tips for:'),
  divinetiming: makeCmd('⏰', SYS.spirit + ' Explain divine timing for:'),
  universesgn:  makeCmd('🌌', SYS.spirit + ' Explain universe signs for:'),
};
